SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_PO_DETIL] AS 
(
select a.AUT$UNIT_ID, a.PO_DATE, a.PO_ID, C.BRG_CODE, C.BRG_NAME, b.POD_QTY_ORDER as Qty_order, 
b.POD_PRICE, b.POD_DISC1, b.POD_DISC2, b.POD_DISC3,  b.POD_PPN,b.pod_ppnbm,  b.POD_TOTAL_DISC,
b.POD_TOTAL_TAX, b.POD_TOTAL
from PO A
INNER JOIN PO_DETIL b on b.PO_ID = a.PO_ID
LEFT  JOIN BARANG c on B.BARANG_ID = C.BARANG_ID 
)
GO
