SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SUPPLIER_MERCHANDISE_GROUP] AS 
(
select S.SUPLIER_MERCHAN_GRUP_ID, S.SUPMG_SUB_CODE,SUPMG_NAME, SP.SUP_CODE, SP.SUP_NAME,
     A.REF$MERCHANDISE_ID, A.REF$MERCHANDISE_GRUP_ID, A.MERCHANGRUP_NAME, B.MERCHAN_NAME
     from SUPLIER_MERCHAN_GRUP S
     INNER JOIN SUPLIER SP ON SP.SUPLIER_ID=S.SUPLIER_ID
     INNER JOIN REF$MERCHANDISE_GRUP A ON S.REF$MERCHANDISE_GRUP_ID=A.REF$MERCHANDISE_GRUP_ID
     INNER JOIN REF$MERCHANDISE B ON A.REF$MERCHANDISE_ID = B.REF$MERCHANDISE_ID 

)
GO
