SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_SO_REPORT]
AS
SELECT A.SO_ID, A.SO_NO, A.SO_DATE,
C.MERCHAN_CODE, C.MERCHAN_NAME, G.MERCHANGRUP_CODE, G.MERCHANGRUP_NAME,
D.BRG_CODE, D.BRG_NAME, H.SAT_CODE, 
B.SOD_QTYSO, B.SOD_QTY, B.SOD_PRICE, B.SOD_DISC1, B.SOD_DISC2, B.SOD_DISC3,
B.SOD_STOCK, B.SOD_ADS, B.SOD_ROP, B.SOD_TOTAL, B.SOD_TOTAL_DISC, 
F.SUP_CODE, F.SUP_NAME, F.SUP_ADDRESS, E.SUPMG_LEAD_TIME, E.SUPMG_TOP 
FROM SO A
INNER JOIN SO_DETAIL B ON A.SO_ID=B.SO_ID
INNER JOIN REF$MERCHANDISE C ON C.REF$MERCHANDISE_ID=A.REF$MERCHANDISE_ID
INNER JOIN BARANG D ON D.BARANG_ID=B.BARANG_ID
INNER JOIN SUPLIER_MERCHAN_GRUP E ON E.SUPLIER_MERCHAN_GRUP_ID=B.SUPLIER_MERCHAN_GRUP_ID
INNER JOIN SUPLIER F ON F.SUPLIER_ID=E.SUPLIER_ID
INNER JOIN REF$MERCHANDISE_GRUP G ON G.REF$MERCHANDISE_GRUP_ID=D.REF$MERCHANDISE_GRUP_ID
INNER JOIN REF$SATUAN H ON H.REF$SATUAN_ID = B.REF$SATUAN_ID
GO
