SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V_SO] AS 
select A.SO_ID, A.SO_NO, B.MERCHAN_NAME, D.SUP_CODE, D.SUP_NAME, A.SO_DATE 
from so a
inner join REF$MERCHANDISE b on a.REF$MERCHANDISE_ID=b.REF$MERCHANDISE_ID
left join SUPLIER_MERCHAN_GRUP C ON A.SUPLIER_MERCHAN_GRUP_ID=C.SUPLIER_MERCHAN_GRUP_ID
LEFT JOIN SUPLIER D ON D.SUPLIER_ID = C.SUPLIER_ID


GO
