SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_PO] AS 
(
select a.PO_ID, a.PO_NO, a.PO_DATE, a.PO_DELIVER_DATE, a.PO_VALID_DATE, B.SUPMG_SUB_CODE AS KODE_SUPPLIER_MERCHANDISE_GROUP, 
B.SUPMG_NAME AS SUPPLIER_MERCHANDISE_GROUP , b.SUPMG_TOP as [TOP], A.AUT$UNIT_ID, 
A.PO_TOTAL, A.PO_DISC, A.PO_PPN, A.PO_PPNBM , D.STAPO_NAME AS STATUS, E.SO_NO, D.REF$STATUS_PO_ID
from PO A
LEFT JOIN SUPLIER_MERCHAN_GRUP B ON A.SUPLIER_MERCHAN_GRUP_ID = B.SUPLIER_MERCHAN_GRUP_ID
LEFT JOIN AUT$UNIT C ON A.AUT$UNIT_ID = C.AUT$UNIT_ID
LEFT JOIN REF$STATUS_PO D ON A.REF$STATUS_PO_ID = D.REF$STATUS_PO_ID
LEFT JOIN SO e on a.so_id = e.SO_ID
INNER JOIN PO_DETIL f on a.PO_ID = f.PO_ID
)
GO
