SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[V_AUT$UNIT] AS 
SELECT
a.AUT$UNIT_ID,
a.UNT_CODE as CODE,
a.UNT_NAME AS NAME,
a.UNT_DESCRIPTION AS DESCRIPTION,
d.UNT_NAME as PARENT_NAME,
a.UNT_CONTACT_PERSON AS CONTACT_PERSON,
a.UNT_EMAIL AS EMAIL,
a.UNT_PHONE AS PHONE,
a.UNT_FAX AS FAX,
a.UNT_ADR as ADDRESS,
b.KAB_NAME AS KABUPATEN,
c.PROP_NAME AS PROPINSI,
a.UNT_RGN_CODE AS REGION,
a.UNT_ZIP AS ZIP_CODE,
A.UNT_NPWP AS NPWP,
A.UNT_NPWP_NAME AS NPWP_NAME,
A.UNT_NPWP_ADR AS NPWP_ADDRESS,
A.UNT_NPWP_REG_DATE AS NPWP_REG_DATE
FROM
dbo.[AUT$UNIT] AS a
LEFT JOIN KABUPATEN b on a.KABUPATEN_ID = b.KABUPATEN_ID
LEFT JOIN PROPINSI c on b.PROPINSI_ID = c.PROPINSI_ID
left JOIN AUT$UNIT d on a.UNT_PARENT_ID = d.AUT$UNIT_ID
GO
