CREATE TABLE [dbo].[TRUMUSJURNALITEM]
(
[HEADER_ID] [int] NOT NULL,
[KETERANGAN] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RUMUS] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMPANY_ID] [int] NOT NULL,
[STAMP] [datetime] NULL,
[FLAGITEM] [int] NULL,
[TRUMUSJURNALITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRUMUSJUR__TRUMU__7286E07F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRUMUSJURNALITEM] ADD CONSTRAINT [PK__TRUMUSJU__C6AD1635746F28F1] PRIMARY KEY CLUSTERED  ([TRUMUSJURNALITEM_ID]) ON [PRIMARY]
GO
