CREATE TABLE [dbo].[TEAM_FORM_SOP]
(
[TFSOP_UNT_ID] [int] NOT NULL,
[TFSOP_TSOP_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TFSOP_TSOP_UNT_ID] [int] NOT NULL,
[TFSOP_FSOP_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TFSOP_FSOP_UNT_ID] [int] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TEAM_FORM__DATE___73A521EA] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TEAM_FORM_SOP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TEAM_FORM__TEAM___007FFA1B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEAM_FORM_SOP] ADD CONSTRAINT [PK__TEAM_FOR__672099AB0268428D] PRIMARY KEY CLUSTERED  ([TEAM_FORM_SOP_ID]) ON [PRIMARY]
GO
