CREATE TABLE [dbo].[JURNAL_SALAH]
(
[JURSLH_UNT_ID] [int] NOT NULL,
[JURSLH_JUR_ID] [int] NOT NULL,
[JURSLH_JUR_UNT_ID] [int] NOT NULL,
[JURSLH_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__JURNAL_SA__DATE___69C6B1F5] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[JURNAL_SALAH_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__JURNAL_SA__JURNA__1980B20F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JURNAL_SALAH] ADD CONSTRAINT [PK__JURNAL_S__A89F41AF1B68FA81] PRIMARY KEY CLUSTERED  ([JURNAL_SALAH_ID]) ON [PRIMARY]
GO
