CREATE TABLE [dbo].[MERK]
(
[MERK_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_MERK_MERK_ID] DEFAULT (newid()),
[MERK_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MERK_DESCRIPTION] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MERK_COMP_ID] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[OP_CREATE] [int] NULL,
[OPC_UNIT] [int] NULL,
[DATE_MODIFY] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MERK] ADD CONSTRAINT [PK_MERK] PRIMARY KEY CLUSTERED  ([MERK_ID]) ON [PRIMARY]
GO
