CREATE TABLE [dbo].[ADJUSTMENT_FAKTUR]
(
[ADJFAK_UNT_ID] [int] NOT NULL,
[ADJFAK_DO_NP] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADJFAK_DO_UNT_ID] [int] NOT NULL,
[ADJFAK_ACCADJ_ID] [int] NULL,
[ADJFAK_ACCADJ_UNT_ID] [int] NULL,
[ADJFAK_REF] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJFAK_IS_POSTED] [int] NULL,
[ADJFAK_DATE_POSTED] [datetime] NULL,
[ADJFAK_IS_JURNAL] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__ADJUSTMEN__DATE___07020F21] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ADJFAK_SUPMG_SUB_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJFAK_DATE_RCV] [datetime] NULL CONSTRAINT [DF__ADJUSTMEN__ADJFA__07F6335A] DEFAULT (getdate()),
[ADJFAK_TOTAL_AFTER_DISC] [numeric] (21, 3) NULL,
[ADJFAK_PPN] [numeric] (21, 3) NULL,
[ADJFAK_PPNBM] [numeric] (21, 3) NULL,
[ADJFAK_TOTAL_ADJ] [numeric] (21, 3) NULL,
[ADJFAK_DN] [numeric] (21, 3) NULL,
[ADJFAK_CN] [numeric] (21, 3) NULL,
[ADJFAK_PAYMENT] [numeric] (21, 3) NULL,
[ADJFAK_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJFAK_PO_UNT_ID] [int] NULL,
[ADJFAK_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJFAK_NO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADJUSTMENT_FAKTUR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ADJUSTMEN__ADJUS__407A839F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADJUSTMENT_FAKTUR] ADD CONSTRAINT [PK__ADJUSTME__252A7B6A4262CC11] PRIMARY KEY CLUSTERED  ([ADJUSTMENT_FAKTUR_ID]) ON [PRIMARY]
GO
