CREATE TABLE [dbo].[REF$PAJAK]
(
[PJK_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PJK_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PJK_PPN] [numeric] (7, 2) NULL CONSTRAINT [DF__REF$PAJAK__PJK_P__297722B6] DEFAULT ((0.1)),
[PJK_PPNBM] [numeric] (7, 2) NULL CONSTRAINT [DF__REF$PAJAK__PJK_P__2A6B46EF] DEFAULT ((0)),
[PJK_IS_DEFAULT] [int] NULL CONSTRAINT [DF__REF$PAJAK__PJK_I__2B5F6B28] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$PAJAK__DATE___2C538F61] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$PAJAK_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$PAJAK__ID__24134F1B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$PAJAK] ADD CONSTRAINT [PK__REF$PAJA__3214EC2725FB978D] PRIMARY KEY CLUSTERED  ([REF$PAJAK_ID]) ON [PRIMARY]
GO
