CREATE TABLE [dbo].[TRANSAKSI_DETIL]
(
[TRANSD_UNT_ID] [int] NOT NULL,
[TRANSD_TRANS_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANSD_TRANS_UNT_ID] [int] NOT NULL,
[TRANSD_BHJ_ID] [int] NOT NULL,
[TRANSD_BHJ_UNT_ID] [int] NOT NULL,
[TRANSD_BRG_IS_GMC] [int] NULL,
[TRANSD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__TRANSAKSI__TRANS__2DD1C37F] DEFAULT ((0)),
[TRANSD_TOTAL] [numeric] (21, 3) NULL,
[TRANSD_SELL_PRICE] [numeric] (21, 3) NULL,
[TRANSD_SELL_PRICE_DISC] [numeric] (21, 3) NULL,
[TRANSD_TOTAL_CEIL] [numeric] (21, 3) NULL,
[TRANSD_TOTAL_B4_TAX] [numeric] (21, 3) NULL,
[TRANSD_COGS] [numeric] (21, 3) NULL,
[TRANSD_LAST_COST] [numeric] (21, 3) NULL,
[TRANSD_IS_BKP] [int] NULL,
[TRANSD_PPN] [numeric] (7, 2) NULL,
[TRANSD_PPNBM] [numeric] (7, 2) NULL,
[TRANSD_BRG_IS_PJK_INCLUDE] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TRANSAKSI__DATE___2EC5E7B8] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[TRANSD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSD_TPBRG_ID] [int] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TRANSD_TRANS_ID] [int] NULL,
[TRANSD_DISC_GMC_NOMINAL] [numeric] (21, 3) NULL,
[TRANSD_DISC_CARD] [numeric] (21, 3) NULL CONSTRAINT [DF__TRANSAKSI__TRANS__2FBA0BF1] DEFAULT ((0)),
[TRANSD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSD_DISC_MAN] [numeric] (21, 3) NULL,
[OTO_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSAKSI_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANSAKSI__TRANS__5911273F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSAKSI_DETIL] ADD CONSTRAINT [PK__TRANSAKS__6D5E76FA5AF96FB1] PRIMARY KEY CLUSTERED  ([TRANSAKSI_DETIL_ID]) ON [PRIMARY]
GO
