CREATE TABLE [dbo].[REF$KONVERSI_UKURAN]
(
[KONVUK_UK_CODE_FROM] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KONVUK_UK_CODE_TO] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KONVUK_SCALE] [numeric] (10, 2) NULL CONSTRAINT [DF__REF$KONVE__KONVU__184C96B4] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$KONVE__DATE___1940BAED] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$KONVERSI_UKURAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$KONVE__REF$K__1B9E04AB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$KONVERSI_UKURAN] ADD CONSTRAINT [PK__REF$KONV__D2CC55BF1D864D1D] PRIMARY KEY CLUSTERED  ([REF$KONVERSI_UKURAN_ID]) ON [PRIMARY]
GO
