CREATE TABLE [dbo].[ULINK_PRD]
(
[UPRD_DATE] [datetime] NOT NULL,
[UPRD_UNIT] [int] NOT NULL,
[UPRD_POSCODE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ULINK_PRD_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ULINK_PRD__ULINK__1C7D1A4B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ULINK_PRD] ADD CONSTRAINT [PK__ULINK_PR__2A8DDC1F1E6562BD] PRIMARY KEY CLUSTERED  ([ULINK_PRD_ID]) ON [PRIMARY]
GO
