CREATE TABLE [dbo].[BONUS_ATURAN]
(
[BNS_UNT_ID] [int] NOT NULL,
[BNS_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BNS_BRG_CODE_BNS] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BNS_BRG_BNS_UNT_ID] [int] NOT NULL,
[BNS_SAT_CODE_BNS] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BNS_ORDER_FROM] [int] NULL CONSTRAINT [DF__BONUS_ATU__BNS_O__17036CC0] DEFAULT ((0)),
[BNS_ORDER_TO] [int] NULL CONSTRAINT [DF__BONUS_ATU__BNS_O__17F790F9] DEFAULT ((0)),
[BNS_DATE_FROM] [datetime] NULL CONSTRAINT [DF__BONUS_ATU__BNS_D__18EBB532] DEFAULT (getdate()),
[BNS_DATE_TO] [datetime] NULL,
[BNS_QTY_CS] [numeric] (18, 3) NULL CONSTRAINT [DF__BONUS_ATU__BNS_Q__19DFD96B] DEFAULT ((0)),
[BNS_QTY_SALES] [numeric] (18, 3) NULL CONSTRAINT [DF__BONUS_ATU__BNS_Q__1AD3FDA4] DEFAULT ((0)),
[BNS_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__BONUS_ATU__BNS_Q__1BC821DD] DEFAULT ((0)),
[BNS_IS_ACTIVE] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__BONUS_ATU__DATE___1CBC4616] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[BONUS_ATURAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__BONUS_ATU__BONUS__5FDE205F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BONUS_ATURAN] ADD CONSTRAINT [PK__BONUS_AT__95E00E8661C668D1] PRIMARY KEY CLUSTERED  ([BONUS_ATURAN_ID]) ON [PRIMARY]
GO
