CREATE TABLE [dbo].[REF$TIPE_PO_BARANG]
(
[POBRG_TPPO_ID] [int] NOT NULL,
[POBRG_TPBRG_ID] [int] NOT NULL,
[REF$TIPE_PO_BARANG_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$TIPE___REF$T__2BBF5DDB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_PO_BARANG] ADD CONSTRAINT [PK__REF$TIPE__1DB11D692DA7A64D] PRIMARY KEY CLUSTERED  ([REF$TIPE_PO_BARANG_ID]) ON [PRIMARY]
GO
