CREATE TABLE [dbo].[REF$TIPE_PEMBELI]
(
[TPBL_ID] [int] NOT NULL,
[TPBL_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TPBL_NAME] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$TIPE___DATE___5090EFD7] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$TIPE_PEM__ID__5F3414E9] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_PEMBELI] ADD CONSTRAINT [PK__REF$TIPE__3214EC27611C5D5B] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
