CREATE TABLE [dbo].[PROMO_DETIL]
(
[PROMD_UNT_ID] [int] NOT NULL,
[PROMD_PROM_ID] [int] NOT NULL,
[PROMD_PROM_UNT_ID] [int] NOT NULL,
[PROMD_BRGSUP_ID] [int] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__PROMO_DET__DATE___53A266AC] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[PROMD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMD_MG_ID] [int] NULL,
[PROMD_SUPMG_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[PROMO_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PROMO_DET__PROMO__45943E77] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMO_DETIL] ADD CONSTRAINT [PK__PROMO_DE__ED10BAEE477C86E9] PRIMARY KEY CLUSTERED  ([PROMO_DETIL_ID]) ON [PRIMARY]
GO
