CREATE TABLE [dbo].[LPK_PERIODE]
(
[LPKP_DATE] [datetime] NOT NULL,
[LPKP_UNT] [int] NOT NULL,
[LPKP_STATUS] [int] NOT NULL CONSTRAINT [DF__LPK_PERIO__LPKP___7908F585] DEFAULT ((0)),
[DATE_CREATE] [datetime] NULL,
[LPK_PERIODE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__LPK_PERIO__LPK_P__2200E977] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LPK_PERIODE] ADD CONSTRAINT [PK__LPK_PERI__06A7426C23E931E9] PRIMARY KEY CLUSTERED  ([LPK_PERIODE_ID]) ON [PRIMARY]
GO
