CREATE TABLE [dbo].[REF$DOCUMENT]
(
[DOC_NAME] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$DOCUM__DATE___04459E07] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$DOCUMENT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$DOCUM__REF$D__32816A03] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$DOCUMENT] ADD CONSTRAINT [PK__REF$DOCU__F28D79E13469B275] PRIMARY KEY CLUSTERED  ([REF$DOCUMENT_ID]) ON [PRIMARY]
GO
