CREATE TABLE [dbo].[TPURCHASESUGESTION]
(
[PS_ID] [int] NOT NULL,
[UNT_ID] [int] NOT NULL,
[PS_NOBUKTI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NOT NULL,
[OPC_UNT_ID] [int] NOT NULL,
[DATE_CREATE] [datetime] NOT NULL,
[OP_MODIFY] [int] NOT NULL,
[OPM_UNT_ID] [int] NOT NULL,
[DATE_MODIFY] [datetime] NOT NULL,
[PS_TGLBUKTI] [datetime] NOT NULL,
[PS_TGLJATUHTEMPO] [datetime] NOT NULL,
[PS_KETERANGAN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPURCHASESUGESTION_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TPURCHASE__TPURC__7C4554E3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPURCHASESUGESTION] ADD CONSTRAINT [PK__TPURCHAS__997389BC7E2D9D55] PRIMARY KEY CLUSTERED  ([TPURCHASESUGESTION_ID]) ON [PRIMARY]
GO
