CREATE TABLE [dbo].[TEMP$CLOSE_PER_REVERSE]
(
[COMP_ID] [int] NULL,
[UID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODE] [int] NULL,
[TEMP$CLOSE_PER_REVERSE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TEMP$CLOS__TEMP$__31432D07] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMP$CLOSE_PER_REVERSE] ADD CONSTRAINT [PK__TEMP$CLO__4906FF9A332B7579] PRIMARY KEY CLUSTERED  ([TEMP$CLOSE_PER_REVERSE_ID]) ON [PRIMARY]
GO
