CREATE TABLE [dbo].[ELECTRIC_CUSTOMER]
(
[ELCUST_UNT_ID] [int] NOT NULL,
[ELCUST_CUST_ID] [int] NOT NULL,
[ELCUST_CUST_UNT_ID] [int] NOT NULL,
[ELCUST_KAVLING_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELCUST_DATE_BEGIN] [date] NULL,
[ELCUST_LAST_PROCESS] [date] NULL,
[ELCUST_LAST_INVOICE] [date] NULL,
[ELCUST_IS_ACTIVE] [int] NULL,
[ELCUST_ELECTR_ID] [int] NOT NULL,
[ELCUST_ELECTR_UNT_ID] [int] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__ELECTRIC___DATE___15DA3E5D] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ELECTRIC_CUSTOMER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ELECTRIC___ELECT__713DB68B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELECTRIC_CUSTOMER] ADD CONSTRAINT [PK__ELECTRIC__21229DE27325FEFD] PRIMARY KEY CLUSTERED  ([ELECTRIC_CUSTOMER_ID]) ON [PRIMARY]
GO
