CREATE TABLE [dbo].[REF$UKURAN]
(
[UK_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UK_NAME] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UK_GROUP] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$UKURA__DATE___5CF6C6BC] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$UKURAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$UKURA__REF$U__3B01A16B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$UKURAN] ADD CONSTRAINT [PK__REF$UKUR__817D33103CE9E9DD] PRIMARY KEY CLUSTERED  ([REF$UKURAN_ID]) ON [PRIMARY]
GO
