CREATE TABLE [dbo].[PROMO_RULES]
(
[PRORUL_UNT_ID] [int] NOT NULL,
[PRORUL_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PRORUL_IS_ACTIVE] [int] NULL,
[PRORUL_IS_MULTIPLY] [int] NULL,
[PRORUL_ITEM] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__PROMO_RUL__PRORU__558AAF1E] DEFAULT ('VOUCHER'),
[PRORUL_PRICE_ITEM_PI] [numeric] (21, 3) NULL,
[PRORUL_PRICE_ITEM_OP] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__PROMO_RUL__PRORU__567ED357] DEFAULT ('GE'),
[PRORUL_IS_PRICE_ITEM_USED] [int] NULL,
[PRORUL_PRICE_ALL_PA] [numeric] (21, 3) NULL,
[PRORUL_PRICE_ALL_OP] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__PROMO_RUL__PRORU__5772F790] DEFAULT ('GE'),
[PRORUL_IS_PRICE_ALL_USED] [int] NULL,
[PRORUL_QTY_ITEM_QI] [numeric] (18, 3) NULL CONSTRAINT [DF__PROMO_RUL__PRORU__58671BC9] DEFAULT ((0)),
[PRORUL_QTY_ITEM_OP] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__PROMO_RUL__PRORU__595B4002] DEFAULT ('GE'),
[PRORUL_IS_QTY_ITEM_USED] [int] NULL,
[PRORUL_PI_PA_OP] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__PROMO_RUL__PRORU__5A4F643B] DEFAULT ('OR'),
[PRORUL_PI_QI_OP] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__PROMO_RUL__PRORU__5B438874] DEFAULT ('OR'),
[PRORUL_PA_QI_OP] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__PROMO_RUL__PRORU__5C37ACAD] DEFAULT ('OR'),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__PROMO_RUL__DATE___5D2BD0E6] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[PROMO_RULES_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PROMO_RUL__PROMO__4964CF5B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMO_RULES] ADD CONSTRAINT [PK__PROMO_RU__659579794B4D17CD] PRIMARY KEY CLUSTERED  ([PROMO_RULES_ID]) ON [PRIMARY]
GO
