CREATE TABLE [dbo].[BARANG_SUPLIER]
(
[BARANG_SUPLIER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__BARANG_SU__BARAN__677F4227] DEFAULT (newid()),
[BRGSUP_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BRGSUP_SUPMG_SUB_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BRGSUP_BUY_PRICE] [numeric] (21, 3) NULL,
[BRGSUP_DISC1] [numeric] (7, 2) NULL,
[BRGSUP_DISC2] [numeric] (7, 2) NULL,
[BRGSUP_DISC3] [numeric] (21, 3) NULL,
[BRGSUP_BUY_PRICE_TEMP] [numeric] (21, 3) NULL,
[BRGSUP_BUY_PRICE_DISC] [numeric] (21, 3) NULL,
[BRGSUP_EXPIRE_TIME] [int] NULL CONSTRAINT [DF__BARANG_SU__BRGSU__778AC167] DEFAULT ((0)),
[BRGSUP_SAT_CODE_BUY] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BRGSUP_DELIVERY_TIME] [int] NULL,
[BRGSUP_IS_ENABLE_CN] [int] NULL,
[BRGSUP_STOCK_IN_ORDER] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_SU__BRGSU__787EE5A0] DEFAULT ((0)),
[BRGSUP_MIN_ORDER] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_SU__BRGSU__797309D9] DEFAULT ((0)),
[BRGSUP_MAX_ORDER] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_SU__BRGSU__7A672E12] DEFAULT ((0)),
[BRGSUP_IS_PRIMARY] [int] NOT NULL,
[BRGSUP_IS_BKP] [int] NULL,
[BRGSUP_IS_ACTIVE] [int] NULL,
[BRGSUP_FEE] [numeric] (7, 2) NULL,
[BRGSUP_MARK_UP] [numeric] (7, 2) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__BARANG_SU__DATE___7B5B524B] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[BRGSUP_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SUPLIER_ID] [uniqueidentifier] NULL,
[REF$SATUAN_PURCHASE] [uniqueidentifier] NULL,
[BARANG_ID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BARANG_SUPLIER] ADD CONSTRAINT [PK_Barang_Suplier] PRIMARY KEY NONCLUSTERED  ([BARANG_SUPLIER_ID]) ON [PRIMARY]
GO
