CREATE TABLE [dbo].[PAYMENT_CLAIM_FAKTUR]
(
[PAYCF_UNT_ID] [int] NOT NULL,
[PAYCF_NO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAYCF_DATE] [datetime] NULL CONSTRAINT [DF__PAYMENT_C__PAYCF__1699586C] DEFAULT (getdate()),
[PAYCF_TPBYR_ID] [int] NULL,
[PAYCF_KDJUR_ID] [int] NULL,
[PAYCF_KDJUR_COMP_ID] [int] NULL,
[PAYCF_SUPMG_SUB_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYCF_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYCF_AMOUNT_CLAIM] [numeric] (21, 3) NULL,
[PAYCF_AMOUNT_BALANCE] [numeric] (21, 3) NULL,
[PAYCF_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAYCF_REK_COMP_ID] [int] NOT NULL,
[PAYCF_REF_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAYCF_DUE_DATE] [datetime] NULL,
[PAYCF_AMOUNT_PAYMENT] [numeric] (21, 3) NULL,
[PAYCF_STAPRO_ID] [int] NULL,
[PAYCF_STATUS_NOTE] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYCF_CHECKOUT_DATE] [datetime] NULL,
[PAYCF_IS_JURNAL] [int] NULL,
[PAYCF_CLM_ID] [int] NULL,
[PAYCF_CLM_UNT_ID] [int] NULL,
[PAYCF_CLMCONT_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYCF_CLMCONT_UNT_ID] [int] NULL,
[PAYCF_IS_PAY_POT] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__PAYMENT_C__DATE___178D7CA5] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[PAYCF_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[PAYMENT_CLAIM_FAKTUR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PAYMENT_C__PAYME__735B0927] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYMENT_CLAIM_FAKTUR] ADD CONSTRAINT [PK__PAYMENT___2F6A1EE875435199] PRIMARY KEY CLUSTERED  ([PAYMENT_CLAIM_FAKTUR_ID]) ON [PRIMARY]
GO
