CREATE TABLE [dbo].[TRANSACT]
(
[TRANS_DATE] [datetime] NOT NULL,
[TRANS_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANS_CASH_ID] [int] NOT NULL,
[TRANS_SHIFT_CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANS_MEMBER_ID] [int] NOT NULL,
[TRANS_TOTAL] [float] NOT NULL,
[TRANS_TOTAL_AMC] [float] NOT NULL,
[TRANS_DISC_AMC_PERSEN] [float] NULL,
[TRANS_DISC_AMC_NOMINAL] [float] NULL,
[TRANS_PEMBULAT] [float] NULL,
[TRANS_BAYAR_CASH] [float] NULL,
[TRANS_BAYAR_CARD] [float] NULL,
[TRANS_PAYBACK] [float] NULL,
[TRANS_IS_ACTIVE] [int] NULL,
[TRANSACT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANSACT__TRANSA__25C68D63] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSACT] ADD CONSTRAINT [PK__TRANSACT__E74AEFF127AED5D5] PRIMARY KEY CLUSTERED  ([TRANSACT_ID]) ON [PRIMARY]
GO
