CREATE TABLE [dbo].[REF$STATUS_PROSES]
(
[STAPRO_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STAPRO_NAME] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$STATU__DATE___3AA1AEB8] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$STATUS_PROSES_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$STATU__REF$S__7D197D8B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$STATUS_PROSES] ADD CONSTRAINT [PK__REF$STAT__BB1058DA7F01C5FD] PRIMARY KEY CLUSTERED  ([REF$STATUS_PROSES_ID]) ON [PRIMARY]
GO
