CREATE TABLE [dbo].[TRANSAKSI_CARD]
(
[TRANSC_UNT_ID] [int] NOT NULL,
[TRANSC_TRANS_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANSC_TRANS_UNT_ID] [int] NOT NULL,
[TRANSC_CARD_ID] [int] NOT NULL,
[TRANSC_CARD_UNT_ID] [int] NOT NULL,
[TRANSC_CHARGE] [numeric] (21, 3) NULL,
[TRANSC_NILAI] [numeric] (21, 3) NULL,
[TRANSC_NOMOR] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSC_NO_OTORISASI] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSC_CASHBACK_CHARGE] [numeric] (21, 3) NULL,
[TRANSC_CASHBACK_NILAI] [numeric] (21, 3) NULL,
[TRANSC_IS_ACTIVE] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TRANSAKSI__DATE___2BE97B0D] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TRANSAKSI_CARD_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANSAKSI__TRANS__5CE1B823] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSAKSI_CARD] ADD CONSTRAINT [PK__TRANSAKS__3C741DB15ECA0095] PRIMARY KEY CLUSTERED  ([TRANSAKSI_CARD_ID]) ON [PRIMARY]
GO
