CREATE TABLE [dbo].[TQUOTATIONHARGABELI]
(
[EFFECTIVEDATE] [date] NOT NULL,
[ID] [int] NOT NULL,
[ISPROCESSED] [int] NOT NULL,
[KETERANGAN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NEWSUPPLIER_KODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NEWUNIT_ID] [int] NOT NULL,
[NOBUKTI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOREF] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TGLBUKTI] [date] NOT NULL,
[OP_CREATE] [int] NULL,
[OPC_UNIT] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TQUOTATIO__DATE___1D9B5BB6] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[OPM_UNIT] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[TQUOTATIONHARGABELI_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TQUOTATIO__TQUOT__07B7078F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TQUOTATIONHARGABELI] ADD CONSTRAINT [PK__TQUOTATI__FE49CA9E099F5001] PRIMARY KEY CLUSTERED  ([TQUOTATIONHARGABELI_ID]) ON [PRIMARY]
GO
