CREATE TABLE [dbo].[AUT$GROUP_MODULE]
(
[GMOD_GRO_UNT_ID] [int] NOT NULL,
[GMOD_MOD_UNT_ID] [int] NOT NULL,
[AUT$GROUP_MODULE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AUT$GROUP__AUT$G__09D45A2B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUT$GROUP_MODULE] ADD CONSTRAINT [PK__AUT$GROU__67401EB30BBCA29D] PRIMARY KEY CLUSTERED  ([AUT$GROUP_MODULE_ID]) ON [PRIMARY]
GO
