CREATE TABLE [dbo].[SO]
(
[SO_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SO__SO_ID__5DC0CDC3] DEFAULT (newid()),
[SO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AUT$UNIT_ID] [uniqueidentifier] NULL,
[REF$MERCHANDISE_ID] [uniqueidentifier] NOT NULL,
[SUPLIER_MERCHAN_GRUP_ID] [uniqueidentifier] NULL,
[SO_DATE] [date] NOT NULL CONSTRAINT [DF__SO__SO_DATE__0CA5D9DE] DEFAULT (getdate()),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SO__DATE_CREATE__0D99FE17] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO] ADD CONSTRAINT [PK__SO__AB701DE25FA91635] PRIMARY KEY CLUSTERED  ([SO_ID]) ON [PRIMARY]
GO
