CREATE TABLE [dbo].[TRANS_KUPON_BOTOL_DETIL]
(
[TKBD_UNT_ID] [int] NOT NULL,
[TKBD_TKB_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TKBD_TKB_UNT_ID] [int] NOT NULL,
[TKBD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TKBD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TKBD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__TRANS_KUP__TKBD___45A94D10] DEFAULT ((0)),
[TKBD_SELL_PRICE] [numeric] (21, 3) NULL,
[TKBD_DISC] [numeric] (21, 3) NULL,
[TKBD_SELL_PRICE_DISC] [numeric] (21, 3) NULL,
[TKBD_TOTAL_SELL_PRICE_DISC] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TRANS_KUP__DATE___469D7149] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TRANS_KUPON_BOTOL_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANS_KUP__TRANS__6482D9EB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANS_KUPON_BOTOL_DETIL] ADD CONSTRAINT [PK__TRANS_KU__F5DD3B27666B225D] PRIMARY KEY CLUSTERED  ([TRANS_KUPON_BOTOL_DETIL_ID]) ON [PRIMARY]
GO
