CREATE TABLE [dbo].[SUPLIER_GROUP]
(
[GROUP_NO] [int] NOT NULL,
[GROUP_NAME] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GROUP_DESCRIPTION] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_CREATE] [datetime] NULL,
[OP_CREATE] [int] NULL,
[OPC_UNIT] [int] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPM_UNIT] [int] NULL,
[SUPLIER_GROUP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SUPLIER_G__SUPLI__2A0C1F93] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUPLIER_GROUP] ADD CONSTRAINT [PK__SUPLIER___1281179C2BF46805] PRIMARY KEY CLUSTERED  ([SUPLIER_GROUP_ID]) ON [PRIMARY]
GO
