CREATE TABLE [dbo].[REKENING_PL]
(
[REKPL_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REKPL_COMP_ID] [int] NOT NULL,
[REKPL_DIVISION] [int] NULL CONSTRAINT [DF__REKENING___REKPL__6B44E613] DEFAULT ((0)),
[REKPL_IS_HEADER] [int] NULL,
[REKPL_IS_SUB_TOTAL] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REKENING___DATE___6C390A4C] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[REKENING_PL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REKENING___REKEN__6C98FCFF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REKENING_PL] ADD CONSTRAINT [PK__REKENING__45D5033B6E814571] PRIMARY KEY CLUSTERED  ([REKENING_PL_ID]) ON [PRIMARY]
GO
