CREATE TABLE [dbo].[CLAIM]
(
[CLM_UNT_ID] [int] NOT NULL,
[CLM_SUPMG_SUB_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLM_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLM_TTF_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLM_DATE] [datetime] NULL CONSTRAINT [DF__CLAIM__CLM_DATE__2180FB33] DEFAULT (getdate()),
[CLM_TOTAL] [numeric] (21, 3) NULL,
[CLM_DUE_DATE] [datetime] NULL,
[CLM_RETURN_DATE] [datetime] NULL,
[CLM_MATERAI] [numeric] (21, 3) NULL,
[CLM_REMARK_MATERAI] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLM_TOTAL_ADJ] [numeric] (21, 3) NULL,
[CLM_REMARK_ADJ] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLM_ACCADJ_ID] [int] NULL,
[CLM_ACCADJ_UNT_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CLAIM__DATE_CREA__22751F6C] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[CLM_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLM_TPBYR_ID] [int] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CLAIM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CLAIM__CLAIM_ID__509BDCCF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLAIM] ADD CONSTRAINT [PK__CLAIM__A0BE721B52842541] PRIMARY KEY CLUSTERED  ([CLAIM_ID]) ON [PRIMARY]
GO
