CREATE TABLE [dbo].[SYS$CONSTANT]
(
[CONS_UNT_ID] [int] NOT NULL,
[CONS_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONS_VALUE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONS_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SYS$CONST__DATE___5614BF03] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SYS$CONSTANT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$CONST__SYS$C__1249A49B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$CONSTANT] ADD CONSTRAINT [PK__SYS$CONS__3EA46B6B1431ED0D] PRIMARY KEY CLUSTERED  ([SYS$CONSTANT_ID]) ON [PRIMARY]
GO
