CREATE TABLE [dbo].[GROUP_USER_MERCHANDISE]
(
[GUM_GRO_ID] [int] NOT NULL,
[GUM_GRO_UNT_ID] [int] NOT NULL,
[GUM_MERCHAN_ID] [int] NOT NULL,
[DATE_CREATE] [datetime] NULL,
[DATE_MODIFY] [datetime] NULL,
[OP_CREATE] [int] NULL,
[OP_MODIFY] [int] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[GUM_HO_AUTHORIZE] [int] NOT NULL CONSTRAINT [DF__GROUP_USE__GUM_H__3FD07829] DEFAULT ((0)),
[GROUP_USER_MERCHANDISE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__GROUP_USE__GROUP__63449CEF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUP_USER_MERCHANDISE] ADD CONSTRAINT [PK__GROUP_US__ECC6D681652CE561] PRIMARY KEY CLUSTERED  ([GROUP_USER_MERCHANDISE_ID]) ON [PRIMARY]
GO
