CREATE TABLE [dbo].[REF$STATUS_PO]
(
[STAPO_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STAPO_NAME] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$STATU__DATE___38B96646] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$STATUS_PO_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$STATU__REF$S__00EA0E6F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$STATUS_PO] ADD CONSTRAINT [PK__REF$STAT__620C01D602D256E1] PRIMARY KEY CLUSTERED  ([REF$STATUS_PO_ID]) ON [PRIMARY]
GO
