CREATE TABLE [dbo].[TRANS_KUPON_BOTOL]
(
[TKB_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TKB_UNT_ID] [int] NOT NULL,
[TKB_DATE] [datetime] NULL CONSTRAINT [DF__TRANS_KUP__TKB_D__3FF073BA] DEFAULT (getdate()),
[TKB_INC] [int] NULL CONSTRAINT [DF__TRANS_KUP__TKB_I__40E497F3] DEFAULT ((1)),
[TKB_MEMBER_ID] [int] NOT NULL,
[TKB_MEMBER_UNT_ID] [int] NOT NULL,
[TKB_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TKB_POS_TRANS_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TKB_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__TRANS_KUP__TKB_Q__41D8BC2C] DEFAULT ((0)),
[TKB_SELL_PRICE_DISC] [numeric] (21, 3) NULL,
[TKB_STATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__TRANS_KUP__TKB_S__42CCE065] DEFAULT ('OPEN'),
[TKB_IS_PRINTED] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TRANS_KUP__DATE___43C1049E] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TKB_IS_JURNAL] [int] NULL,
[TRANS_KUPON_BOTOL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANS_KUP__TRANS__67152DD3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANS_KUPON_BOTOL] ADD CONSTRAINT [PK__TRANS_KU__BEE511EE68FD7645] PRIMARY KEY CLUSTERED  ([TRANS_KUPON_BOTOL_ID]) ON [PRIMARY]
GO
