CREATE TABLE [dbo].[PO_PROSES]
(
[POP_UNT_ID] [int] NOT NULL,
[POP_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[POP_PO_UNT_ID] [int] NOT NULL,
[POP_SO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[POP_SO_UNT_ID] [int] NOT NULL,
[POP_DATE] [datetime] NULL CONSTRAINT [DF__PO_PROSES__POP_D__4B0D20AB] DEFAULT (getdate()),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__PO_PROSES__DATE___4C0144E4] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[PO_PROSES_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PO_PROSES__PO_PR__58A712EB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PO_PROSES] ADD CONSTRAINT [PK__PO_PROSE__EC252A315A8F5B5D] PRIMARY KEY CLUSTERED  ([PO_PROSES_ID]) ON [PRIMARY]
GO
