CREATE TABLE [dbo].[CN_RECV_DETIL]
(
[CNRD_UNT_ID] [int] NOT NULL,
[CNRD_CNR_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CNRD_CNR_UNT_ID] [int] NOT NULL,
[CNRD_BRGSUP_ID] [int] NOT NULL,
[CNRD_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CNRD_PO_UNT_ID] [int] NOT NULL,
[CNRD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__CN_RECV_D__CNRD___40058253] DEFAULT ((0)),
[CNRD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNRD_PRICE] [numeric] (21, 3) NULL,
[CNRD_TOTAL] [numeric] (21, 3) NULL,
[CNRD_TOTAL_DISC] [numeric] (21, 3) NULL,
[CNRD_PPN_PERSEN] [numeric] (7, 2) NULL,
[CNRD_PPN] [numeric] (21, 3) NULL,
[CNRD_PPNBM_PERSEN] [numeric] (7, 2) NULL,
[CNRD_PPNBM] [numeric] (21, 3) NULL,
[CNRD_TOTAL_TAX] [numeric] (21, 3) NULL,
[CNRD_IS_CLAIM_TTF] [int] NULL,
[CNRD_IS_PROCESS] [int] NULL,
[CNRD_IS_OUTSTANDING] [int] NULL,
[CNRD_DO_NO_NEW] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNRD_DO_UNT_ID_NEW] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CN_RECV_D__DATE___40F9A68C] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[CNRD_POD_ID] [int] NULL,
[CNRD_POD_UNT_ID] [int] NULL,
[CNRD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNRD_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CN_RECV_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CN_RECV_D__CN_RE__2E46C4CB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CN_RECV_DETIL] ADD CONSTRAINT [PK__CN_RECV___ABEF7AAA302F0D3D] PRIMARY KEY CLUSTERED  ([CN_RECV_DETIL_ID]) ON [PRIMARY]
GO
