CREATE TABLE [dbo].[DN_RECV]
(
[DNR_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNR_UNT_ID] [int] NOT NULL,
[DNR_INV_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DN_RECV__DNR_INV__671F4F74] DEFAULT ('DN-'),
[DNR_DATE] [datetime] NULL CONSTRAINT [DF__DN_RECV__DNR_DAT__681373AD] DEFAULT (getdate()),
[DNR_TOTAL] [numeric] (21, 3) NULL,
[DNR_TOTAL_DISC] [numeric] (21, 3) NULL,
[DNR_PPN] [numeric] (21, 3) NULL,
[DNR_PPNBM] [numeric] (21, 3) NULL,
[DNR_TOTAL_TAX] [numeric] (21, 3) NULL,
[DNR_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__DN_RECV__DATE_CR__690797E6] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[DNR_DO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNR_DO_UNT_ID] [int] NOT NULL,
[DNR_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNR_PO_UNT_ID] [int] NOT NULL,
[DNR_IS_CLAIM] [int] NULL,
[DN_RECV_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__DN_RECV__DN_RECV__61274A53] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DN_RECV] ADD CONSTRAINT [PK__DN_RECV__EEB54566630F92C5] PRIMARY KEY CLUSTERED  ([DN_RECV_ID]) ON [PRIMARY]
GO
