CREATE TABLE [dbo].[CLAIM_INVOICE]
(
[INV_CLMD_ID] [int] NOT NULL,
[INV_CLMD_UNT_ID] [int] NOT NULL,
[INV_DATE] [date] NOT NULL,
[INV_NO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INV_NOMINAL] [float] NOT NULL,
[INV_NP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INV_TAX_DATE] [date] NOT NULL,
[INV_TAX_NO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INV_TAX_NOMINAL] [float] NOT NULL,
[INV_UNT_ID] [int] NOT NULL,
[CLAIM_INVOICE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CLAIM_INV__CLAIM__6A70BD6B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLAIM_INVOICE] ADD CONSTRAINT [PK__CLAIM_IN__F7C0D56D6C5905DD] PRIMARY KEY CLUSTERED  ([CLAIM_INVOICE_ID]) ON [PRIMARY]
GO
