CREATE TABLE [dbo].[TSTOCKADJUSTMENTITEM]
(
[BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[QTYIN] [float] NOT NULL,
[QTYOUT] [float] NOT NULL,
[HARGA_AVG] [float] NULL,
[ISBONUS] [int] NOT NULL,
[UOM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HEADERUNIT_ID] [int] NOT NULL,
[PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PO_NO_UNT] [int] NULL,
[TSTOCKADJUSTMENTITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TSTOCKADJ__TSTOC__24885067] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TSTOCKADJUSTMENTITEM] ADD CONSTRAINT [PK__TSTOCKAD__25CAC0A0267098D9] PRIMARY KEY CLUSTERED  ([TSTOCKADJUSTMENTITEM_ID]) ON [PRIMARY]
GO
