CREATE TABLE [dbo].[RAFAKSI_INVOICE]
(
[RAFI_RAF_ID] [int] NOT NULL,
[RAFI_RAF_UNT_ID] [int] NULL,
[RAFI_ID] [int] NOT NULL,
[RAFI_UNT_ID] [int] NOT NULL,
[RAFI_TGL_INV] [date] NULL,
[RAFI_NILAI_INV] [float] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[RAFI_INV_NO] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RAFAKSI_INVOICE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__RAFAKSI_I__RAFAK__168F36CB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RAFAKSI_INVOICE] ADD CONSTRAINT [PK__RAFAKSI___C793EAA418777F3D] PRIMARY KEY CLUSTERED  ([RAFAKSI_INVOICE_ID]) ON [PRIMARY]
GO
