CREATE TABLE [dbo].[CLAIM_POTONGAN]
(
[CLMPOT_UNT_ID] [int] NOT NULL,
[CLMPOT_CLMD_ID] [int] NOT NULL,
[CLMPOT_CLMD_UNT_ID] [int] NOT NULL,
[CLMPOT_PTD_ID] [int] NOT NULL,
[CLMPOT_PTD_UNT_ID] [int] NOT NULL,
[CLMPOT_TOTAL] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CLAIM_POT__DATE___2EDAF651] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CLAIM_POTONGAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CLAIM_POT__CLAIM__3D89085B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLAIM_POTONGAN] ADD CONSTRAINT [PK__CLAIM_PO__F07E427B3F7150CD] PRIMARY KEY CLUSTERED  ([CLAIM_POTONGAN_ID]) ON [PRIMARY]
GO
