CREATE TABLE [dbo].[LPK]
(
[LPK_TGLAWAL] [date] NOT NULL,
[LPK_TGLAKHIR] [date] NOT NULL,
[LPK_UNT_ID] [int] NOT NULL,
[LPK_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LPK_BRG_CODE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LPK_BRG_ALIAS] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LPK_HARGA_BELI] [float] NULL,
[LPK_HARGA_JUAL] [float] NULL,
[LPK_QTY_PO] [float] NULL,
[LPK_QTY_RECV] [float] NULL,
[LPK_QTY_AWAL] [float] NULL,
[LPK_JUAL_QTY] [float] NULL,
[LPK_JUAL_HARGA_BELI] [float] NULL,
[LPK_JUAL_HARGA_JUAL] [float] NULL,
[LPK_ENDING_QTY] [float] NULL,
[LPK_ENDING_HARGA_BELI] [float] NULL,
[LPK_ENDING_HARGA_JUAL] [float] NULL,
[LPK_JUAL_PPN] [float] NULL,
[LPK_QTY_BTI_RECV] [float] NULL,
[LPK_QTY_BTI_OUT] [float] NULL,
[LPK_QTY_BTI_RTROUT] [float] NULL,
[LPK_QTY_RETUR] [float] NULL,
[LPK_HARI] [int] NULL,
[LPK_BULAN] [int] NULL,
[LPK_TAHUN] [int] NULL,
[LPK_SUP_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LPK_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LPK_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LPK_QTY_RTRIN] [float] NULL,
[LPK_QTY_BTI_RTRIN] [float] NULL,
[DATE_CREATE] [datetime] NULL,
[LPK_PO_UNT_ID] [int] NULL,
[LPK_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__LPK__LPK_ID__1A5FC7AF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LPK] ADD CONSTRAINT [PK__LPK__984899931C481021] PRIMARY KEY CLUSTERED  ([LPK_ID]) ON [PRIMARY]
GO
