CREATE TABLE [dbo].[IGRA_KETERANGAN]
(
[IGRKET_UNT_ID] [int] NOT NULL,
[IGRKET_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IGRKET_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__IGRA_KETE__DATE___59904A2C] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[IGRA_KETERANGAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__IGRA_KETE__IGRA___2C938683] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IGRA_KETERANGAN] ADD CONSTRAINT [PK__IGRA_KET__EC9C16FC2E7BCEF5] PRIMARY KEY CLUSTERED  ([IGRA_KETERANGAN_ID]) ON [PRIMARY]
GO
