CREATE TABLE [dbo].[BANK]
(
[BANK_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BANK_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BANK_BRANCH] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ADDRESS] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_REK_COMP_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__BANK__DATE_CREAT__52593CB8] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[BANK_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANK_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__BANK__ID__1C722D53] DEFAULT (newid()),
[REKENING_ID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BANK] ADD CONSTRAINT [PK__BANK__3214EC271E5A75C5] PRIMARY KEY CLUSTERED  ([BANK_ID]) ON [PRIMARY]
GO
