CREATE TABLE [dbo].[ADJUSTMENT_PRODUCT_DETIL]
(
[APD_UNT_ID] [int] NOT NULL,
[APD_ADJPROD_ID] [int] NOT NULL,
[APD_ADJPROD_UNT_ID] [int] NOT NULL,
[APD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APD_NO_PO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APD_PURCHASE_PRICE] [numeric] (21, 3) NULL,
[APD_COGS] [numeric] (21, 3) NULL,
[APD_LAST_COST] [numeric] (21, 3) NULL,
[APD_QTY] [numeric] (18, 3) NULL,
[APD_TOTAL] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__ADJUSTMEN__DATE___0EA330E9] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ADJUSTMENT_PRODUCT_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ADJUSTMEN__ADJUS__5E94F66B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADJUSTMENT_PRODUCT_DETIL] ADD CONSTRAINT [PK__ADJUSTME__0F1BB2E0607D3EDD] PRIMARY KEY CLUSTERED  ([ADJUSTMENT_PRODUCT_DETIL_ID]) ON [PRIMARY]
GO
