CREATE TABLE [dbo].[THOIMPORT_ITEM]
(
[SQL] [image] NOT NULL,
[URUTAN] [int] NOT NULL,
[UNITID] [int] NOT NULL,
[STOREIMPORT_ID] [int] NOT NULL,
[UNITSRC] [int] NULL,
[THOIMPORT_ITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__THOIMPORT__THOIM__62CF9BA3] DEFAULT (newid())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[THOIMPORT_ITEM] ADD CONSTRAINT [PK__THOIMPOR__CDF4A51F64B7E415] PRIMARY KEY CLUSTERED  ([THOIMPORT_ITEM_ID]) ON [PRIMARY]
GO
