CREATE TABLE [dbo].[THOTRANSFERSQL]
(
[ID] [int] NOT NULL,
[NEWUNIT_ID] [int] NOT NULL,
[NOBUKTI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TGLBUKTI] [date] NOT NULL,
[URUTAN] [int] NOT NULL,
[STAMP] [datetime] NULL,
[THOTRANSFERSQL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__THOTRANSF__THOTR__524F1B17] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[THOTRANSFERSQL] ADD CONSTRAINT [PK__THOTRANS__F3FE27CB54376389] PRIMARY KEY CLUSTERED  ([THOTRANSFERSQL_ID]) ON [PRIMARY]
GO
