CREATE TABLE [dbo].[QUOTATION]
(
[QUOTATION_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__QUOTATION__QUOTA__321755AF] DEFAULT (newid()),
[SUPLIER_MERCHAN_GRUP_ID] [uniqueidentifier] NOT NULL,
[QUOT_REF_NO] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUOT_DATE] [datetime] NULL,
[QUOT_DATE_EFFECTIVE] [date] NOT NULL,
[QUOT_END_DATE] [date] NULL,
[QUOT_IS_MAILER] [int] NOT NULL CONSTRAINT [DF_QUOTATION_QUOT_IS_MAILER] DEFAULT ((0)),
[QUOT_REMARK] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUOT_IS_PROCESSED] [int] NOT NULL CONSTRAINT [DF__QUOTATION__QUOT___61F08603] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__QUOTATION__DATE___62E4AA3C] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[QUOT_UNT_ID] [int] NOT NULL,
[QUOT_SUPMG_SUB_CODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QUOTATION] ADD CONSTRAINT [PK__QUOTATIO__C29D449833FF9E21] PRIMARY KEY CLUSTERED  ([QUOTATION_ID]) ON [PRIMARY]
GO
