CREATE TABLE [dbo].[MEMBER_KELUARGA]
(
[MEMBERKLRG_ID] [int] NOT NULL,
[MEMBERKLRG_UNT_ID] [int] NOT NULL,
[MEMBERKLRG_MEMBER_ID] [int] NOT NULL,
[MEMBERKLRG_MEMBER_UNT_ID] [int] NOT NULL,
[MEMBERKLRG_STAKLRG_ID] [int] NOT NULL,
[MEMBERKLRG_FULL_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBERKLRG_BIRTH_DATE] [date] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[MEMBER_KELUARGA_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__MEMBER_KE__MEMBE__705EA0EB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEMBER_KELUARGA] ADD CONSTRAINT [PK__MEMBER_K__401F24637246E95D] PRIMARY KEY CLUSTERED  ([MEMBER_KELUARGA_ID]) ON [PRIMARY]
GO
