CREATE TABLE [dbo].[TKODEGLTRANS]
(
[CLASSNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STAMP] [datetime] NULL,
[COMPANY_ID] [int] NOT NULL,
[TKODEGLTRANS_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TKODEGLTR__TKODE__36BC0F3B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TKODEGLTRANS] ADD CONSTRAINT [PK__TKODEGLT__C8F3E73F38A457AD] PRIMARY KEY CLUSTERED  ([TKODEGLTRANS_ID]) ON [PRIMARY]
GO
