CREATE TABLE [dbo].[GUDANG_BARANG]
(
[GUDBRG_GUD_ID] [int] NOT NULL,
[GUDBRG_GUD_UNT_ID] [int] NOT NULL,
[GUDBRG_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GUDBRG_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__GUDANG_BA__GUDBR__43A1090D] DEFAULT ((0)),
[GUDBRG_QTY_COMMON] [numeric] (18, 3) NULL CONSTRAINT [DF__GUDANG_BA__GUDBR__44952D46] DEFAULT ((0)),
[GUDBRG_QTY_TRADER] [numeric] (18, 3) NULL CONSTRAINT [DF__GUDANG_BA__GUDBR__4589517F] DEFAULT ((0)),
[GUDBRG_QTY_ASSGROS] [numeric] (18, 3) NULL CONSTRAINT [DF__GUDANG_BA__GUDBR__467D75B8] DEFAULT ((0)),
[GUDBRG_DATE] [datetime] NULL CONSTRAINT [DF__GUDANG_BA__GUDBR__477199F1] DEFAULT (getdate()),
[GUDBRG_IS_OUT] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__GUDANG_BA__DATE___4865BE2A] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[GUDANG_BARANG_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__GUDANG_BA__GUDAN__3434A84B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GUDANG_BARANG] ADD CONSTRAINT [PK__GUDANG_B__D5F3A28A361CF0BD] PRIMARY KEY CLUSTERED  ([GUDANG_BARANG_ID]) ON [PRIMARY]
GO
