CREATE TABLE [dbo].[REF$BULAN]
(
[BULAN_NO] [int] NOT NULL,
[REF$BULAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$BULAN__REF$B__38E44ECF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$BULAN] ADD CONSTRAINT [PK__REF$BULA__E3EE74A03ACC9741] PRIMARY KEY CLUSTERED  ([REF$BULAN_ID]) ON [PRIMARY]
GO
