CREATE TABLE [dbo].[TPOTONGANFAKTURITEM]
(
[CLAIMFAKTUR_ID] [int] NOT NULL,
[CLAIMFAKTURUNIT_ID] [int] NOT NULL,
[NAMAPOTONGAN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NEWUNIT_ID] [int] NOT NULL,
[NOMINAL] [float] NOT NULL,
[TPOTONGANFAKTURITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TPOTONGAN__TPOTO__5EFF0ABF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPOTONGANFAKTURITEM] ADD CONSTRAINT [PK__TPOTONGA__2DCE225860E75331] PRIMARY KEY CLUSTERED  ([TPOTONGANFAKTURITEM_ID]) ON [PRIMARY]
GO
