CREATE TABLE [dbo].[CUSTOMER_VOUCHER]
(
[CUSTV_UNT_ID] [int] NOT NULL,
[CUSTV_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUSTV_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUSTV_ADDRESS] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTV_TELP] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTV_CONTACT_PERSON] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTV_COUNTER] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CUSTOMER___DATE___5F7E2DAC] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CUSTOMER_VOUCHER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CUSTOMER___CUSTO__0FC23DAB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMER_VOUCHER] ADD CONSTRAINT [PK__CUSTOMER__6A34B1A811AA861D] PRIMARY KEY CLUSTERED  ([CUSTOMER_VOUCHER_ID]) ON [PRIMARY]
GO
