CREATE TABLE [dbo].[REF$MERCHANDISE_GRUP]
(
[MERCHANGRUP_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MERCHANGRUP_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MERCHANGRUP_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MERCHANGRUP_COMP_ID] [int] NULL,
[MERCHANGRUP_DEF_MARK_UP] [numeric] (7, 2) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$MERCH__DATE___24B26D99] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[MERCHANGRUP_HO_AUTHORIZE] [int] NOT NULL CONSTRAINT [DF__REF$MERCH__MERCH__25A691D2] DEFAULT ((0)),
[REF$MERCHANDISE_GRUP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$MERCHAND__ID__4944D3CA] DEFAULT (newid()),
[REF$MERCHANDISE_ID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$MERCHANDISE_GRUP] ADD CONSTRAINT [PK__REF$MERC__3214EC274B2D1C3C] PRIMARY KEY CLUSTERED  ([REF$MERCHANDISE_GRUP_ID]) ON [PRIMARY]
GO
