CREATE TABLE [dbo].[REF$AGAMA]
(
[AGAMA_NAME] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$AGAMA__DATE___7D98A078] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[REF$AGAMA_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$AGAMA__REF$A__3A228BCB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$AGAMA] ADD CONSTRAINT [PK__REF$AGAM__62EE8A113C0AD43D] PRIMARY KEY CLUSTERED  ([REF$AGAMA_ID]) ON [PRIMARY]
GO
