CREATE TABLE [dbo].[QUOTATION_PROMO]
(
[QUOT_UNT_ID] [int] NOT NULL,
[QUOT_DATE] [datetime] NULL,
[QUOT_REF_NO] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUOT_DATE_EFFECTIVE] [datetime] NULL,
[QUOT_REMARK] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUOT_IS_PROCESSED] [int] NULL CONSTRAINT [DF__QUOTATION__QUOT___6F4A8121] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[QUOT_IS_MAILER] [int] NULL,
[QUOT_END_DATE] [datetime] NULL,
[QUOTATION_PROMO_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__QUOTATION__QUOTA__79B300FB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QUOTATION_PROMO] ADD CONSTRAINT [PK__QUOTATIO__7D04502D7B9B496D] PRIMARY KEY CLUSTERED  ([QUOTATION_PROMO_ID]) ON [PRIMARY]
GO
