CREATE TABLE [dbo].[CONTRABON_SALES]
(
[CONT_UNT_ID] [int] NOT NULL,
[CONT_DATE_SALES] [datetime] NOT NULL,
[CONT_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONT_GROSS_SALES] [numeric] (21, 3) NULL CONSTRAINT [DF__CONTRABON__CONT___4F47C5E3] DEFAULT ((0)),
[CONT_DISC_AMOUNT] [numeric] (21, 3) NULL CONSTRAINT [DF__CONTRABON__CONT___503BEA1C] DEFAULT ((0)),
[CONT_TAX_AMOUNT] [numeric] (21, 3) NULL CONSTRAINT [DF__CONTRABON__CONT___51300E55] DEFAULT ((0)),
[CONT_NET_SALES] [numeric] (21, 3) NULL CONSTRAINT [DF__CONTRABON__CONT___5224328E] DEFAULT ((0)),
[CONT_TOTAL_SALES] [numeric] (21, 3) NULL CONSTRAINT [DF__CONTRABON__CONT___531856C7] DEFAULT ((0)),
[CONT_FEE] [numeric] (7, 2) NULL CONSTRAINT [DF__CONTRABON__CONT___540C7B00] DEFAULT ((0)),
[CONT_IS_VALIDATED] [int] NULL,
[CONT_IS_CLAIM] [int] NULL,
[CONT_IS_CONTRABON] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CONTRABON__DATE___55009F39] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[CONT_SUPMG_SUB_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONT_TPBRG_ID] [int] NOT NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CONT_DISC_AMC] [float] NULL,
[CONT_MG_ID] [int] NULL,
[CONTRABON_SALES_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CONTRABON__CONTR__1B33F057] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTRABON_SALES] ADD CONSTRAINT [PK__CONTRABO__CFC1CCEA1D1C38C9] PRIMARY KEY CLUSTERED  ([CONTRABON_SALES_ID]) ON [PRIMARY]
GO
