CREATE TABLE [dbo].[SYS$VER]
(
[SYSVER_VER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SYSVER_TIME] [datetime] NULL CONSTRAINT [DF__SYS$VER__SYSVER___6CF8245B] DEFAULT (getdate()),
[SYS$VER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$VER__SYS$VER__743A1EC7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$VER] ADD CONSTRAINT [PK__SYS$VER__7217B73476226739] PRIMARY KEY CLUSTERED  ([SYS$VER_ID]) ON [PRIMARY]
GO
