CREATE TABLE [dbo].[GENERAL_LEDGER_CLOSE_YEAR]
(
[GLCY_COMP_ID] [int] NOT NULL,
[GLCY_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GLCY_REK_COMP_ID] [int] NOT NULL,
[GLCY_DATE] [datetime] NOT NULL CONSTRAINT [DF__GENERAL_L__GLCY___3552E9B6] DEFAULT (getdate()),
[GLCY_BEGIN_BAL] [numeric] (21, 3) NULL,
[GLCY_DEBET] [numeric] (21, 3) NULL,
[GLCY_CREDIT] [numeric] (21, 3) NULL,
[GLCY_BAL] [numeric] (21, 3) NULL,
[GLCY_LAST_BAL] [numeric] (21, 3) NULL,
[GLCY_RESV_1] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__GENERAL_L__DATE___36470DEF] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[GENERAL_LEDGER_CLOSE_YEAR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__GENERAL_L__GENER__4B180DA3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GENERAL_LEDGER_CLOSE_YEAR] ADD CONSTRAINT [PK__GENERAL___D07EF3E04D005615] PRIMARY KEY CLUSTERED  ([GENERAL_LEDGER_CLOSE_YEAR_ID]) ON [PRIMARY]
GO
