CREATE TABLE [dbo].[AUT$USER_GROUP]
(
[UG_USR_ID] [int] NOT NULL,
[UG_USR_UNT_ID] [int] NOT NULL,
[UG_GRO_ID] [int] NOT NULL,
[UG_GRO_UNT_ID] [int] NOT NULL,
[AUT$USER_GROUP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AUT$USER___AUT$U__096A45D7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUT$USER_GROUP] ADD CONSTRAINT [PK__AUT$USER__6F33298E0B528E49] PRIMARY KEY CLUSTERED  ([AUT$USER_GROUP_ID]) ON [PRIMARY]
GO
