CREATE TABLE [dbo].[TEMP$PROFIT_LOSS_REPORT_GENERATOR]
(
[LINE_NO] [int] NOT NULL,
[DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_INCOME] [int] NULL CONSTRAINT [DF__TEMP$PROF__IS_IN__03DB89B3] DEFAULT ((1)),
[TEMP$PROFIT_LOSS_REPORT_GENERATOR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TEMP$PROF__TEMP$__2C29722F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMP$PROFIT_LOSS_REPORT_GENERATOR] ADD CONSTRAINT [PK__TEMP$PRO__64EB3D5C2E11BAA1] PRIMARY KEY CLUSTERED  ([TEMP$PROFIT_LOSS_REPORT_GENERATOR_ID]) ON [PRIMARY]
GO
