CREATE TABLE [dbo].[TRANS_BARANG_TURUNAN]
(
[TBRGTUR_UNT_ID] [int] NOT NULL,
[TBRGTUR_ADJ_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TBRGTUR_DATE] [datetime] NULL CONSTRAINT [DF__TRANS_BAR__TBRGT__3943762B] DEFAULT (getdate()),
[TBRGTUR_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TBRGTUR_STATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__TRANS_BAR__TBRGT__3A379A64] DEFAULT (' ''OPEN'''),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TRANS_BAR__DATE___3B2BBE9D] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TRANS_BARANG_TURUNAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANS_BAR__TRANS__6C23FBB3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANS_BARANG_TURUNAN] ADD CONSTRAINT [PK__TRANS_BA__1393EA016E0C4425] PRIMARY KEY CLUSTERED  ([TRANS_BARANG_TURUNAN_ID]) ON [PRIMARY]
GO
