CREATE TABLE [dbo].[TGENERATOR]
(
[GENERATOR_NAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQL_NAME] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TGENERATOR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TGENERATO__TGENE__46DD686B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TGENERATOR] ADD CONSTRAINT [PK__TGENERAT__0E3B115348C5B0DD] PRIMARY KEY CLUSTERED  ([TGENERATOR_ID]) ON [PRIMARY]
GO
