CREATE TABLE [dbo].[ADJUSTMENT_FAKTUR_DETIL]
(
[AFD_UNT_ID] [int] NOT NULL,
[AFD_ADJFAK_ID] [int] NOT NULL,
[AFD_ADJFAK_UNT_ID] [int] NOT NULL,
[AFD_DOD_ID] [int] NOT NULL,
[AFD_DOD_UNT_ID] [int] NOT NULL,
[AFD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__ADJUSTMEN__AFD_Q__09DE7BCC] DEFAULT ((1)),
[AFD_PRICE] [numeric] (21, 3) NULL,
[AFD_DISC] [numeric] (21, 3) NULL,
[AFD_PPN] [numeric] (7, 2) NULL,
[AFD_PPNBM] [numeric] (7, 2) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__ADJUSTMEN__DATE___0AD2A005] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[AFD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AFD_VAL_ADJ_AFTER_DISC] [numeric] (21, 3) NULL,
[AFD_VAL_ADJ_PPN] [numeric] (21, 3) NULL,
[AFD_VAL_ADJ_PPNBM] [numeric] (21, 3) NULL,
[AFD_VAL_ADJ_TOTAL] [numeric] (21, 3) NULL,
[AFD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJUSTMENT_FAKTUR_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ADJUSTMEN__ADJUS__4FBCC72F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADJUSTMENT_FAKTUR_DETIL] ADD CONSTRAINT [PK__ADJUSTME__A996BA3051A50FA1] PRIMARY KEY CLUSTERED  ([ADJUSTMENT_FAKTUR_DETIL_ID]) ON [PRIMARY]
GO
