CREATE TABLE [dbo].[KOMPETITOR]
(
[KOMPT_UNT_ID] [int] NOT NULL,
[KOMPT_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KOMPT_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KOMPT_IS_ACTIVE] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__KOMPETITO__DATE___6CA31EA0] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[KOMPETITOR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__KOMPETITO__KOMPE__15B0212B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KOMPETITOR] ADD CONSTRAINT [PK__KOMPETIT__4AC91CC51798699D] PRIMARY KEY CLUSTERED  ([KOMPETITOR_ID]) ON [PRIMARY]
GO
