CREATE TABLE [dbo].[VENDOR_GROUP]
(
[GROUP_NO] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GROUP_NAME] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GROUP_DESCRIPTION] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_CREATE] [datetime] NULL,
[DATE_MODIFY] [datetime] NULL,
[VENDOR_GROUP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__VENDOR_GR__VENDO__33607FA3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENDOR_GROUP] ADD CONSTRAINT [PK__VENDOR_G__335B8A323548C815] PRIMARY KEY CLUSTERED  ([VENDOR_GROUP_ID]) ON [PRIMARY]
GO
