CREATE TABLE [dbo].[SYS$PARAMETER_UNIT]
(
[PARU_PARTMP_ID] [int] NOT NULL,
[PARU_UNT_ID] [int] NOT NULL,
[PARU_VALUE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SYS$PARAM__DATE___627A95E8] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[SYS$PARAMETER_UNIT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$PARAM__SYS$P__0307610B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$PARAMETER_UNIT] ADD CONSTRAINT [PK__SYS$PARA__FDDEB05504EFA97D] PRIMARY KEY CLUSTERED  ([SYS$PARAMETER_UNIT_ID]) ON [PRIMARY]
GO
