CREATE TABLE [dbo].[THOIMPORT]
(
[NOBUKTI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TANGGAL] [datetime] NOT NULL,
[UNITID] [int] NOT NULL,
[URUTAN] [int] NOT NULL,
[UNITSRC] [int] NULL,
[THOIMPORT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__THOIMPORT__THOIM__66A02C87] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[THOIMPORT] ADD CONSTRAINT [PK__THOIMPOR__B1C5C125688874F9] PRIMARY KEY CLUSTERED  ([THOIMPORT_ID]) ON [PRIMARY]
GO
