CREATE TABLE [dbo].[REF$TIPE_PERUSAHAAN]
(
[TPPERSH_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TPPERSH_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TPPERSH_IS_DEFAULT] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$TIPE___DATE___52793849] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[REF$TIPE_PERUSAHAAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$TIPE___REF$T__7CC477D0] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_PERUSAHAAN] ADD CONSTRAINT [PK__REF$TIPE__1BCF81727EACC042] PRIMARY KEY CLUSTERED  ([REF$TIPE_PERUSAHAAN_ID]) ON [PRIMARY]
GO
