CREATE TABLE [dbo].[IGRA_DETIL]
(
[IGRD_UNT_ID] [int] NOT NULL,
[IGRD_IGR_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IGRD_IGR_UNT_ID] [int] NOT NULL,
[IGRD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IGRD_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IGRD_PO_UNT_ID] [int] NULL,
[IGRD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__IGRA_DETI__IGRD___55BFB948] DEFAULT ((0)),
[IGRD_ACTUAL_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__IGRA_DETI__IGRD___56B3DD81] DEFAULT ((0)),
[IGRD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IGRD_PRICE] [numeric] (21, 3) NULL,
[IGRD_TPCN_ID] [int] NULL,
[IGRD_TPCN_UNT_ID] [int] NULL,
[IGRD_IS_PROCESS] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__IGRA_DETI__DATE___57A801BA] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[IGRA_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__IGRA_DETI__IGRA___30641767] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IGRA_DETIL] ADD CONSTRAINT [PK__IGRA_DET__455E8146324C5FD9] PRIMARY KEY CLUSTERED  ([IGRA_DETIL_ID]) ON [PRIMARY]
GO
