CREATE TABLE [dbo].[BANK_ACCOUNT]
(
[BNKACC_ID] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BNKACC_NOREK] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BNKACC_AUTH_ID] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BNKACC_STATUS] [image] NULL,
[BNKACC_BANK_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_CREATE] [datetime] NULL,
[DATE_MODIFY] [datetime] NULL,
[BANK_ACCOUNT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__BANK_ACCO__BANK___204DAB2F] DEFAULT (newid())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[BANK_ACCOUNT] ADD CONSTRAINT [PK__BANK_ACC__71617E542235F3A1] PRIMARY KEY CLUSTERED  ([BANK_ACCOUNT_ID]) ON [PRIMARY]
GO
