CREATE TABLE [dbo].[STANDAR_JURNAL]
(
[STDJ_COMP_ID] [int] NOT NULL,
[STDJ_KDJUR_ID] [int] NOT NULL,
[STDJ_KDJUR_COMP_ID] [int] NOT NULL,
[STDJ_REK_CODE_FROM] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STDJ_REK_COMP_ID_FROM] [int] NOT NULL,
[STDJ_REK_CODE_TO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STDJ_REK_COMP_ID_TO] [int] NOT NULL,
[STDJ_TRANSACTION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__STANDAR_J__DATE___190BB0C3] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[STANDAR_JURNAL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__STANDAR_J__STAND__255C790F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STANDAR_JURNAL] ADD CONSTRAINT [PK__STANDAR___977BE6B82744C181] PRIMARY KEY CLUSTERED  ([STANDAR_JURNAL_ID]) ON [PRIMARY]
GO
