CREATE TABLE [dbo].[REF$OUTLET]
(
[OUTLET_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OUTLET_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OUTLET_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$OUTLE__DATE___278EDA44] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$OUTLET_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$OUTLET__ID__6304A5CD] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$OUTLET] ADD CONSTRAINT [PK__REF$OUTL__3214EC2764ECEE3F] PRIMARY KEY CLUSTERED  ([REF$OUTLET_ID]) ON [PRIMARY]
GO
