CREATE TABLE [dbo].[SCENARIO]
(
[SCEN_UNT_ID] [int] NOT NULL,
[SCEN_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SCEN_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SCEN_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCEN_KDJUR_ID] [int] NULL,
[SCEN_KDJUR_COMP_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SCENARIO__DATE_C__72E607DB] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SCENARIO_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SCENARIO__SCENAR__4F52B2DB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SCENARIO] ADD CONSTRAINT [PK__SCENARIO__467D35C3513AFB4D] PRIMARY KEY CLUSTERED  ([SCENARIO_ID]) ON [PRIMARY]
GO
