CREATE TABLE [dbo].[AGING_AR_KRING]
(
[AAK_TANGGAL] [date] NOT NULL,
[AAK_TRADER_CODE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AAK_TRADER_NAME] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AAK_BELUM_JTH_TEMPO] [float] NULL,
[AAK_1_7] [float] NULL,
[AAK_8_14] [float] NULL,
[AAK_15_21] [float] NULL,
[AAK_22_28] [float] NULL,
[AAK_LBH_BESAR_28] [float] NULL,
[AAK_UNT_ID] [int] NOT NULL,
[AAK_TOTAL] [float] NULL,
[AAK_DOAS_NO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AAK_DOAS_DATE_RECEIPT] [date] NULL,
[AGING_AR_KRING_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AGING_AR___AGING__0B879873] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGING_AR_KRING] ADD CONSTRAINT [PK__AGING_AR__96B1BF600D6FE0E5] PRIMARY KEY CLUSTERED  ([AGING_AR_KRING_ID]) ON [PRIMARY]
GO
