CREATE TABLE [dbo].[SUPLIER_NBD]
(
[SUPNBD_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUPNBD_UNT_ID] [int] NOT NULL,
[SUPNBD_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUPNBD_ADDRESS] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUPNBD_CITY] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPNBD_POST_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPNBD_TELP] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPNBD_FAX] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPNBD_CONTACT_PERSON] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPNBD_TITLE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPNBD_NPWP] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPNBD_TYPE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SUPLIER_N__DATE___32CB82C6] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SUPLIER_NBD_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SUPLIER_N__SUPLI__40EF84EB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUPLIER_NBD] ADD CONSTRAINT [PK__SUPLIER___2B883B8A42D7CD5D] PRIMARY KEY CLUSTERED  ([SUPLIER_NBD_ID]) ON [PRIMARY]
GO
