CREATE TABLE [dbo].[WASTAGE_OBRAL_DETIL]
(
[WOD_UNT_ID] [int] NOT NULL,
[WOD_WSTOB_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WOD_WSTOB_UNT_ID] [int] NOT NULL,
[WOD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WOD_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WOD_PO_UNT_ID] [int] NULL,
[WOD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__WASTAGE_O__WOD_Q__670A40DB] DEFAULT ((0)),
[WOD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WOD_PRICE] [numeric] (21, 3) NULL,
[WOD_SELL_PRICE] [numeric] (21, 3) NULL,
[WOD_SELL_PRICE_DISC] [numeric] (21, 3) NULL,
[WOD_TOTAL] [numeric] (21, 3) NULL,
[WOD_TOTAL_SELL] [numeric] (21, 3) NULL,
[WOD_TOTAL_SELL_DISC] [numeric] (21, 3) NULL,
[WOD_PPN_PERSEN] [numeric] (7, 2) NULL,
[WOD_PPN] [numeric] (21, 3) NULL,
[WOD_PPNBM_PERSEN] [numeric] (7, 2) NULL,
[WOD_PPNBM] [numeric] (21, 3) NULL,
[WOD_TOTAL_TAX] [numeric] (21, 3) NULL,
[WOD_SELL_TO] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WOD_IS_PROCESS] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__WASTAGE_O__DATE___67FE6514] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[WOD_IGRD_ID] [int] NULL,
[WOD_IGRD_UNT_ID] [int] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[WASTAGE_OBRAL_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__WASTAGE_O__WASTA__422DC1E7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WASTAGE_OBRAL_DETIL] ADD CONSTRAINT [PK__WASTAGE___4812529544160A59] PRIMARY KEY CLUSTERED  ([WASTAGE_OBRAL_DETIL_ID]) ON [PRIMARY]
GO
