CREATE TABLE [dbo].[SUPLIER_MG_TRANSAKSI]
(
[SUPMGT_TGL] [date] NOT NULL,
[SUPMGT_SUB_CODE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUPMGT_AP_ENDING_BALANCE] [float] NOT NULL,
[SUPMGT_CN_BALANCE] [float] NOT NULL,
[SUPMGT_SUB_UNT_ID] [int] NOT NULL,
[SUPMGT_OUTSTANDING_PAYMENT] [float] NOT NULL,
[SUPMGT_LAST_PURCHASE] [date] NOT NULL,
[SUPMGT_PAYMENT] [float] NOT NULL,
[SUPLIER_MG_TRANSAKSI_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SUPLIER_M__SUPLI__3D1EF407] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUPLIER_MG_TRANSAKSI] ADD CONSTRAINT [PK__SUPLIER___125387EA3F073C79] PRIMARY KEY CLUSTERED  ([SUPLIER_MG_TRANSAKSI_ID]) ON [PRIMARY]
GO
