CREATE TABLE [dbo].[SYS$PARAMETER_COMP_TEMPLATE]
(
[PARCT_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PARCT_DEFAULT] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARCT_GROUP] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARCT_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS$PARAMETER_COMP_TEMPLATE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$PARAM__SYS$P__06D7F1EF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$PARAMETER_COMP_TEMPLATE] ADD CONSTRAINT [PK__SYS$PARA__E069DE1308C03A61] PRIMARY KEY CLUSTERED  ([SYS$PARAMETER_COMP_TEMPLATE_ID]) ON [PRIMARY]
GO
