CREATE TABLE [dbo].[AGREEMENT_JADWAL]
(
[AGRJDWL_UNT_ID] [int] NOT NULL,
[AGRJDWL_AGR_ID] [int] NOT NULL,
[AGRJDWL_AGR_UNT_ID] [int] NOT NULL,
[AGRJDWL_INV_TERM_NO] [int] NULL CONSTRAINT [DF__AGREEMENT__AGRJD__286302EC] DEFAULT ((1)),
[AGRJDWL_INV_PAYMENT_NO] [int] NULL CONSTRAINT [DF__AGREEMENT__AGRJD__29572725] DEFAULT ((1)),
[AGRJDWL_INV_DATE] [datetime] NULL CONSTRAINT [DF__AGREEMENT__AGRJD__2A4B4B5E] DEFAULT (getdate()),
[AGRJDWL_INV_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AGRJDWL_INV_DUE_DATE] [datetime] NULL,
[AGRJDWL_INV_TOTAL] [numeric] (21, 3) NULL,
[AGRJDWL_INV_IS_PRINTED] [int] NULL,
[AGRJDWL_INV_IS_POTONGAN] [int] NULL,
[AGRJDWL_STAPRO_ID_INV] [int] NULL,
[AGRJDWL_INV_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGRJDWL_ACCRU_DATE] [datetime] NULL,
[AGRJDWL_ACCRU_NO] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGRJDWL_ACCRU_TOTAL] [int] NULL,
[AGRJDWL_ACCRU_STATUS] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__AGREEMENT__AGRJD__2B3F6F97] DEFAULT ('OPEN'),
[AGRJDWL_ACCRU_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__AGREEMENT__DATE___2C3393D0] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[AGRJDWL_PAJAK_NO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGREEMENT_JADWAL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AGREEMENT__AGREE__1CE72E9F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGREEMENT_JADWAL] ADD CONSTRAINT [PK__AGREEMEN__AD7FE7851ECF7711] PRIMARY KEY CLUSTERED  ([AGREEMENT_JADWAL_ID]) ON [PRIMARY]
GO
