CREATE TABLE [dbo].[GENERAL_LEDGER]
(
[GL_COMP_ID] [int] NOT NULL,
[GL_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GL_REK_COMP_ID] [int] NOT NULL,
[GL_DATE] [datetime] NOT NULL CONSTRAINT [DF__GENERAL_L__GL_DA__32767D0B] DEFAULT (getdate()),
[GL_BEGIN_BAL] [numeric] (21, 3) NULL,
[GL_DEBET] [numeric] (21, 3) NULL,
[GL_CREDIT] [numeric] (21, 3) NULL,
[GL_BAL] [numeric] (21, 3) NULL,
[GL_LAST_BAL] [numeric] (21, 3) NULL,
[GL_RESV_1] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__GENERAL_L__DATE___336AA144] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[GENERAL_LEDGER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__GENERAL_L__GENER__4EE89E87] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GENERAL_LEDGER] ADD CONSTRAINT [PK__GENERAL___4BDFD5D450D0E6F9] PRIMARY KEY CLUSTERED  ([GENERAL_LEDGER_ID]) ON [PRIMARY]
GO
