CREATE TABLE [dbo].[CASH_DROPPING]
(
[CASHDROP_UNT_ID] [int] NOT NULL,
[CASHDROP_USR_ID] [int] NOT NULL,
[CASHDROP_USR_UNT_ID] [int] NOT NULL,
[CASHDROP_BALANCE_ID] [int] NOT NULL,
[CASHDROP_BALANCE_UNT_ID] [int] NOT NULL,
[CASHDROP_TOTAL] [numeric] (21, 3) NULL,
[CASHDROP_DATE] [datetime] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CASH_DROP__DATE___1EA48E88] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CASH_DROPPING_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CASH_DROP__CASH___546C6DB3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASH_DROPPING] ADD CONSTRAINT [PK__CASH_DRO__88AB29DA5654B625] PRIMARY KEY CLUSTERED  ([CASH_DROPPING_ID]) ON [PRIMARY]
GO
