CREATE TABLE [dbo].[TEMP$BARANG_HARGA_JUAL]
(
[TBHJ_ID] [int] NOT NULL,
[TBHJ_DISC_PERSEN] [float] NULL,
[TBHJ_DISC_NOMINAL] [float] NULL,
[TBHJ_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TBHJ_BRG_CODE_UNT_ID] [int] NOT NULL,
[TBHJ_TPHRG_ID] [int] NOT NULL,
[TBHJ_TPHRG_UNT_ID] [int] NOT NULL,
[TBHJ_SELL_PRICE] [float] NULL,
[TEMP$BARANG_HARGA_JUAL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TEMP$BARA__TEMP$__1E305893] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMP$BARANG_HARGA_JUAL] ADD CONSTRAINT [PK__TEMP$BAR__B5E97DC42018A105] PRIMARY KEY CLUSTERED  ([TEMP$BARANG_HARGA_JUAL_ID]) ON [PRIMARY]
GO
