CREATE TABLE [dbo].[DN_RECV_DETIL]
(
[DNRD_UNT_ID] [int] NOT NULL,
[DNRD_DNR_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNRD_DNR_UNT_ID] [int] NOT NULL,
[DNRD_BRGSUP_ID] [int] NOT NULL,
[DNRD_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNRD_PO_UNT_ID] [int] NULL,
[DNRD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__DN_RECV_D__DNRD___6AEFE058] DEFAULT ((0)),
[DNRD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNRD_PRICE] [numeric] (21, 3) NULL,
[DNRD_TOTAL] [numeric] (21, 3) NULL,
[DNRD_TOTAL_DISC] [numeric] (21, 3) NULL,
[DNRD_PPN_PERSEN] [numeric] (7, 2) NULL,
[DNRD_PPN] [numeric] (21, 3) NULL,
[DNRD_PPNBM_PERSEN] [numeric] (7, 2) NULL,
[DNRD_PPNBM] [numeric] (21, 3) NULL,
[DNRD_TOTAL_TAX] [numeric] (21, 3) NULL,
[DNRD_IS_CLAIM_TTF] [int] NULL,
[DNRD_IS_PROCESS] [int] NULL,
[DNRD_IS_OUTSTANDING] [int] NULL,
[DNRD_DO_NO_NEW] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNRD_DO_UNT_ID_NEW] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__DN_RECV_D__DATE___6BE40491] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[DNRD_POD_ID] [int] NULL,
[DNRD_POD_UNT_ID] [int] NULL,
[DNRD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNRD_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[DN_RECV_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__DN_RECV_D__DN_RE__04508AFF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DN_RECV_DETIL] ADD CONSTRAINT [PK__DN_RECV___B9A760120638D371] PRIMARY KEY CLUSTERED  ([DN_RECV_DETIL_ID]) ON [PRIMARY]
GO
