CREATE TABLE [dbo].[TDOSTORE]
(
[DOS_DO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DOS_DOD_ID] [int] NOT NULL,
[DOS_UNT_ID] [int] NOT NULL,
[DOS_QTY_UNT_ID] [int] NOT NULL,
[DOS_QTY] [numeric] (21, 3) NULL,
[TDOSTORE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TDOSTORE__TDOSTO__037C6257] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TDOSTORE] ADD CONSTRAINT [PK__TDOSTORE__20D5200F0564AAC9] PRIMARY KEY CLUSTERED  ([TDOSTORE_ID]) ON [PRIMARY]
GO
