CREATE TABLE [dbo].[TEMP$PL]
(
[REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REK_NAME] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REK_LEVEL] [int] NULL,
[BAL] [numeric] (21, 3) NULL,
[BAL_1] [numeric] (21, 3) NULL,
[BAL_2] [numeric] (21, 3) NULL,
[DIVISION] [int] NULL,
[IS_HEADER] [int] NULL CONSTRAINT [DF__TEMP$PL__IS_HEAD__000AF8CF] DEFAULT ((1)),
[IS_SUB_TOTAL] [int] NULL CONSTRAINT [DF__TEMP$PL__IS_SUB___00FF1D08] DEFAULT ((1)),
[IS_SUMMARY] [int] NULL CONSTRAINT [DF__TEMP$PL__IS_SUMM__01F34141] DEFAULT ((1)),
[TEMP$PL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TEMP$PL__TEMP$PL__7795AE5F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMP$PL] ADD CONSTRAINT [PK__TEMP$PL__2F13BB13797DF6D1] PRIMARY KEY CLUSTERED  ([TEMP$PL_ID]) ON [PRIMARY]
GO
