CREATE TABLE [dbo].[ADS_MASUK]
(
[ADSI_UNT_ID] [int] NOT NULL,
[ADSI_NO] [varchar] (108) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADSI_SUPMG_SUB_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADSI_DATE] [datetime] NULL CONSTRAINT [DF__ADS_MASUK__ADSI___1B0907CE] DEFAULT (getdate()),
[ADSI_NOMINAL] [numeric] (21, 3) NULL,
[ADSI_KDJUR_ID] [int] NULL,
[ADSI_KDJUR_COMP_ID] [int] NULL,
[ADSI_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADSI_REK_COMP_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__ADS_MASUK__DATE___1BFD2C07] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[ADSI_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ADS_MASUK_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ADS_MASUK__ADS_M__538D5813] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADS_MASUK] ADD CONSTRAINT [PK__ADS_MASU__61BC3A605575A085] PRIMARY KEY CLUSTERED  ([ADS_MASUK_ID]) ON [PRIMARY]
GO
