CREATE TABLE [dbo].[STANDAR_JURNAL_DETAIL]
(
[STDJD_COMP_ID] [int] NOT NULL,
[STDJD_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STDJD_REK_COMP_ID] [int] NOT NULL,
[STDJD_TRANSACTION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__STANDAR_J__DATE___1AF3F935] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[STDJD_KDJUR_ID] [int] NULL,
[STDJD_KDJUR_COMP_ID] [int] NULL,
[RUMUS] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STDJD_MULTI_PURPOSE] [int] NULL,
[FLAGRUMUS] [int] NULL,
[TIPE] [int] NULL,
[STANDAR_JURNAL_DETAIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__STANDAR_J__STAND__168449D3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STANDAR_JURNAL_DETAIL] ADD CONSTRAINT [PK__STANDAR___BCA5E240186C9245] PRIMARY KEY CLUSTERED  ([STANDAR_JURNAL_DETAIL_ID]) ON [PRIMARY]
GO
