CREATE TABLE [dbo].[MUTASI_GUDANG]
(
[MUTGUD_UNT_ID] [int] NOT NULL,
[MUTGUD_INV_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__MUTASI_GU__MUTGU__019E3B86] DEFAULT ('MG-'),
[MUTGUD_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MUTGUD_DATE] [datetime] NULL CONSTRAINT [DF__MUTASI_GU__MUTGU__02925FBF] DEFAULT (getdate()),
[MUTGUD_GUD_ID_FROM] [int] NOT NULL,
[MUTGUD_GUD_UNT_ID_FROM] [int] NOT NULL,
[MUTGUD_GUD_ID_TO] [int] NOT NULL,
[MUTGUD_GUD_UNT_ID_TO] [int] NOT NULL,
[MUTGUD_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__MUTASI_GU__DATE___038683F8] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[MUTASI_GUDANG_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__MUTASI_GU__MUTAS__066DDD9B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MUTASI_GUDANG] ADD CONSTRAINT [PK__MUTASI_G__A53DAA4D0856260D] PRIMARY KEY CLUSTERED  ([MUTASI_GUDANG_ID]) ON [PRIMARY]
GO
