CREATE TABLE [dbo].[ELECTRIC_RATE]
(
[ELECTR_UNT_ID] [int] NOT NULL,
[ELECTR_GROUP] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ELECTR_POWER] [numeric] (17, 2) NULL,
[ELECTR_FACTOR] [real] NULL,
[ELECTR_COST_ABODEMEN] [numeric] (21, 3) NULL,
[ELECTR_COST_USE] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__ELECTRIC___DATE___1B9317B3] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ELECTRIC_RATE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ELECTRIC___ELECT__65CC03DF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELECTRIC_RATE] ADD CONSTRAINT [PK__ELECTRIC__A669042767B44C51] PRIMARY KEY CLUSTERED  ([ELECTRIC_RATE_ID]) ON [PRIMARY]
GO
