CREATE TABLE [dbo].[AUT$USER]
(
[USR_UNT_ID] [int] NOT NULL,
[USR_FULLNAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USR_USERNAME] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USR_PASSWD] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USR_STATUS] [int] NULL,
[USR_DESCRIPTION] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAXUBAHPO] [int] NULL,
[AUT$USER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AUT$USER__AUT$US__7A92169B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUT$USER] ADD CONSTRAINT [PK__AUT$USER__010310FD7C7A5F0D] PRIMARY KEY CLUSTERED  ([AUT$USER_ID]) ON [PRIMARY]
GO
