CREATE TABLE [dbo].[SO_BARANG_BLACKLIST]
(
[SOBB_UNT_ID] [int] NOT NULL,
[SOBB_BRGSUP_ID] [int] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SO_BARANG__DATE___0F824689] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SO_BARANG_BLACKLIST_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SO_BARANG__SO_BA__30CE2BBB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_BARANG_BLACKLIST] ADD CONSTRAINT [PK__SO_BARAN__DA2B7DD132B6742D] PRIMARY KEY CLUSTERED  ([SO_BARANG_BLACKLIST_ID]) ON [PRIMARY]
GO
