CREATE TABLE [dbo].[TQUOTATIONHARGABELIITEM]
(
[HEADERUNIT_ID] [int] NOT NULL,
[BARANG_KODE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BARANGUNIT_ID] [int] NOT NULL,
[DISC1] [float] NOT NULL,
[DISC2] [int] NOT NULL,
[DISC3] [float] NOT NULL,
[HARGA] [float] NOT NULL,
[UOMUNIT_ID] [int] NOT NULL,
[NEWUOM_CODE] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NEWUNIT_ID] [int] NULL,
[TQUOTATIONHARGABELIITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TQUOTATIO__TQUOT__29971E47] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TQUOTATIONHARGABELIITEM] ADD CONSTRAINT [PK__TQUOTATI__A44D34DD2B7F66B9] PRIMARY KEY CLUSTERED  ([TQUOTATIONHARGABELIITEM_ID]) ON [PRIMARY]
GO
