CREATE TABLE [dbo].[RECEIPT]
(
[RCPT_UNT_ID] [int] NOT NULL,
[RCPT_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RCPT_DATE] [datetime] NULL CONSTRAINT [DF__RECEIPT__RCPT_DA__78D3EB5B] DEFAULT (getdate()),
[RCPT_TPBYR_ID] [int] NULL,
[RCPT_KDJUR_ID] [int] NULL,
[RCPT_KDJUR_COMP_ID] [int] NULL,
[RCPT_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RCPT_REK_COMP_ID] [int] NOT NULL,
[RCPT_DUE_DATE] [datetime] NULL,
[RCPT_REF] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCPT_RECEIPT_TO] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCPT_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCPT_STAPRO_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__RECEIPT__DATE_CR__79C80F94] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[RECEIPT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__RECEIPT__RECEIPT__41C3AD93] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECEIPT] ADD CONSTRAINT [PK__RECEIPT__D1F6B97E43ABF605] PRIMARY KEY CLUSTERED  ([RECEIPT_ID]) ON [PRIMARY]
GO
