CREATE TABLE [dbo].[TGRBONUSITEM]
(
[NEWUNIT_ID] [int] NOT NULL,
[GR_NO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GRUNIT_ID] [int] NOT NULL,
[NEWBARANG_CODE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BARANGUNIT_ID] [int] NOT NULL,
[ISBONUSFORBONUS] [int] NOT NULL,
[POBONUSITEM_ID] [int] NULL,
[POBONUSITEMUNIT_ID] [int] NULL,
[NEWUOM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UOMUNIT_ID] [int] NOT NULL,
[QTY] [float] NOT NULL,
[TGRBONUSITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TGRBONUSI__TGRBO__7211DF33] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TGRBONUSITEM] ADD CONSTRAINT [PK__TGRBONUS__583199C973FA27A5] PRIMARY KEY CLUSTERED  ([TGRBONUSITEM_ID]) ON [PRIMARY]
GO
