CREATE TABLE [dbo].[SHIPMENT_TRANSPORT]
(
[TRANS_CODE] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANS_UNT_ID] [int] NOT NULL,
[TRANS_AGENT_CODE] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANS_AGENT_UNT_ID] [int] NULL,
[TRANS_NAME] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANS_CAR_NO] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANS_DRIVER] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANS_DESCRIPTION] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SHIPMENT___DATE___0ABD916C] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SHIPMENT_TRANSPORT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SHIPMENT___SHIPM__4E7E8A33] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SHIPMENT_TRANSPORT] ADD CONSTRAINT [PK__SHIPMENT__E7B5116B5066D2A5] PRIMARY KEY CLUSTERED  ([SHIPMENT_TRANSPORT_ID]) ON [PRIMARY]
GO
