CREATE TABLE [dbo].[COMPANY]
(
[COMP_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMP_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__COMPANY__DATE_CR__4D5F7D71] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[COMPANY_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__COMPANY__COMPANY__1F04813B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPANY] ADD CONSTRAINT [PK__COMPANY__73B8DCFF20ECC9AD] PRIMARY KEY CLUSTERED  ([COMPANY_ID]) ON [PRIMARY]
GO
