CREATE TABLE [dbo].[BARANG_HARGA_JUAL]
(
[BARANG_HARGA_JUAL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__BARANG_HA__BARAN__72F0F4D3] DEFAULT (newid()),
[BARANG_ID] [uniqueidentifier] NOT NULL,
[REF$SATUAN_ID] [uniqueidentifier] NOT NULL,
[REF$TIPE_HARGA_ID] [uniqueidentifier] NOT NULL,
[BHJ_SELL_PRICE] [numeric] (21, 3) NOT NULL CONSTRAINT [DF_BARANG_HARGA_JUAL_BHJ_SELL_PRICE] DEFAULT ((0)),
[BHJ_DISC_PERSEN] [numeric] (7, 2) NOT NULL CONSTRAINT [DF_BARANG_HARGA_JUAL_BHJ_DISC_PERSEN] DEFAULT ((0)),
[BHJ_DISC_NOMINAL] [numeric] (21, 3) NOT NULL CONSTRAINT [DF_BARANG_HARGA_JUAL_BHJ_DISC_NOMINAL] DEFAULT ((0)),
[BHJ_SELL_PRICE_DISC] [numeric] (21, 3) NOT NULL CONSTRAINT [DF_BARANG_HARGA_JUAL_BHJ_SELL_PRICE_DISC] DEFAULT ((0)),
[BHJ_SELL_PRICE_CORET] [numeric] (21, 3) NOT NULL CONSTRAINT [DF_BARANG_HARGA_JUAL_BHJ_SELL_PRICE_CORET] DEFAULT ((0)),
[BHJ_MARK_UP] [numeric] (7, 2) NOT NULL CONSTRAINT [DF_BARANG_HARGA_JUAL_BHJ_MARK_UP] DEFAULT ((0)),
[BHJ_IS_LIMIT_QTY] [int] NULL,
[BHJ_IS_QTY_SUBSIDY] [int] NULL,
[BHJ_LIMIT_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_HA__BHJ_L__6B24EA82] DEFAULT ((0)),
[BHJ_LIMIT_QTY_PRICE] [numeric] (21, 3) NULL,
[BHJ_QTY_SUBSIDY] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_HA__BHJ_Q__6C190EBB] DEFAULT ((9)),
[BHJ_QTY_SUBSIDY_PRICE] [numeric] (21, 3) NULL,
[BHJ_CONV_VALUE] [numeric] (13, 5) NOT NULL CONSTRAINT [DF__BARANG_HA__BHJ_C__6D0D32F4] DEFAULT ((1)),
[BHJ_REMARK] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BHJ_ADSO_ID] [int] NULL,
[BHJ_ADSO_UNT_ID] [int] NULL,
[BHJ_IS_MAILER] [int] NULL,
[BHJ_MAX_QTY_DISC] [float] NULL,
[BHJ_MAILER_END_DATE] [datetime] NULL,
[BHJ_LAST_SELL_PRICE] [float] NULL,
[BHJ_LAST_DISC] [float] NULL,
[BHJ_LAST_DISC_PERSEN] [float] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__BARANG_HA__DATE___6E01572D] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BARANG_HARGA_JUAL] ADD CONSTRAINT [PK_BARANG_HARGA_JUAL] PRIMARY KEY CLUSTERED  ([BARANG_ID], [REF$SATUAN_ID]) ON [PRIMARY]
GO
