CREATE TABLE [dbo].[TPURCHASESUGESTIONITEM]
(
[PS_ID] [int] NOT NULL,
[PSI_ID] [int] NOT NULL,
[UNT_ID] [int] NOT NULL,
[BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PSI_HARGAJUAL] [float] NOT NULL,
[PSI_DISCOUNT] [float] NOT NULL,
[PSI_KETERANGAN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSI_HARGABELI] [float] NULL CONSTRAINT [DF__TPURCHASE__PSI_H__17E28260] DEFAULT ((0.0)),
[PSI_DISC_B_01] [float] NULL CONSTRAINT [DF__TPURCHASE__PSI_D__18D6A699] DEFAULT ((0.0)),
[PSI_DISC_B_02] [float] NULL CONSTRAINT [DF__TPURCHASE__PSI_D__19CACAD2] DEFAULT ((0.0)),
[PSI_DISC_B_03] [float] NULL CONSTRAINT [DF__TPURCHASE__PSI_D__1ABEEF0B] DEFAULT ((0.0)),
[PSI_PPN] [float] NULL CONSTRAINT [DF__TPURCHASE__PSI_P__1BB31344] DEFAULT ((0.0)),
[TPURCHASESUGESTIONITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TPURCHASE__TPURC__0015E5C7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPURCHASESUGESTIONITEM] ADD CONSTRAINT [PK__TPURCHAS__9D25EFD901FE2E39] PRIMARY KEY CLUSTERED  ([TPURCHASESUGESTIONITEM_ID]) ON [PRIMARY]
GO
