CREATE TABLE [dbo].[JURNAL_CLOSE_YEAR]
(
[JURCY_UNT_ID] [int] NOT NULL,
[JURCY_FISCAL_YEAR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[JURCY_PERIOD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[JURCY_DATE] [datetime] NOT NULL CONSTRAINT [DF__JURNAL_CL__JURCY__6501FCD8] DEFAULT (getdate()),
[JURCY_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[JURCY_REF_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JURCY_DEBET] [numeric] (21, 3) NULL,
[JURCY_CREDIT] [numeric] (21, 3) NULL,
[JURCY_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JURCY_IS_POSTED] [int] NULL,
[JURCY_POSTED_DATE] [datetime] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__JURNAL_CL__DATE___65F62111] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[JURNAL_CLOSE_YEAR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__JURNAL_CL__JURNA__2121D3D7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JURNAL_CLOSE_YEAR] ADD CONSTRAINT [PK__JURNAL_C__E0F58FE9230A1C49] PRIMARY KEY CLUSTERED  ([JURNAL_CLOSE_YEAR_ID]) ON [PRIMARY]
GO
