CREATE TABLE [dbo].[SUPPLIER_UNIT_LEAD_TIME]
(
[SULT_UNT_ID] [int] NOT NULL,
[SULT_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SULT_LEAD_TIME] [int] NOT NULL,
[OP_CREATE] [int] NOT NULL,
[DATE_CREATE] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SUPPLIER_UNIT_LEAD_TIME_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SUPPLIER___SUPPL__4C613797] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUPPLIER_UNIT_LEAD_TIME] ADD CONSTRAINT [PK__SUPPLIER__C43F1B2B4E498009] PRIMARY KEY CLUSTERED  ([SUPPLIER_UNIT_LEAD_TIME_ID]) ON [PRIMARY]
GO
