CREATE TABLE [dbo].[RAFAKSI_DETIL]
(
[RAFD_RAF_ID] [int] NOT NULL,
[RAFD_RAF_UNT_ID] [int] NULL,
[RAFD_ID] [int] NOT NULL,
[RAFD_UNT_ID] [int] NOT NULL,
[RAFD_BRG_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RAFD_SAT_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__RAFAKSI_D__DATE___75035A77] DEFAULT (getdate()),
[RAFD_QTY_STOCK] [float] NULL,
[RAFD_QTY_RAFAKSI] [float] NULL,
[RAFD_NILAI_RAFAKSI] [float] NULL,
[RAFD_AKHIR_PERIODE] [int] NULL CONSTRAINT [DF__RAFAKSI_D__RAFD___75F77EB0] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[RAFAKSI_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__RAFAKSI_D__RAFAK__0B1D841F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RAFAKSI_DETIL] ADD CONSTRAINT [PK__RAFAKSI___BFF6ADDB0D05CC91] PRIMARY KEY CLUSTERED  ([RAFAKSI_DETIL_ID]) ON [PRIMARY]
GO
