CREATE TABLE [dbo].[REF$TIPE_PEMBAYARAN]
(
[TPBYR_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TPBYR_NAME] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$TIPE___DATE___4EA8A765] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$TIPE_PEMBAYARAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_REF$TIPE_PEMBAYARAN_REF$TIPE_PEMBAYARAN_ID] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_PEMBAYARAN] ADD CONSTRAINT [PK_REF$TIPE_PEMBAYARAN] PRIMARY KEY CLUSTERED  ([REF$TIPE_PEMBAYARAN_ID]) ON [PRIMARY]
GO
