CREATE TABLE [dbo].[REF$TIPE_PO]
(
[TPPO_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TPPO_NAME] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$TIPE___DATE___546180BB] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TTPO_AP_STATUS] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__REF$TIPE___TTPO___5555A4F4] DEFAULT ('PO'),
[TTPO_TPBRG_ID] [int] NULL,
[REF$TIPE_PO_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$TIPE___REF$T__5AC46587] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_PO] ADD CONSTRAINT [PK__REF$TIPE__B8C07F905CACADF9] PRIMARY KEY CLUSTERED  ([REF$TIPE_PO_ID]) ON [PRIMARY]
GO
