CREATE TABLE [dbo].[BARCODE_REQUEST]
(
[BAR_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BAR_UNT_ID] [int] NOT NULL,
[BAR_DATE] [datetime] NULL,
[BAR_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BAR_TOTAL_PRICE] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__BARCODE_R__DATE___0F624AF8] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ISJOURNALIZED] [int] NULL,
[BARCODE_REQUEST_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__BARCODE_R__BARCO__6932806F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BARCODE_REQUEST] ADD CONSTRAINT [PK__BARCODE___FC58198A6B1AC8E1] PRIMARY KEY CLUSTERED  ([BARCODE_REQUEST_ID]) ON [PRIMARY]
GO
