CREATE TABLE [dbo].[GUDANG]
(
[GUD_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GUD_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GUD_ADDRESS] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUD_TELP] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUD_FAX] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUD_CITY] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUD_POST_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUD_CONTACT_PERSON] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__GUDANG__DATE_CRE__41B8C09B] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[GUDANG_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__GUDANG__GUDANG_I__3805392F] DEFAULT (newid()),
[AUT$UNIT_ID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GUDANG] ADD CONSTRAINT [PK__GUDANG__B29AD4F739ED81A1] PRIMARY KEY CLUSTERED  ([GUDANG_ID]) ON [PRIMARY]
GO
