CREATE TABLE [dbo].[TRANS_BARANG_TURUNAN_DETIL]
(
[TBTD_UNT_ID] [int] NOT NULL,
[TBTD_TBRGTUR_ID] [int] NOT NULL,
[TBTD_TBRGTUR_UNT_ID] [int] NOT NULL,
[TBTD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TBTD_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TBTD_PO_UNT_ID] [int] NULL,
[TBTD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__TRANS_BAR__TBTD___3D14070F] DEFAULT ((0)),
[TBTD_QTY_WASTAGE] [numeric] (18, 3) NULL,
[TBTD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TBTD_PURCH_PRICE] [numeric] (21, 3) NULL,
[TBTD_IS_PECAHAN] [int] NULL,
[TBTD_FORMULA_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TRANS_BAR__DATE___3E082B48] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TRANS_BARANG_TURUNAN_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANS_BAR__TRANS__68536ACF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANS_BARANG_TURUNAN_DETIL] ADD CONSTRAINT [PK__TRANS_BA__36D227E96A3BB341] PRIMARY KEY CLUSTERED  ([TRANS_BARANG_TURUNAN_DETIL_ID]) ON [PRIMARY]
GO
