CREATE TABLE [dbo].[FINAL_PAYMENT]
(
[FINPAYMENT_UNT_ID] [int] NOT NULL,
[FINPAYMENT_BALANCE_ID] [int] NOT NULL,
[FINPAYMENT_BALANCE_UNT_ID] [int] NOT NULL,
[FINPAYMENT_TOTAL] [numeric] (21, 3) NULL,
[FINPAYMENT_GRAND_TOTAL] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__FINAL_PAY__DATE___2057CCD0] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[FINAL_PAYMENT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__FINAL_PAY__FINAL__5E2AE217] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FINAL_PAYMENT] ADD CONSTRAINT [PK__FINAL_PA__A99DB71560132A89] PRIMARY KEY CLUSTERED  ([FINAL_PAYMENT_ID]) ON [PRIMARY]
GO
