CREATE TABLE [dbo].[AUT$MENU]
(
[MENU_UNT_ID] [int] NOT NULL,
[MENU_GRO_ID] [int] NOT NULL,
[MENU_GRO_UNT_ID] [int] NOT NULL,
[AUT$MENU_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AUT$MENU__AUT$ME__0603C947] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUT$MENU] ADD CONSTRAINT [PK__AUT$MENU__534D978A07EC11B9] PRIMARY KEY CLUSTERED  ([AUT$MENU_ID]) ON [PRIMARY]
GO
