CREATE TABLE [dbo].[RECEIPT_DETIL]
(
[RCPTD_UNT_ID] [int] NOT NULL,
[RCPTD_RCPT_ID] [int] NOT NULL,
[RCPTD_RCPT_UNT_ID] [int] NOT NULL,
[RCPTD_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RCPTD_REK_COMP_ID] [int] NOT NULL,
[RCPTD_TOTAL] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__RECEIPT_D__DATE___7BB05806] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[RECEIPT_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__RECEIPT_D__RECEI__3DF31CAF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECEIPT_DETIL] ADD CONSTRAINT [PK__RECEIPT___DEEFF9DC3FDB6521] PRIMARY KEY CLUSTERED  ([RECEIPT_DETIL_ID]) ON [PRIMARY]
GO
