CREATE TABLE [dbo].[SYS$IMPORT_HISTORY_ERROR]
(
[IMHE_UNT_ID] [int] NOT NULL,
[IMHE_IMP_SESSION_ID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IMHE_IMP_UNT_ID] [int] NOT NULL,
[IMHE_FILE_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IMHE_RECORD_NO] [int] NOT NULL,
[IMHE_SQL] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMHE_ERROR_MSG] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMHE_ALLOW_SKIP] [int] NOT NULL CONSTRAINT [DF__SYS$IMPOR__IMHE___5CC1BC92] DEFAULT ((0)),
[SYS$IMPORT_HISTORY_ERROR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$IMPOR__SYS$I__1FD8A9E3] DEFAULT (newid())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$IMPORT_HISTORY_ERROR] ADD CONSTRAINT [PK__SYS$IMPO__A67C403D21C0F255] PRIMARY KEY CLUSTERED  ([SYS$IMPORT_HISTORY_ERROR_ID]) ON [PRIMARY]
GO
