CREATE TABLE [dbo].[REGION]
(
[RGN_ID] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RGN_NAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_CREATE] [datetime] NULL,
[OP_CREATE] [int] NULL,
[OPC_UNIT] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[OPM_UNIT] [int] NULL,
[RGN_DESCRIPTION] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REGION_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REGION__REGION_I__3ED2324F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REGION] ADD CONSTRAINT [PK__REGION__80772D6240BA7AC1] PRIMARY KEY CLUSTERED  ([REGION_ID]) ON [PRIMARY]
GO
