CREATE TABLE [dbo].[RETUR_ASSGROS]
(
[RETASS_UNT_ID] [int] NULL,
[RETASS_NOBUKTI] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETASS_STATUSFLAG] [int] NULL,
[RETASS_KETERANGAN] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETASS_TGLBUKTI] [datetime] NULL,
[RETASS_TRD_CODE] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETASS_TRD_UNT_ID] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[RETASS_IS_JURNAL] [int] NULL,
[RETUR_ASSGROS_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__RETUR_ASS__RETUR__0EE3280B] DEFAULT (newid())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RETUR_ASSGROS] ADD CONSTRAINT [PK__RETUR_AS__8510D9E210CB707D] PRIMARY KEY CLUSTERED  ([RETUR_ASSGROS_ID]) ON [PRIMARY]
GO
