CREATE TABLE [dbo].[REKENING]
(
[REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REK_COMP_ID] [int] NULL,
[REK_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REK_LEVEL] [int] NULL CONSTRAINT [DF__REKENING__REK_LE__5FD33367] DEFAULT ((0)),
[REK_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REK_PARENT_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REK_PARENT_COMP_ID] [int] NULL,
[REK_IS_DEBET] [int] NULL,
[REK_GROREK_ID] [int] NULL,
[REK_GROREK_COMP_ID] [int] NULL,
[REK_IS_LEAF] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REKENING__DATE_C__60C757A0] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[REK_IS_GROUP] [int] NULL CONSTRAINT [DF__REKENING__REK_IS__61BB7BD9] DEFAULT ((0)),
[REKENING_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REKENING__ID__2042BE37] DEFAULT (newid()),
[REF$GRUP_REKENING_ID] [uniqueidentifier] NULL,
[REKENING_PARENT_ID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REKENING] ADD CONSTRAINT [PK__REKENING__3214EC27222B06A9] PRIMARY KEY CLUSTERED  ([REKENING_ID]) ON [PRIMARY]
GO
