CREATE TABLE [dbo].[RETUR_ASSGROS_DETIL]
(
[RETASSD_ID] [int] NULL,
[RETASSD_UNT_ID] [int] NULL,
[RETASSD_BRG_CODE] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETASSD_BRG_UNT_ID] [int] NULL,
[RETASSD_SAT_CODE] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETASSD_SAT_UNT_ID] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[RETASSD_DOASD_ID] [int] NULL,
[RETASSD_DOASD_UNT_ID] [int] NULL,
[RETASSD_RETASS_ID] [int] NULL,
[RETASSD_RETASS_UNT_ID] [int] NULL,
[RETASSD_QTY] [float] NULL,
[RETASSD_DOASD_SELL_PRICE_DISC] [float] NULL,
[RETASSD_DOASD_PPN] [float] NULL,
[RETASSD_DOASD_PPNBM] [float] NULL,
[RETUR_ASSGROS_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__RETUR_ASS__RETUR__3B6BB5BF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RETUR_ASSGROS_DETIL] ADD CONSTRAINT [PK__RETUR_AS__6CC981723D53FE31] PRIMARY KEY CLUSTERED  ([RETUR_ASSGROS_DETIL_ID]) ON [PRIMARY]
GO
