CREATE TABLE [dbo].[OPEN_PERIODE]
(
[OPPER_COMP_ID] [int] NOT NULL,
[OPPER_DATE] [datetime] NULL CONSTRAINT [DF__OPEN_PERI__OPPER__0D0FEE32] DEFAULT (getdate()),
[OPPER_FISCAL_YEAR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__OPEN_PERI__DATE___0E04126B] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[OPEN_PERIODE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__OPEN_PERI__OPEN___772B9A0B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OPEN_PERIODE] ADD CONSTRAINT [PK__OPEN_PER__10EA18847913E27D] PRIMARY KEY CLUSTERED  ([OPEN_PERIODE_ID]) ON [PRIMARY]
GO
