CREATE TABLE [dbo].[TPSSTORE]
(
[PS_ID] [int] NOT NULL,
[PSI_ID] [int] NOT NULL,
[PSS_UNT_ID] [int] NOT NULL,
[UNT_ID] [int] NOT NULL,
[PSS_QTY] [float] NOT NULL,
[TPSSTORE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TPSSTORE__TPSSTO__7874C3FF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPSSTORE] ADD CONSTRAINT [PK__TPSSTORE__CBFF33C47A5D0C71] PRIMARY KEY CLUSTERED  ([TPSSTORE_ID]) ON [PRIMARY]
GO
