CREATE TABLE [dbo].[PAYMENT_CLAIM_TRANSFER]
(
[PAYCT_COMP_ID] [int] NOT NULL,
[PAYCT_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAYCT_REK_COMP_ID] [int] NOT NULL,
[PAYCT_GIRO_NUMBER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYCT_DUE_DATE] [date] NULL,
[PAYCT_TRANSFER_DATE] [date] NULL,
[PAYCT_CLOSE_DATE] [date] NULL,
[PAYCT_STAPRO_ID] [int] NULL,
[PAYCT_TRANSFER_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYCT_CLM_ID] [int] NOT NULL,
[PAYCT_CLM_UNT_ID] [int] NOT NULL,
[PAYCT_AMOUNT] [numeric] (21, 3) NULL,
[PAYCT_AMOUNT_CLEAN] [numeric] (21, 3) NULL,
[PAYCT_AMOUNT_CLAIM] [numeric] (21, 3) NULL,
[PAYCT_AMOUNT_POT] [numeric] (21, 3) NULL,
[PAYCT_TRANSFER_COST] [numeric] (21, 3) NULL,
[PAYCT_CLMCONT_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYCT_CLMCONT_UNT_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__PAYMENT_C__DATE___1B5E0D89] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[PAYCT_NO_VOUCHER_JURNAL] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYMENT_CLAIM_TRANSFER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PAYMENT_C__PAYME__6BB9E75F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYMENT_CLAIM_TRANSFER] ADD CONSTRAINT [PK__PAYMENT___B47C2E776DA22FD1] PRIMARY KEY CLUSTERED  ([PAYMENT_CLAIM_TRANSFER_ID]) ON [PRIMARY]
GO
