CREATE TABLE [dbo].[REF$GRUP_REKENING]
(
[GROREK_ID] [int] NOT NULL,
[GROREK_COMP_ID] [int] NOT NULL,
[GROREK_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROREK_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$GRUP___DATE___0BE6BFCF] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[REF$GRUP_REKENING_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$GRUP___REF$G__66D536B1] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$GRUP_REKENING] ADD CONSTRAINT [PK__REF$GRUP__308DA3FD68BD7F23] PRIMARY KEY CLUSTERED  ([REF$GRUP_REKENING_ID]) ON [PRIMARY]
GO
