CREATE TABLE [dbo].[WASTAGE_OBRAL]
(
[WSTOB_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WSTOB_UNT_ID] [int] NOT NULL,
[WSTOB_INV_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__WASTAGE_O__WSTOB__6339AFF7] DEFAULT ('RET-'),
[WSTOB_DATE] [datetime] NULL CONSTRAINT [DF__WASTAGE_O__WSTOB__642DD430] DEFAULT (getdate()),
[WSTOB_TOTAL] [numeric] (21, 3) NULL,
[WSTOB_TOTAL_SELL] [numeric] (21, 3) NULL,
[WSTOB_TOTAL_DISC] [numeric] (21, 3) NULL,
[WSTOB_PPN] [numeric] (21, 3) NULL,
[WSTOB_PPNBM] [numeric] (21, 3) NULL,
[WSTOB_TOTAL_TAX] [numeric] (21, 3) NULL,
[WSTOB_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WSTOB_SELL_TO] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WSTOB_IS_JOURNAL] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__WASTAGE_O__DATE___6521F869] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[WASTAGE_OBRAL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__WASTAGE_O__WASTA__4A43E4FB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WASTAGE_OBRAL] ADD CONSTRAINT [PK__WASTAGE___4300CD254C2C2D6D] PRIMARY KEY CLUSTERED  ([WASTAGE_OBRAL_ID]) ON [PRIMARY]
GO
