CREATE TABLE [dbo].[REF$MERCHANDISE]
(
[MERCHAN_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MERCHAN_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$MERCH__DATE___21D600EE] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[MERCHAN_TYPE] [int] NULL,
[MERCHAN_PJK_ID] [int] NULL,
[MERCHAN_HO_AUTHORIZE] [int] NOT NULL CONSTRAINT [DF__REF$MERCH__MERCH__22CA2527] DEFAULT ((0)),
[REF$MERCHANDISE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$MERCH__REF$M__16F94B1F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$MERCHANDISE] ADD CONSTRAINT [PK__REF$MERC__0970736318E19391] PRIMARY KEY CLUSTERED  ([REF$MERCHANDISE_ID]) ON [PRIMARY]
GO
