CREATE TABLE [dbo].[TEMP$RUNNING_PL]
(
[COMP_ID] [int] NULL,
[UID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_PLUS] [int] NULL,
[CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEMP$RUNNING_PL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TEMP$RUNN__TEMP$__33CA93F7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMP$RUNNING_PL] ADD CONSTRAINT [PK__TEMP$RUN__88F0A75835B2DC69] PRIMARY KEY CLUSTERED  ([TEMP$RUNNING_PL_ID]) ON [PRIMARY]
GO
