CREATE TABLE [dbo].[TRADER_PLAFON]
(
[TRDP_TRD_ID] [int] NOT NULL,
[TRDP_TRD_UNT_ID] [int] NOT NULL,
[TRDP_TRD_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRDP_DATE] [datetime] NULL CONSTRAINT [DF__TRADER_PL__TRDP___226010D3] DEFAULT (getdate()),
[TRDP_NILAIEX] [numeric] (21, 3) NULL,
[TRDP_NILAIIN] [numeric] (21, 3) NULL,
[TRDP_PLAFON] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TRADER_PL__DATE___2354350C] DEFAULT (getdate()),
[TRADER_PLAFON_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRADER_PL__TRADE__0B129727] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRADER_PLAFON] ADD CONSTRAINT [PK__TRADER_P__09D6555C0CFADF99] PRIMARY KEY CLUSTERED  ([TRADER_PLAFON_ID]) ON [PRIMARY]
GO
