CREATE TABLE [dbo].[BARANG_TRANSAKSI]
(
[BRGT_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BRGT_COGS] [numeric] (21, 3) NULL,
[BRGT_LAST_COST] [numeric] (21, 3) NULL,
[BRGT_STOCK_MIN] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___7D439ABD] DEFAULT ((0)),
[BRGT_STOCK_MAX] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___7E37BEF6] DEFAULT ((0)),
[BRGT_STOCK] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___7F2BE32F] DEFAULT ((0)),
[BRGT_STOCK_MIN_DISP] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___00200768] DEFAULT ((0)),
[BRGT_STOCK_MAX_DISP] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___01142BA1] DEFAULT ((0)),
[BRGT_STOCK_DISP] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___02084FDA] DEFAULT ((0)),
[BRGT_STOCK_IN_ORDER] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___02FC7413] DEFAULT ((0)),
[BRGT_SALES_PER_DAY] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___03F0984C] DEFAULT ((0)),
[BRGT_COMMON_STOCK] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___04E4BC85] DEFAULT ((0)),
[BRGT_COMMON_ALLOC] [numeric] (7, 2) NULL CONSTRAINT [DF__BARANG_TR__BRGT___05D8E0BE] DEFAULT ((0)),
[BRGT_ASSGROS_STOCK] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___06CD04F7] DEFAULT ((0)),
[BRGT_ASSGROS_ALLOC] [numeric] (7, 2) NULL CONSTRAINT [DF__BARANG_TR__BRGT___07C12930] DEFAULT ((0)),
[BRGT_TRADER_STOCK] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_TR__BRGT___08B54D69] DEFAULT ((0)),
[BRGT_TRADER_ALLOC] [numeric] (7, 2) NULL CONSTRAINT [DF__BARANG_TR__BRGT___09A971A2] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__BARANG_TR__DATE___0A9D95DB] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[BARANG_TRANSAKSI_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__BARANG_TR__BARAN__2D729C23] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BARANG_TRANSAKSI] ADD CONSTRAINT [PK__BARANG_T__5B97532C2F5AE495] PRIMARY KEY CLUSTERED  ([BARANG_TRANSAKSI_ID]) ON [PRIMARY]
GO
