CREATE TABLE [dbo].[GENERAL_LEDGER_FROM]
(
[GLF_COMP_ID] [int] NOT NULL,
[GLF_GL_ID] [int] NULL,
[GLF_GL_COMP_ID] [int] NULL,
[GLF_JURD_ID] [int] NOT NULL,
[GLF_JURD_UNT_ID] [int] NOT NULL,
[GLF_DEBET] [numeric] (21, 3) NULL,
[GLF_CREDIT] [numeric] (21, 3) NULL,
[GLF_IS_CLOSE_YEAR] [int] NULL,
[GLF_GLCY_ID] [int] NULL,
[GLF_GLCY_COMP_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__GENERAL_L__DATE___382F5661] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[GENERAL_LEDGER_FROM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__GENERAL_L__GENER__47477CBF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GENERAL_LEDGER_FROM] ADD CONSTRAINT [PK__GENERAL___7C08D5DA492FC531] PRIMARY KEY CLUSTERED  ([GENERAL_LEDGER_FROM_ID]) ON [PRIMARY]
GO
