CREATE TABLE [dbo].[AMORTISASI]
(
[AMOR_COMP_ID] [int] NOT NULL,
[AMOR_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AMOR_REK_COMP_ID] [int] NOT NULL,
[AMOR_REK_CODE_EXP] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AMOR_REK_EXP_COMP_ID] [int] NOT NULL,
[AMOR_BEGIN_PER] [datetime] NULL,
[AMOR_COST] [numeric] (21, 3) NULL,
[AMOR_AGE] [int] NULL CONSTRAINT [DF__AMORTISAS__AMOR___31EC6D26] DEFAULT ((1)),
[AMOR_PROSEN] [numeric] (7, 2) NULL,
[AMOR_PER_YEAR] [numeric] (21, 3) NULL,
[AMOR_TOTAL] [numeric] (21, 3) NULL,
[AMOR_REMAIN_AGE] [int] NULL CONSTRAINT [DF__AMORTISAS__AMOR___32E0915F] DEFAULT ((1)),
[AMOR_BOOK_VALUE] [numeric] (21, 3) NULL,
[AMOR_CURR_PROC] [datetime] NULL CONSTRAINT [DF__AMORTISAS__AMOR___33D4B598] DEFAULT (getdate()),
[AMOR_STATUS] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__AMORTISAS__DATE___34C8D9D1] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[AMORTISASI_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AMORTISAS__AMORT__15460CD7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AMORTISASI] ADD CONSTRAINT [PK__AMORTISA__85F9B6AF172E5549] PRIMARY KEY CLUSTERED  ([AMORTISASI_ID]) ON [PRIMARY]
GO
