CREATE TABLE [dbo].[VOUCHER_DETIL]
(
[VCRD_UNT_ID] [int] NOT NULL,
[VCRD_VCR_ID] [int] NOT NULL,
[VCRD_VCR_UNT_ID] [int] NOT NULL,
[VCRD_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VCRD_NOMINAL] [numeric] (21, 3) NULL,
[VCRD_STATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__VOUCHER_D__VCRD___5D80D6A1] DEFAULT ('OPEN'),
[VCRD_POS_TRANS_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__VOUCHER_D__DATE___5E74FADA] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[VOUCHER_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__VOUCHER_D__VOUCH__49CEE3AF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHER_DETIL] ADD CONSTRAINT [PK__VOUCHER___D13208304BB72C21] PRIMARY KEY CLUSTERED  ([VOUCHER_DETIL_ID]) ON [PRIMARY]
GO
