CREATE TABLE [dbo].[TRANSFER]
(
[TRFER_COMP_ID] [int] NOT NULL,
[TRFER_TYPE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRFER_KDJUR_ID] [int] NULL,
[TRFER_KDJUR_COMP_ID] [int] NULL,
[TRFER_VOUCHER_NO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRFER_DATE] [datetime] NULL CONSTRAINT [DF__TRANSFER__TRFER___36670980] DEFAULT (getdate()),
[TRFER_REF_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRFER_EFECTIVE_DATE] [datetime] NULL,
[TRFER_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRFER_REK_CODE_D] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRFER_REK_COMP_ID_D] [int] NOT NULL,
[TRFER_REK_CODE_C] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRFER_REK_COMP_ID_C] [int] NOT NULL,
[TRFER_AMOUNT] [numeric] (21, 3) NULL,
[TRFER_STAPRO_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TRANSFER__DATE_C__375B2DB9] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[TRANSFER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANSFER__TRANSF__5540965B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSFER] ADD CONSTRAINT [PK__TRANSFER__627DD8AD5728DECD] PRIMARY KEY CLUSTERED  ([TRANSFER_ID]) ON [PRIMARY]
GO
