CREATE TABLE [dbo].[TSTOREIMPORT]
(
[NOBUKTI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TANGGAL] [datetime] NOT NULL,
[UNITID] [int] NOT NULL,
[URUTAN] [int] NOT NULL,
[UNITSRC] [int] NULL,
[TSTOREIMPORT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TSTOREIMP__TSTOR__21F5FC7F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TSTOREIMPORT] ADD CONSTRAINT [PK__TSTOREIM__7DD5785223DE44F1] PRIMARY KEY CLUSTERED  ([TSTOREIMPORT_ID]) ON [PRIMARY]
GO
