CREATE TABLE [dbo].[TPOSTORE]
(
[PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[POD_ID] [int] NOT NULL,
[POSTORE_UNT_ID] [int] NOT NULL,
[UNT_ID] [int] NOT NULL,
[POSTORE_QTYORDER] [numeric] (21, 3) NULL,
[POSTORE_SOD_ID] [int] NULL,
[TPOSTORE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TPOSTORE__TPOSTO__74A4331B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPOSTORE] ADD CONSTRAINT [PK__TPOSTORE__CACF0AB2768C7B8D] PRIMARY KEY CLUSTERED  ([TPOSTORE_ID]) ON [PRIMARY]
GO
