CREATE TABLE [dbo].[LOG_EOD]
(
[LE_DATE_CREATE] [datetime] NULL,
[LE_OP_CREATE] [int] NULL,
[UNIT_ID] [int] NOT NULL,
[LOG_EOD_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__LOG_EOD__LOG_EOD__1A54DAB7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOG_EOD] ADD CONSTRAINT [PK__LOG_EOD__689634F61C3D2329] PRIMARY KEY CLUSTERED  ([LOG_EOD_ID]) ON [PRIMARY]
GO
