CREATE TABLE [dbo].[SYS$PARAMETER_COMP]
(
[PARC_PARCT_ID] [int] NOT NULL,
[PARC_COMP_ID] [int] NOT NULL,
[PARC_VALUE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SYS$PARAM__DATE___5F9E293D] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[SYS$PARAMETER_COMP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$PARAM__SYS$P__0AA882D3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$PARAMETER_COMP] ADD CONSTRAINT [PK__SYS$PARA__3105788C0C90CB45] PRIMARY KEY CLUSTERED  ([SYS$PARAMETER_COMP_ID]) ON [PRIMARY]
GO
