CREATE TABLE [dbo].[REF$PERIODE]
(
[PER_UNT_ID] [int] NOT NULL,
[PER_NAME] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PER_DAYS] [int] NULL CONSTRAINT [DF__REF$PERIO__PER_D__2E3BD7D3] DEFAULT ((1)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$PERIO__DATE___2F2FFC0C] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$PERIODE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$PERIO__REF$P__088B3037] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$PERIODE] ADD CONSTRAINT [PK__REF$PERI__CFCEC5580A7378A9] PRIMARY KEY CLUSTERED  ([REF$PERIODE_ID]) ON [PRIMARY]
GO
