CREATE TABLE [dbo].[REF$MATAUANG]
(
[UANG_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UANG_SYMBOL] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UANG_NAME] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UANG_SCALE] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$MATAU__DATE___1FEDB87C] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$MATAUANG_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$MATAU__REF$M__13FCE2E3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$MATAUANG] ADD CONSTRAINT [PK__REF$MATA__E38B205315E52B55] PRIMARY KEY CLUSTERED  ([REF$MATAUANG_ID]) ON [PRIMARY]
GO
