CREATE TABLE [dbo].[REF$TIPE_SUPLIER]
(
[TPSUP_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TPSUP_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$TIPE___DATE___5B0E7E4A] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$TIPE_SUPLIER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$TIPE___REF$T__532343BF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_SUPLIER] ADD CONSTRAINT [PK__REF$TIPE__D7DD314E550B8C31] PRIMARY KEY CLUSTERED  ([REF$TIPE_SUPLIER_ID]) ON [PRIMARY]
GO
