CREATE TABLE [dbo].[REF$DISC_MEMBER]
(
[DISCMEMBER_ID] [int] NOT NULL,
[DISCMEMBER_UNT_ID] [int] NOT NULL,
[DISCMEMBER_TPMEMBER_ID] [int] NOT NULL,
[DISCMEMBER_TPMEMBER_UNTID] [int] NOT NULL,
[DISCMEMBER_BEGIN_VALUE] [numeric] (21, 3) NULL,
[DISCMEMBER_END_VALUE] [numeric] (21, 3) NULL,
[DISCMEMBER_DISCOUNT] [numeric] (7, 2) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$DISC___DATE___025D5595] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$DISC_MEMBER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$DISC___REF$D__742F31CF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$DISC_MEMBER] ADD CONSTRAINT [PK__REF$DISC__B2A0EA2B76177A41] PRIMARY KEY CLUSTERED  ([REF$DISC_MEMBER_ID]) ON [PRIMARY]
GO
