CREATE TABLE [dbo].[REKENING_CF]
(
[REKCF_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REKCF_COMP_ID] [int] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REKENING___DATE___668030F6] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[ISBANKACCOUNT] [int] NULL CONSTRAINT [DF__REKENING___ISBAN__6774552F] DEFAULT ((0)),
[REKENING_CF_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REKENING___REKEN__5D56B96F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REKENING_CF] ADD CONSTRAINT [PK__REKENING__39143BBF5F3F01E1] PRIMARY KEY CLUSTERED  ([REKENING_CF_ID]) ON [PRIMARY]
GO
