CREATE TABLE [dbo].[TSQLEODHISTORY]
(
[HEADERFLAG] [int] NOT NULL,
[SQL] [image] NOT NULL,
[URUTAN] [int] NOT NULL,
[UNITID] [int] NOT NULL,
[THOTRANSFEREOD_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TSQLEODHISTORY_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TSQLEODHI__TSQLE__7DF8932B] DEFAULT (newid())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[TSQLEODHISTORY] ADD CONSTRAINT [PK__TSQLEODH__A6A2FCEE7FE0DB9D] PRIMARY KEY CLUSTERED  ([TSQLEODHISTORY_ID]) ON [PRIMARY]
GO
