CREATE TABLE [dbo].[REF$TIPE_KUPON]
(
[TPKUPON_ID] [int] NOT NULL,
[TPKUPON_NAMA] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$TIPE___DATE___49E3F248] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$TIPE_KUP__ID__53C2623D] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_KUPON] ADD CONSTRAINT [PK__REF$TIPE__3214EC2755AAAAAF] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
