CREATE TABLE [dbo].[TPOTONGANITEM]
(
[UNIT_ID] [int] NOT NULL,
[NOBUKTI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOBUKTIUNIT_ID] [int] NOT NULL,
[NOMINAL] [float] NULL,
[NOMINALPPN] [float] NULL,
[NOMINALPPNBM] [float] NULL,
[PPN] [float] NULL,
[PPNBM] [float] NULL,
[CLAIMDETAIL_ID] [int] NULL,
[CLAIMDETAIL_UNIT_ID] [int] NULL,
[POTTGH_ID] [int] NULL,
[POTTGH_UNT_ID] [int] NULL,
[TPOTONGANITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TPOTONGAN__TPOTO__3A8CA01F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPOTONGANITEM] ADD CONSTRAINT [PK__TPOTONGA__F057FED93C74E891] PRIMARY KEY CLUSTERED  ([TPOTONGANITEM_ID]) ON [PRIMARY]
GO
