CREATE TABLE [dbo].[CN_DAMAGE_DETIL]
(
[CNDD_UNT_ID] [int] NOT NULL,
[CNDD_CNDMG_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CNDD_CNDMG_UNT_ID] [int] NOT NULL,
[CNDD_BRGSUP_ID] [int] NOT NULL,
[CNDD_BRGSUP_UNT_ID] [int] NOT NULL,
[CNDD_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CNDD_PO_UNT_ID] [int] NOT NULL,
[CNDD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__CN_DAMAGE__CNDD___3864608B] DEFAULT ((0)),
[CNDD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNDD_PRICE] [numeric] (21, 3) NULL,
[CNDD_TOTAL] [numeric] (21, 3) NULL,
[CNDD_PPN_PERSEN] [numeric] (7, 2) NULL,
[CNDD_PPN] [numeric] (21, 3) NULL,
[CNDD_PPNBM_PERSEN] [numeric] (7, 2) NULL,
[CNDD_PPNBM] [numeric] (21, 3) NULL,
[CNDD_TOTAL_TAX] [numeric] (21, 3) NULL,
[CNDD_IS_PROCESS] [int] NULL,
[CNDD_IS_OUTSTANDING] [int] NULL,
[CNDD_DO_NO_NEW] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNDD_DO_UNT_ID_NEW] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CN_DAMAGE__DATE___395884C4] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[CNDD_IGRD_ID] [int] NULL,
[CNDD_IGRD_UNT_ID] [int] NULL,
[CNDD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNDD_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CN_DAMAGE_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CN_DAMAGE__CN_DA__35E7E693] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CN_DAMAGE_DETIL] ADD CONSTRAINT [PK__CN_DAMAG__70EB5D2137D02F05] PRIMARY KEY CLUSTERED  ([CN_DAMAGE_DETIL_ID]) ON [PRIMARY]
GO
