CREATE TABLE [dbo].[SHIFT]
(
[SHIFT_UNT_ID] [int] NOT NULL,
[SHIFT_NAME] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SHIFT_START_TIME] [datetime] NULL,
[SHIFT_END_TIME] [datetime] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SHIFT__DATE_CREA__031C6FA4] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SHIFT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SHIFT__SHIFT_ID__349EBC9F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SHIFT] ADD CONSTRAINT [PK__SHIFT__EF7FA00736870511] PRIMARY KEY CLUSTERED  ([SHIFT_ID]) ON [PRIMARY]
GO
