CREATE TABLE [dbo].[PROPINSI]
(
[PROP_NAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_CREATE] [datetime] NULL,
[OP_CREATE] [int] NULL,
[OPC_UNIT] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[OPM_UNIT] [int] NULL,
[PROPINSI_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PROPINSI__PROPIN__42A2C333] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROPINSI] ADD CONSTRAINT [PK__PROPINSI__AA171D71448B0BA5] PRIMARY KEY CLUSTERED  ([PROPINSI_ID]) ON [PRIMARY]
GO
