CREATE TABLE [dbo].[DO_BONUS]
(
[DOB_UNT_ID] [int] NOT NULL,
[DOB_DOD_ID] [int] NOT NULL,
[DOB_DOD_UNT_ID] [int] NOT NULL,
[DOB_BNS_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DOB_QTY_CS] [numeric] (18, 3) NULL CONSTRAINT [DF__DO_BONUS__DOB_QT__02C769E9] DEFAULT ((0)),
[DOB_QTY_SALES] [numeric] (18, 3) NULL CONSTRAINT [DF__DO_BONUS__DOB_QT__03BB8E22] DEFAULT ((0)),
[DOB_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__DO_BONUS__DOB_QT__04AFB25B] DEFAULT ((0)),
[DOB_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__DO_BONUS__DATE_C__05A3D694] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[DO_BONUS_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__DO_BONUS__DO_BON__7CAF6937] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DO_BONUS] ADD CONSTRAINT [PK__DO_BONUS__74C13DF57E97B1A9] PRIMARY KEY CLUSTERED  ([DO_BONUS_ID]) ON [PRIMARY]
GO
