CREATE TABLE [dbo].[TPOBONUSITEM]
(
[UOMUNIT_ID] [int] NOT NULL,
[PO_NO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PO_UNIT_ID] [int] NOT NULL,
[BARANG_CODE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BARANGUNIT_ID] [int] NOT NULL,
[UOM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[QTY] [float] NOT NULL,
[ISBONUSFORBONUS] [int] NOT NULL,
[POITEMUNIT_ID] [int] NULL,
[OP_MODIFY] [int] NULL,
[TPOBONUSITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TPOBONUSI__TPOBO__75E27017] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPOBONUSITEM] ADD CONSTRAINT [PK__TPOBONUS__C19B676177CAB889] PRIMARY KEY CLUSTERED  ([TPOBONUSITEM_ID]) ON [PRIMARY]
GO
