CREATE TABLE [dbo].[AUT$APP]
(
[APP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APP_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APP_DESCRIPTION] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_CREATE] [datetime] NULL,
[DATE_MODIFY] [datetime] NULL,
[OP_CREATE] [int] NULL,
[OP_MODIFY] [int] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[AUT$APP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AUT$APP__ID__390E6C01] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUT$APP] ADD CONSTRAINT [PK__AUT$APP__3214EC273AF6B473] PRIMARY KEY CLUSTERED  ([AUT$APP_ID]) ON [PRIMARY]
GO
