CREATE TABLE [dbo].[KOORDINATOR_SOP]
(
[KSOP_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KSOP_UNT_ID] [int] NOT NULL,
[KSOP_PSOP_ID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KSOP_PSOP_UNT_ID] [int] NOT NULL,
[KSOP_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__KOORDINAT__DATE___73501C2F] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[KOORDINATOR_SOP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__KOORDINAT__KOORD__074CF33B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KOORDINATOR_SOP] ADD CONSTRAINT [PK__KOORDINA__4ADE3A4809353BAD] PRIMARY KEY CLUSTERED  ([KOORDINATOR_SOP_ID]) ON [PRIMARY]
GO
