CREATE TABLE [dbo].[ADJUSTMENT_BARANG_TURUNAN]
(
[ADJBRGTUR_UNT_ID] [int] NOT NULL,
[ADJBRGTUR_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJBRGTUR_DATE] [date] NULL,
[ADJBRGTUR_TOTAL_ADJ] [int] NULL,
[ADJBRGTUR_TOTAL_WASTAGE] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ADJUSTMENT_BARANG_TURUNAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ADJUSTMEN__ADJUS__26A5A303] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADJUSTMENT_BARANG_TURUNAN] ADD CONSTRAINT [PK__ADJUSTME__685DE4A4288DEB75] PRIMARY KEY CLUSTERED  ([ADJUSTMENT_BARANG_TURUNAN_ID]) ON [PRIMARY]
GO
