CREATE TABLE [dbo].[REF$GRUP_JURNAL_DETIL]
(
[GROJURD_COMP_ID] [int] NOT NULL,
[GROJURD_GROJUR_CODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GROJURD_GROJUR_COMP_ID] [int] NOT NULL,
[GROJURD_KDJUR_ID] [int] NOT NULL,
[GROJURD_KDJUR_COMPANY_ID] [int] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$GRUP___DATE___08162EEB] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[REF$GRUP_JURNAL_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$GRUP___REF$G__17CD73C7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$GRUP_JURNAL_DETIL] ADD CONSTRAINT [PK__REF$GRUP__67ED4C1C19B5BC39] PRIMARY KEY CLUSTERED  ([REF$GRUP_JURNAL_DETIL_ID]) ON [PRIMARY]
GO
