CREATE TABLE [dbo].[TBONUSRULE]
(
[DATEFROM] [date] NOT NULL,
[DATETO] [date] NOT NULL,
[ISACTIVE] [int] NOT NULL,
[ISBONUSFORBONUS] [int] NOT NULL,
[ISKELIPATAN] [int] NOT NULL,
[KODEBARANG] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KODEBARANGBONUS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[QTYBONUS] [float] NOT NULL,
[QTYFROM] [float] NOT NULL,
[QTYTO] [float] NOT NULL,
[SATUANBARANG] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SATUANBARANGBONUS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STAMP] [datetime] NULL,
[UNITID] [int] NOT NULL,
[KODEBARANGBONUSUNITID] [int] NOT NULL,
[KODEBARANGUNITID] [int] NOT NULL,
[SUPPLIERCODE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUPPLIERUNITID] [int] NOT NULL,
[SATUANBARANGBONUSUNITID] [int] NOT NULL,
[SATUANBARANGUNITID] [int] NOT NULL,
[TBONUSRULE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TBONUSRUL__TBONU__0524B3A7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBONUSRULE] ADD CONSTRAINT [PK__TBONUSRU__2B124065070CFC19] PRIMARY KEY CLUSTERED  ([TBONUSRULE_ID]) ON [PRIMARY]
GO
