CREATE TABLE [dbo].[SYS$PARAMETER]
(
[PAR_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAR_VALUE] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAR_GROUP] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAR_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS$PARAMETER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$PARAM__SYS$P__0E7913B7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$PARAMETER] ADD CONSTRAINT [PK__SYS$PARA__15EAE13B10615C29] PRIMARY KEY CLUSTERED  ([SYS$PARAMETER_ID]) ON [PRIMARY]
GO
