CREATE TABLE [dbo].[ADS_KELUAR]
(
[ADSO_UNT_ID] [int] NOT NULL,
[ADSO_ADSI_ID] [int] NOT NULL,
[ADSO_ADSI_UNT_ID] [int] NOT NULL,
[ADSO_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADSO_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADSO_PRICE_REDUCED] [numeric] (21, 3) NOT NULL,
[ADSO_DATE] [datetime] NULL CONSTRAINT [DF__ADS_KELUA__ADSO___173876EA] DEFAULT (getdate()),
[ADSO_NOMINAL] [numeric] (21, 3) NULL,
[ADSO_KDJUR_ID] [int] NULL,
[ADSO_KDJUR_COMP_ID] [int] NULL,
[ADSO_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADSO_REK_COMP_ID] [int] NULL,
[ADSO_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__ADS_KELUA__ADSO___182C9B23] DEFAULT ((0)),
[ADSO_PRICE_BEFORE] [numeric] (21, 3) NULL,
[ADSO_PRICE_AFTER] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__ADS_KELUA__DATE___1920BF5C] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ADS_KELUAR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ADS_KELUA__ADS_K__575DE8F7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADS_KELUAR] ADD CONSTRAINT [PK__ADS_KELU__B63FB51459463169] PRIMARY KEY CLUSTERED  ([ADS_KELUAR_ID]) ON [PRIMARY]
GO
