CREATE TABLE [dbo].[REF$SATUAN]
(
[SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REF$SATUA__SAT_C__3EC74557] DEFAULT (newid()),
[SAT_NAME] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SAT_GROUP] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[SAT_URUTAN] [int] NOT NULL CONSTRAINT [DF__REF$SATUA__SAT_U__3118447E] DEFAULT ((0)),
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$SATUA__DATE___320C68B7] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SAT_HO_AUTHORIZE] [int] NOT NULL CONSTRAINT [DF__REF$SATUA__SAT_H__33008CF0] DEFAULT ((0)),
[REF$SATUAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$SATUAN__ID__3CDEFCE5] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$SATUAN] ADD CONSTRAINT [PK__REF$SATU__3214EC2740AF8DC9] PRIMARY KEY CLUSTERED  ([REF$SATUAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$SATUAN] ADD CONSTRAINT [UNIQUE_SAT_CODE] UNIQUE NONCLUSTERED  ([SAT_CODE]) ON [PRIMARY]
GO
