CREATE TABLE [dbo].[COST_CENTER]
(
[COCTER_UNT_ID] [int] NULL,
[COCTER_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COCTER_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__COST_CENT__DATE___56E8E7AB] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[COST_CENTER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__COST_CENT__COST___009508B4] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COST_CENTER] ADD CONSTRAINT [PK__COST_CEN__F8483977027D5126] PRIMARY KEY CLUSTERED  ([COST_CENTER_ID]) ON [PRIMARY]
GO
