CREATE TABLE [dbo].[AGREEMENT_DETIL]
(
[AGRD_UNT_ID] [int] NOT NULL,
[AGRD_AGR_ID] [int] NOT NULL,
[AGRD_AGR_UNT_ID] [int] NOT NULL,
[AGRD_PROJAS_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AGRD_PROJAS_UNT_ID] [int] NOT NULL,
[AGRD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__AGREEMENT__AGRD___239E4DCF] DEFAULT ((0)),
[AGRD_PRICE] [numeric] (21, 3) NULL CONSTRAINT [DF__AGREEMENT__AGRD___24927208] DEFAULT ((0)),
[AGRD_SUBTOTAL] [numeric] (21, 3) NULL,
[AGRD_TOTAL] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__AGREEMENT__DATE___25869641] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[AGRD_PRICE_PPN] [numeric] (21, 3) NULL CONSTRAINT [DF__AGREEMENT__AGRD___267ABA7A] DEFAULT ((0)),
[AGREEMENT_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AGREEMENT__AGREE__20B7BF83] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGREEMENT_DETIL] ADD CONSTRAINT [PK__AGREEMEN__CD81419922A007F5] PRIMARY KEY CLUSTERED  ([AGREEMENT_DETIL_ID]) ON [PRIMARY]
GO
