CREATE TABLE [dbo].[SHIPMENT_AGENT]
(
[AGENT_CODE] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AGENT_UNT_ID] [int] NOT NULL,
[AGENT_NAME] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGENT_DESCRIPTION] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SHIPMENT___DATE___0504B816] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SHIPMENT_AGENT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SHIPMENT___SHIPM__2FFA0313] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SHIPMENT_AGENT] ADD CONSTRAINT [PK__SHIPMENT__D0E7A07C31E24B85] PRIMARY KEY CLUSTERED  ([SHIPMENT_AGENT_ID]) ON [PRIMARY]
GO
