CREATE TABLE [dbo].[DLINK_PRD]
(
[PRD_DATE] [datetime] NOT NULL,
[PRD_UNIT] [int] NOT NULL,
[PRD_POSCODE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TYPE_DOWN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DLINK_PRD_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__DLINK_PRD__DLINK__5986288B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DLINK_PRD] ADD CONSTRAINT [PK__DLINK_PR__01BFF2075B6E70FD] PRIMARY KEY CLUSTERED  ([DLINK_PRD_ID]) ON [PRIMARY]
GO
