CREATE TABLE [dbo].[SYS$EXPORT_HISTORY]
(
[EXH_UNT_ID] [int] NOT NULL,
[EXH_USR_ID] [int] NULL,
[EXH_USR_UNT_ID] [int] NULL,
[EXH_DATE] [datetime] NULL,
[EXH_COMP_INFO] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXH_PREV_SESSION_ID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXH_PREV_EXH_UNT_ID] [int] NULL,
[EXH_ALLOW_IGNORE_PREVIOUS] [int] NOT NULL,
[SYS$EXPORT_HISTORY_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$EXPOR__SYS$E__23A93AC7] DEFAULT (newid())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$EXPORT_HISTORY] ADD CONSTRAINT [PK__SYS$EXPO__F276217625918339] PRIMARY KEY CLUSTERED  ([SYS$EXPORT_HISTORY_ID]) ON [PRIMARY]
GO
