CREATE TABLE [dbo].[CLAIM_DETIL]
(
[CLMD_UNT_ID] [int] NOT NULL,
[CLMD_CLM_ID] [int] NOT NULL,
[CLMD_CLM_UNT_ID] [int] NOT NULL,
[CLMD_CLAIM_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLMD_DO_NP] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLMD_DO_UNT_ID] [int] NOT NULL,
[CLMD_PPN] [numeric] (21, 3) NULL,
[CLMD_PPNBM] [numeric] (21, 3) NULL,
[CLMD_PPN_MASUKAN] [numeric] (21, 3) NULL,
[CLMD_PPNBM_MASUKAN] [numeric] (21, 3) NULL,
[CLMD_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CLAIM_DET__DATE___2BFE89A6] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[CLMD_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLMD_PO_UNT_ID] [int] NULL,
[CLMD_DO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLMD_DO_NO_UNT_ID] [int] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CLMD_INV_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLMD_INV_DATE] [datetime] NULL,
[CLMD_INV_NP] [numeric] (21, 3) NULL,
[CLMD_INV_TOTAL] [numeric] (21, 3) NULL,
[CLMD_INV_TAX_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLMD_INV_TAX_DATE] [date] NULL,
[CLAIM_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CLAIM_DET__CLAIM__4159993F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLAIM_DETIL] ADD CONSTRAINT [PK__CLAIM_DE__97F357C74341E1B1] PRIMARY KEY CLUSTERED  ([CLAIM_DETIL_ID]) ON [PRIMARY]
GO
