CREATE TABLE [dbo].[TRANSAKSI]
(
[TRANS_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANS_UNT_ID] [int] NOT NULL,
[TRANS_DATE] [datetime] NULL CONSTRAINT [DF__TRANSAKSI__TRANS__2630A1B7] DEFAULT (getdate()),
[TRANS_MEMBER_ID] [int] NOT NULL,
[TRANS_MEMBER_UNT_ID] [int] NOT NULL,
[TRANS_BALANCE_ID] [int] NOT NULL,
[TRANS_BALANCE_UNT_ID] [int] NOT NULL,
[TRANS_TOTAL_TRANSACTION] [numeric] (21, 3) NULL,
[TRANS_TOTAL_DISC_GMC] [numeric] (21, 3) NULL CONSTRAINT [DF__TRANSAKSI__TRANS__2724C5F0] DEFAULT ((0)),
[TRANS_DISC_GMC_PERSEN] [numeric] (7, 2) NULL CONSTRAINT [DF__TRANSAKSI__TRANS__2818EA29] DEFAULT ((0)),
[TRANS_DISC_GMC_NOMINAL] [numeric] (21, 3) NULL CONSTRAINT [DF__TRANSAKSI__TRANS__290D0E62] DEFAULT ((0)),
[TRANS_TOTAL_BAYAR] [numeric] (21, 3) NULL,
[TRANS_PEMBULAT] [numeric] (21, 3) NULL,
[TRANS_BAYAR_CASH] [numeric] (21, 3) NULL,
[TRANS_BAYAR_CARD] [numeric] (21, 3) NULL,
[TRANS_IS_ACTIVE] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TRANSAKSI__DATE___2A01329B] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TRANS_IS_PENDING] [int] NULL,
[TRANS_TOTAL_PPN] [numeric] (21, 3) NULL,
[TRANS_IS_JURNAL] [int] NULL,
[TRANS_DISC_CARD] [float] NULL,
[TRANSAKSI_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANSAKSI__TRANS__60B24907] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSAKSI] ADD CONSTRAINT [PK__TRANSAKS__444711AA629A9179] PRIMARY KEY CLUSTERED  ([TRANSAKSI_ID]) ON [PRIMARY]
GO
