CREATE TABLE [dbo].[TEMP$DSR]
(
[TR_DATE] [datetime] NULL,
[KB_BKP] [numeric] (21, 3) NULL,
[KB_BTKP] [numeric] (21, 3) NULL,
[KB_RFU_BKP] [numeric] (21, 3) NULL,
[KB_RFU_BTKP] [numeric] (21, 3) NULL,
[KB_BRU_JUAL] [numeric] (21, 3) NULL,
[KB_PPN] [numeric] (21, 3) NULL,
[KB_RFU_PPN] [numeric] (21, 3) NULL,
[KB_BRU_PPN] [numeric] (21, 3) NULL,
[KB_NET] [numeric] (21, 3) NULL,
[PP_KAS_SAL] [numeric] (21, 3) NULL,
[PP_KAS_ADJ] [numeric] (21, 3) NULL,
[PP_KAS_RFU] [numeric] (21, 3) NULL,
[PP_KAS_SUB] [numeric] (21, 3) NULL,
[PP_DEB_SAL] [numeric] (21, 3) NULL,
[PP_DEB_ADJ] [numeric] (21, 3) NULL,
[PP_DEB_RFU] [numeric] (21, 3) NULL,
[PP_DEB_SUB] [numeric] (21, 3) NULL,
[PP_CARD_SAL] [numeric] (21, 3) NULL,
[PP_CARD_ADJ] [numeric] (21, 3) NULL,
[PP_CARD_RFU] [numeric] (21, 3) NULL,
[PP_CARD_SUB] [numeric] (21, 3) NULL,
[PP_KUP_GR] [numeric] (21, 3) NULL,
[PP_KUP_LL] [numeric] (21, 3) NULL,
[PP_KUP_BTL] [numeric] (21, 3) NULL,
[PP_KUP_ADJ] [numeric] (21, 3) NULL,
[PP_KUP_SUB] [numeric] (21, 3) NULL,
[ADJ_KPN_GR] [numeric] (21, 3) NULL,
[ADJ_KPN_LL] [numeric] (21, 3) NULL,
[ADJ_KPN_BTL] [numeric] (21, 3) NULL,
[PP_TOTAL] [numeric] (21, 3) NULL,
[PP_BULAT] [numeric] (21, 3) NULL,
[PP_CARD_FEE] [numeric] (21, 3) NULL,
[PP_NET] [numeric] (21, 3) NULL,
[PP_POT] [numeric] (21, 3) NULL,
[K_AWAL] [numeric] (21, 3) NULL,
[K_TJ_KAS] [numeric] (21, 3) NULL,
[K_TJ_KPN] [numeric] (21, 3) NULL,
[K_TJ_KPN_DISC] [numeric] (21, 3) NULL,
[K_TJ_SUB] [numeric] (21, 3) NULL,
[K_TL_VOID] [numeric] (21, 3) NULL,
[K_TL_KSR] [numeric] (21, 3) NULL,
[K_TL_LL] [numeric] (21, 3) NULL,
[K_TL_SUB] [numeric] (21, 3) NULL,
[K_KL_VOID] [numeric] (21, 3) NULL,
[K_KL_KSR] [numeric] (21, 3) NULL,
[K_KL_LL] [numeric] (21, 3) NULL,
[K_KL_BCA_ADJ] [numeric] (21, 3) NULL,
[K_KL_BCA] [numeric] (21, 3) NULL,
[K_KL_SUB] [numeric] (21, 3) NULL,
[K_TOT] [numeric] (21, 3) NULL,
[K_AKHIR] [numeric] (21, 3) NULL,
[K_SETOR] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ID] [int] NOT NULL,
[TEMP$DSR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TEMP$DSR__TEMP$D__3513BDEB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMP$DSR] ADD CONSTRAINT [PK__TEMP$DSR__45B444CD36FC065D] PRIMARY KEY CLUSTERED  ([TEMP$DSR_ID]) ON [PRIMARY]
GO
