CREATE TABLE [dbo].[VOUCHER]
(
[VCR_UNT_ID] [int] NOT NULL,
[VCR_AGRV_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VCR_AGRV_UNT_ID] [int] NOT NULL,
[VCR_ISSUED_DATE] [datetime] NULL CONSTRAINT [DF__VOUCHER__VCR_ISS__59B045BD] DEFAULT (getdate()),
[VCR_NOMINAL] [numeric] (21, 3) NULL,
[VCR_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__VOUCHER__VCR_QTY__5AA469F6] DEFAULT ((0)),
[VCR_START_DATE] [datetime] NOT NULL,
[VCR_EXPIRE_DATE] [datetime] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__VOUCHER__DATE_CR__5B988E2F] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[VOUCHER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__VOUCHER__VOUCHER__4D9F7493] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOUCHER] ADD CONSTRAINT [PK__VOUCHER__60E7A0B34F87BD05] PRIMARY KEY CLUSTERED  ([VOUCHER_ID]) ON [PRIMARY]
GO
