CREATE TABLE [dbo].[AGREEMENT_VOUCHER]
(
[AGRV_UNT_ID] [int] NOT NULL,
[AGRV_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AGRV_DATE] [datetime] NULL CONSTRAINT [DF__AGREEMENT__AGRV___2E1BDC42] DEFAULT (getdate()),
[AGRV_CUSTV_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AGRV_CUSTV_UNT_ID] [int] NOT NULL,
[AGRV_TOTAL] [numeric] (21, 3) NULL,
[AGRV_DISC] [numeric] (7, 2) NULL,
[AGRV_TOTAL_AFTER_DISC] [numeric] (21, 3) NULL,
[AGRV_DUE_DATE] [datetime] NULL CONSTRAINT [DF__AGREEMENT__AGRV___2F10007B] DEFAULT (getdate()),
[AGRV_STATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__AGREEMENT__DATE___300424B4] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[AGREEMENT_VOUCHER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AGREEMENT__AGREE__19169DBB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGREEMENT_VOUCHER] ADD CONSTRAINT [PK__AGREEMEN__B1583DB81AFEE62D] PRIMARY KEY CLUSTERED  ([AGREEMENT_VOUCHER_ID]) ON [PRIMARY]
GO
