CREATE TABLE [dbo].[DISBURSTMENT_DETIL]
(
[DISD_UNT_ID] [int] NOT NULL,
[DISD_DIS_ID] [int] NOT NULL,
[DISD_DIS_UNT_ID] [int] NOT NULL,
[DISD_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DISD_REK_COMP_ID] [int] NOT NULL,
[DISD_TOTAL] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__DISBURSTM__DATE___6442E2C9] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[DISBURSTMENT_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__DISBURSTM__DISBU__08211BE3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DISBURSTMENT_DETIL] ADD CONSTRAINT [PK__DISBURST__845F2BE00A096455] PRIMARY KEY CLUSTERED  ([DISBURSTMENT_DETIL_ID]) ON [PRIMARY]
GO
