CREATE TABLE [dbo].[FORM_SOP_DETIL]
(
[FSOPD_UNT_ID] [int] NOT NULL,
[FSOPD_FSOP_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FSOPD_FSOP_UNT_ID] [int] NOT NULL,
[FSOPD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FSOPD_IS_ENTRY] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__FORM_SOP___DATE___308E3499] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[FSOPD_NOURUT] [int] NULL,
[FORM_SOP_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__FORM_SOP___FORM___102C51FF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FORM_SOP_DETIL] ADD CONSTRAINT [PK__FORM_SOP__6ADC1EC112149A71] PRIMARY KEY CLUSTERED  ([FORM_SOP_DETIL_ID]) ON [PRIMARY]
GO
