CREATE TABLE [dbo].[SCENARIO_VALUE]
(
[SVAL_UNT_ID] [int] NOT NULL,
[SVAL_SCENSD_ID] [int] NOT NULL,
[SVAL_SCENSD_UNT_ID] [int] NOT NULL,
[SVAL_MULTIPLIER] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SCENARIO___SVAL___789EE131] DEFAULT ('  1'),
[SVAL_IS_MULTIPLIER_VAR] [int] NULL,
[SVAL_MULTIPLICANT] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SCENARIO___SVAL___7993056A] DEFAULT ('     ''TO'),
[SVAL_IS_MULTIPLICANT_VAR] [int] NULL,
[SVAL_OTHER] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SCENARIO___SVAL___7A8729A3] DEFAULT ('  1'),
[SVAL_IS_OTHER_VAR] [int] NULL,
[SVAL_IS_POSITIVE] [int] NULL CONSTRAINT [DF__SCENARIO___SVAL___7B7B4DDC] DEFAULT ((1)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SCENARIO___DATE___7C6F7215] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SCENARIO_VALUE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SCENARIO___SCENA__43E1002F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SCENARIO_VALUE] ADD CONSTRAINT [PK__SCENARIO__6DE4755C45C948A1] PRIMARY KEY CLUSTERED  ([SCENARIO_VALUE_ID]) ON [PRIMARY]
GO
