CREATE TABLE [dbo].[CN_RETUR_REPLACEMENT_DETIL]
(
[CNRRD_UNT_ID] [int] NOT NULL,
[CNRRD_CNRTD_ID] [int] NOT NULL,
[CNRRD_CNRTD_UNT_ID] [int] NOT NULL,
[CNRRD_BRGSUP_ID] [int] NOT NULL,
[CNRRD_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNRRD_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNRRD_DATE] [datetime] NULL CONSTRAINT [DF__CN_RETUR___CNRRD__498EEC8D] DEFAULT (getdate()),
[CNRRD_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__CN_RETUR___CNRRD__4A8310C6] DEFAULT ((0)),
[CNRRD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNRRD_PRICE] [numeric] (21, 3) NULL,
[CNRRD_TOTAL] [numeric] (21, 3) NULL,
[CNRRD_IS_PROCESS] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CN_RETUR___DATE___4B7734FF] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[CNRRD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNRRD_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNRRD_CNRET_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNRRD_CNRET_UNT_ID] [int] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CN_RETUR_REPLACEMENT_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CN_RETUR___CN_RE__22D5121F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CN_RETUR_REPLACEMENT_DETIL] ADD CONSTRAINT [PK__CN_RETUR__B75E12FB24BD5A91] PRIMARY KEY CLUSTERED  ([CN_RETUR_REPLACEMENT_DETIL_ID]) ON [PRIMARY]
GO
