CREATE TABLE [dbo].[TEMP_LAPORAN]
(
[LAPORAN_ID] [int] NOT NULL,
[USER_ID] [int] NOT NULL,
[CHAR1] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR2] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR3] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUM1] [float] NULL,
[NUM2] [float] NULL,
[NUM3] [float] NULL,
[NUM4] [float] NULL,
[NUM5] [float] NULL,
[NUM6] [float] NULL,
[NUM7] [float] NULL,
[NUM8] [float] NULL,
[NUM9] [float] NULL,
[NUM10] [float] NULL,
[NUM11] [float] NULL,
[NUM12] [float] NULL,
[NUM13] [float] NULL,
[NUM14] [float] NULL,
[NUM15] [float] NULL,
[NUM16] [int] NULL,
[CHAR4] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUM17] [float] NULL,
[NUM18] [float] NULL,
[NUM19] [float] NULL,
[NUM20] [float] NULL,
[CHAR5] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR6] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR7] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BRG_UNT_ID] [int] NULL,
[CHAR8] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR9] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR10] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR11] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR12] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR13] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR14] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAR15] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEMP_LAPORAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TEMP_LAPO__TEMP___3F3C46A3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMP_LAPORAN] ADD CONSTRAINT [PK__TEMP_LAP__80556A6B41248F15] PRIMARY KEY CLUSTERED  ([TEMP_LAPORAN_ID]) ON [PRIMARY]
GO
