CREATE TABLE [dbo].[TSTOREIMPORT_ITEM]
(
[ID] [int] NOT NULL,
[SQL] [image] NOT NULL,
[URUTAN] [int] NOT NULL,
[STOREIMPORT_ID] [int] NOT NULL,
[UNITID] [int] NOT NULL,
[HEADERFLAG] [int] NULL,
[UNITSRC] [int] NULL,
[TSTOREIMPORT_ITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TSTOREIMP__TSTOR__110B679F] DEFAULT (newid())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[TSTOREIMPORT_ITEM] ADD CONSTRAINT [PK__TSTOREIM__0636BCA712F3B011] PRIMARY KEY CLUSTERED  ([TSTOREIMPORT_ITEM_ID]) ON [PRIMARY]
GO
