CREATE TABLE [dbo].[SHIPMENT_DOCUMENT]
(
[SD_NO_BUKTI] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SD_UNT_ID] [int] NOT NULL,
[SD_TRANS_CODE] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SD_TRANS_UNT_ID] [int] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SHIPMENT___DATE___06ED0088] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SD_COLIE] [float] NOT NULL CONSTRAINT [DF__SHIPMENT___SD_CO__07E124C1] DEFAULT ((0.0)),
[SD_DES_UNT_ID] [int] NOT NULL,
[SHIPMENT_DOCUMENT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SHIPMENT___SHIPM__430CD787] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SHIPMENT_DOCUMENT] ADD CONSTRAINT [PK__SHIPMENT__CE89059D44F51FF9] PRIMARY KEY CLUSTERED  ([SHIPMENT_DOCUMENT_ID]) ON [PRIMARY]
GO
