CREATE TABLE [dbo].[BARANG_STOK_SIRKULASI]
(
[BSS_UNT_ID] [int] NOT NULL,
[BSS_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BSS_DATE] [datetime] NULL CONSTRAINT [DF__BARANG_ST__BSS_D__70DDC3D8] DEFAULT (getdate()),
[BSS_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_ST__BSS_Q__71D1E811] DEFAULT ((0)),
[BSS_QTY_COMMON] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_ST__BSS_Q__72C60C4A] DEFAULT ((0)),
[BSS_QTY_TRADER] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_ST__BSS_Q__73BA3083] DEFAULT ((0)),
[BSS_QTY_ASSGROS] [numeric] (18, 3) NULL CONSTRAINT [DF__BARANG_ST__BSS_Q__74AE54BC] DEFAULT ((0)),
[BSS_DOC_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSS_TYPE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSS_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSS_IS_EOD] [int] NULL,
[BSS_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__BARANG_ST__DATE___75A278F5] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[HEADERFLAG] [int] NOT NULL,
[ISBONUSFORBONUS] [int] NOT NULL,
[ITEM_ID] [int] NULL,
[BSS_HARGA_TRANSAKSI] [float] NULL,
[BSS_LASTCOST] [numeric] (21, 3) NULL,
[BARANG_STOK_SIRKULASI_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__BARANG_ST__BARAN__6B4FD30B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BARANG_STOK_SIRKULASI] ADD CONSTRAINT [PK__BARANG_S__4C5B59966D381B7D] PRIMARY KEY CLUSTERED  ([BARANG_STOK_SIRKULASI_ID]) ON [PRIMARY]
GO
