CREATE TABLE [dbo].[POTONGAN_TAGIHAN_DETIL]
(
[PTD_UNT_ID] [int] NOT NULL,
[PTD_POTTGH_ID] [int] NOT NULL,
[PTD_POTTGH_UNT_ID] [int] NOT NULL,
[PTD_AGRJDWL_INV_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PTD_AGRJDWL_UNT_ID] [int] NULL,
[PTD_STAPRO_ID] [int] NULL,
[PTD_TOTAL] [numeric] (21, 3) NULL,
[PTD_RESIDU] [numeric] (21, 3) NULL,
[PTD_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PTD_NO_OTHER_INCOME] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PTD_NO_OTHER_INCOME_UNT_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__POTONGAN___DATE___361203C5] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[PTD_CNDMG_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PTD_CNDMG_UNT_ID] [int] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[PTD_RET_NOBUKTI] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PTD_RET_UNT_ID] [int] NULL,
[POTONGAN_TAGIHAN_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__POTONGAN___POTON__4D35603F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POTONGAN_TAGIHAN_DETIL] ADD CONSTRAINT [PK__POTONGAN__F05B874D4F1DA8B1] PRIMARY KEY CLUSTERED  ([POTONGAN_TAGIHAN_DETIL_ID]) ON [PRIMARY]
GO
