CREATE TABLE [dbo].[SO_SUPLIER_BLACKLIST]
(
[SOSB_UNT_ID] [int] NOT NULL,
[SOSB_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__SO_SUPLIE__DATE___17236851] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SO_SUPLIER_BLACKLIST_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SO_SUPLIE__SO_SU__292D09F3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SO_SUPLIER_BLACKLIST] ADD CONSTRAINT [PK__SO_SUPLI__A0EFE11E2B155265] PRIMARY KEY CLUSTERED  ([SO_SUPLIER_BLACKLIST_ID]) ON [PRIMARY]
GO
