CREATE TABLE [dbo].[REF$GRUP_MEMBER]
(
[GROMEMBER_ID] [int] NULL,
[GROMEMBER_UNT_ID] [int] NULL,
[GROMEMBER_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GROMEMBER_DOC_ID] [int] NULL,
[GROMEMBER_IDENTITY_NO] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROMEMBER_NPWP] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROMEMBER_ADDRESS] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROMEMBER_KELURAHAN] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROMEMBER_KOTA] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROMEMBER_KODE_POS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROMEMBER_TELP] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROMEMBER_NO_FAX] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROMEMBER_IS_COMPLETE] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$GRUP___DATE___09FE775D] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$GRUP_MEMBER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$GRUP___REF$G__77FFC2B3] DEFAULT (newid()),
[REF$TIPE_PERUSAHAAN_ID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$GRUP_MEMBER] ADD CONSTRAINT [PK__REF$GRUP__F09A6C2479E80B25] PRIMARY KEY CLUSTERED  ([REF$GRUP_MEMBER_ID]) ON [PRIMARY]
GO
