CREATE TABLE [dbo].[DOWNPAYMENT_AR]
(
[DPAR_ID] [int] NOT NULL,
[DPAR_UNT_ID] [int] NOT NULL,
[DPAR_REFNO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPAR_REFDATE] [datetime] NULL,
[DPAR_AMOUNT] [float] NULL,
[DPAR_DESCRIPTION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPAR_ISJOURNALIZED] [int] NULL,
[DPAR_UANG_ID] [int] NULL,
[DPAR_JUR_ID] [int] NULL,
[DPAR_JUR_UNT_ID] [int] NULL,
[DPAR_RECEIPT_KIND] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPAR_MEMBER_ID] [int] NULL,
[DPAR_MEMBER_UNT_ID] [int] NULL,
[DPAR_TPBYR_ID] [int] NULL,
[DPAR_TPBYR_UNT_ID] [int] NULL,
[DPAR_ISEXECUTE] [int] NULL,
[DPAR_DUEDATE] [datetime] NULL,
[DPAR_STATUS] [int] NULL,
[DOWNPAYMENT_AR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__DOWNPAYME__DOWNP__25D17A5B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DOWNPAYMENT_AR] ADD CONSTRAINT [PK__DOWNPAYM__F9BA6DB227B9C2CD] PRIMARY KEY CLUSTERED  ([DOWNPAYMENT_AR_ID]) ON [PRIMARY]
GO
