CREATE TABLE [dbo].[QUOTATIONPROMO_DETIL]
(
[QUOTD_UNT_ID] [int] NOT NULL,
[QUOTD_QUOT_ID] [int] NOT NULL,
[QUOTD_QUOT_UNT_ID] [int] NOT NULL,
[QUOTD_SUP_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUOTD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[QUOTD_BRG_CODE_PARENT] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[QUOTD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[QUOTD_PRICE] [numeric] (21, 3) NULL CONSTRAINT [DF__QUOTATION__QUOTD__64CCF2AE] DEFAULT ((0)),
[QUOTD_MU_PERSEN] [numeric] (7, 2) NULL CONSTRAINT [DF__QUOTATION__QUOTD__65C116E7] DEFAULT ((0)),
[QUOTD_MU_RUPIAH] [numeric] (21, 3) NULL CONSTRAINT [DF__QUOTATION__QUOTD__66B53B20] DEFAULT ((0)),
[QUOTD_MU_RUPIAH_PLUS_PPN] [numeric] (21, 3) NULL CONSTRAINT [DF__QUOTATION__QUOTD__67A95F59] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[QUOTD_TIPE_HARGA_ID] [int] NOT NULL,
[QUOTD_TIPE_HARGA_UNT_ID] [int] NOT NULL,
[QUOTD_HARGA_AVERAGE] [float] NULL,
[QUOTD_DISC] [float] NULL,
[QUOTD_DISC_PERSEN] [float] NULL,
[QUOTATIONPROMO_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__QUOTATION__QUOTA__7D8391DF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QUOTATIONPROMO_DETIL] ADD CONSTRAINT [PK__QUOTATIO__E4B88BE87F6BDA51] PRIMARY KEY CLUSTERED  ([QUOTATIONPROMO_DETIL_ID]) ON [PRIMARY]
GO
