CREATE TABLE [dbo].[REF$HARI_LIBUR]
(
[LBR_UNT_ID] [int] NOT NULL,
[LBR_DATE] [date] NOT NULL,
[LBR_NAME] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$HARI___DATE___0DCF0841] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$HARI_LIBUR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$HARI___REF$H__2AE0483B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$HARI_LIBUR] ADD CONSTRAINT [PK__REF$HARI__0A95D5532CC890AD] PRIMARY KEY CLUSTERED  ([REF$HARI_LIBUR_ID]) ON [PRIMARY]
GO
