CREATE TABLE [dbo].[CLAIM_CONTRABON_POTONGAN]
(
[CLMCONTP_UNT_ID] [int] NOT NULL,
[CLMCONTP_CLMCONTD_ID] [int] NOT NULL,
[CLMCONTP_CLMCONTD_UNT_ID] [int] NOT NULL,
[CLMCONTP_POTTGHN_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLMCONTP_POTTGHN_UNT_ID] [int] NOT NULL,
[CLMCONTP_TOTAL] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CLAIM_CON__DATE___2A164134] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CLAIM_CONTRABON_POTONGAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CLAIM_CON__CLAIM__452A2A23] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLAIM_CONTRABON_POTONGAN] ADD CONSTRAINT [PK__CLAIM_CO__95E2131547127295] PRIMARY KEY CLUSTERED  ([CLAIM_CONTRABON_POTONGAN_ID]) ON [PRIMARY]
GO
