CREATE TABLE [dbo].[TSQLEOD]
(
[HEADERFLAG] [int] NOT NULL,
[SQL] [image] NOT NULL,
[URUTAN] [int] NOT NULL,
[TANGGAL] [datetime] NOT NULL,
[UNITID] [int] NOT NULL,
[TSQLEOD_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TSQLEOD__TSQLEOD__7A280247] DEFAULT (newid())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[TSQLEOD] ADD CONSTRAINT [PK__TSQLEOD__1C1EFCCA7C104AB9] PRIMARY KEY CLUSTERED  ([TSQLEOD_ID]) ON [PRIMARY]
GO
