CREATE TABLE [dbo].[TTRANSFERBARANGBONUSITEM]
(
[ID] [int] NOT NULL,
[BARANG_KODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BARANGUNIT_ID] [int] NOT NULL,
[HARGA] [float] NOT NULL,
[HEADER_ID] [int] NOT NULL,
[HEADERUNIT_ID] [int] NOT NULL,
[NEWUNIT_ID] [int] NOT NULL,
[QTY] [float] NOT NULL,
[UOM] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UOMUNIT_ID] [int] NOT NULL,
[KETERANGANTUJUAN] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTRANSFERBARANGBONUSITEM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TTRANSFER__TTRAN__18AC8967] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TTRANSFERBARANGBONUSITEM] ADD CONSTRAINT [PK__TTRANSFE__893D67121A94D1D9] PRIMARY KEY CLUSTERED  ([TTRANSFERBARANGBONUSITEM_ID]) ON [PRIMARY]
GO
