CREATE TABLE [dbo].[INVOICE_ASSGROS]
(
[INVAS_UNT_ID] [int] NOT NULL,
[INVAS_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INVAS_DOAS_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INVAS_DOAS_UNT_ID] [int] NOT NULL,
[INVAS_TRD_ID] [int] NOT NULL,
[INVAS_TRD_UNT_ID] [int] NOT NULL,
[INVAS_DATE] [datetime] NULL CONSTRAINT [DF__INVOICE_A__INVAS__5B78929E] DEFAULT (getdate()),
[INVAS_DUE_DATE] [datetime] NULL CONSTRAINT [DF__INVOICE_A__INVAS__5C6CB6D7] DEFAULT (getdate()),
[INVAS_TOTAL] [numeric] (21, 3) NOT NULL CONSTRAINT [DF__INVOICE_A__INVAS__5D60DB10] DEFAULT ((0)),
[INVAS_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVAS_STATUS] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__INVOICE_A__DATE___5E54FF49] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[INVOICE_ASSGROS_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__INVOICE_A__INVOI__0CC5D56F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVOICE_ASSGROS] ADD CONSTRAINT [PK__INVOICE___836F40EB0EAE1DE1] PRIMARY KEY CLUSTERED  ([INVOICE_ASSGROS_ID]) ON [PRIMARY]
GO
