CREATE TABLE [dbo].[PERIODE_SOP]
(
[PSOP_UNT_ID] [int] NOT NULL,
[PSOP_DATE] [date] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__PERIODE_S__DATE___2116E6DF] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[PERIODE_SOP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PERIODE_S__PERIO__6F8A7843] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERIODE_SOP] ADD CONSTRAINT [PK__PERIODE___6A8F5A487172C0B5] PRIMARY KEY CLUSTERED  ([PERIODE_SOP_ID]) ON [PRIMARY]
GO
