CREATE TABLE [dbo].[TRANSDET]
(
[TRANSD_ID] [int] NULL,
[TRANSD_TRANS_ID] [int] NULL,
[TRANSD_COLIER_NO] [int] NULL,
[TRANSD_PRICE] [float] NULL,
[TRANSD_DISC_PERSEN] [float] NULL,
[TRANSD_PRICE_DISC] [float] NULL,
[TRANSD_QTY] [float] NULL,
[TRANSD_TOTAL_PRICE] [float] NULL,
[TRANSD_IS_BRG_AMC] [int] NULL,
[TRANSD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSD_BRG_PPN] [float] NULL,
[TRANSD_BRG_PPNBM] [float] NULL,
[TRANSD_IS_ACTIVE] [int] NULL,
[TRANSD_IS_PJK_INCLUDE] [int] NULL,
[TRANSDET_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANSDET__TRANSD__5402595F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSDET] ADD CONSTRAINT [PK__TRANSDET__B2648B2A55EAA1D1] PRIMARY KEY CLUSTERED  ([TRANSDET_ID]) ON [PRIMARY]
GO
