CREATE TABLE [dbo].[FORM_SOP]
(
[FSOP_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FSOP_UNT_ID] [int] NOT NULL,
[FSOP_PSOP_ID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FSOP_PSOP_UNT_ID] [int] NOT NULL,
[FSOP_LOKSO_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FSOP_LOKSO_UNT_ID] [int] NOT NULL,
[FSOP_PLU_COUNT] [int] NOT NULL CONSTRAINT [DF__FORM_SOP__FSOP_P__2DB1C7EE] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__FORM_SOP__DATE_C__2EA5EC27] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[FORM_SOP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__FORM_SOP__FORM_S__31AD415B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FORM_SOP] ADD CONSTRAINT [PK__FORM_SOP__356FB284339589CD] PRIMARY KEY CLUSTERED  ([FORM_SOP_ID]) ON [PRIMARY]
GO
