CREATE TABLE [dbo].[SYS$RESULT_CODE]
(
[RES_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES_GROUP] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RES_DESC] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SYS$RESULT_CODE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$RESUL__SYS$R__55B597A7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$RESULT_CODE] ADD CONSTRAINT [PK__SYS$RESU__BF18810E579DE019] PRIMARY KEY CLUSTERED  ([SYS$RESULT_CODE_ID]) ON [PRIMARY]
GO
