CREATE TABLE [dbo].[TRANSAKSI_RETUR_NOTA]
(
[TRANSRET_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANSRET_UNT_ID] [int] NOT NULL,
[TRANSRET_TRANS_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANSRET_TRANS_UNT_ID] [int] NOT NULL,
[TRANSRET_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANSRET_DATE] [datetime] NOT NULL CONSTRAINT [DF__TRANSAKSI__TRANS__31A25463] DEFAULT (getdate()),
[TRANSRET_COUNTER_NO] [int] NULL,
[TRANSRET_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__TRANSAKSI__TRANS__3296789C] DEFAULT ((0)),
[TRANSRET_PRICE] [numeric] (21, 3) NULL,
[TRANSRET_TOTAL_PRICE] [numeric] (21, 3) NULL,
[TRANSRET_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__TRANSAKSI__DATE___338A9CD5] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TRANSRET_ISJOURNALIZED] [int] NULL,
[PPN] [float] NULL,
[TRANSRET_UOM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRANSRET_TRANSD_UNT_ID] [int] NULL,
[TRANSRET_TRANSD_ID] [int] NULL,
[TRANSRET_DISC_AMC] [float] NULL,
[TRANSAKSI_RETUR_NOTA_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANSAKSI__TRANS__394E6323] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSAKSI_RETUR_NOTA] ADD CONSTRAINT [PK__TRANSAKS__98118D423B36AB95] PRIMARY KEY CLUSTERED  ([TRANSAKSI_RETUR_NOTA_ID]) ON [PRIMARY]
GO
