CREATE TABLE [dbo].[SUPLIER_IS_PRIMARY]
(
[BRGSUP_BRG_CODE] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BRGSUP_SUP_CODE] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISPRIMARY] [int] NULL,
[SUPLIER_IS_PRIMARY_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SUPLIER_I__SUPLI__2DDCB077] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUPLIER_IS_PRIMARY] ADD CONSTRAINT [PK__SUPLIER___6AA58DA52FC4F8E9] PRIMARY KEY CLUSTERED  ([SUPLIER_IS_PRIMARY_ID]) ON [PRIMARY]
GO
