CREATE TABLE [dbo].[KUPON]
(
[KUPON_UNT_ID] [int] NOT NULL,
[KUPON_TPKUPON_ID] [int] NOT NULL,
[KUPON_TPKUPON_UNT_ID] [int] NOT NULL,
[KUPON_TRANS_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KUPON_TRANS_UNT_ID] [int] NOT NULL,
[KUPON_IS_POSTING] [int] NULL,
[KUPON_IS_CANCEL] [int] NULL,
[KUPON_NO_TRN_KASIR] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__KUPON__DATE_CREA__753864A1] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[KUPON_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__KUPON__KUPON_ID__0A3E6E7F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KUPON] ADD CONSTRAINT [PK__KUPON__62665C0C0C26B6F1] PRIMARY KEY CLUSTERED  ([KUPON_ID]) ON [PRIMARY]
GO
