CREATE TABLE [dbo].[AUT$DEF_GROUP]
(
[DG_USR_ID] [int] NOT NULL,
[DG_USR_UNT_ID] [int] NOT NULL,
[DG_GRO_ID] [int] NOT NULL,
[DG_GRO_UNT_ID] [int] NOT NULL,
[AUT$DEF_GROUP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AUT$DEF_G__AUT$D__5F740C0B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUT$DEF_GROUP] ADD CONSTRAINT [PK__AUT$DEF___9A390F73615C547D] PRIMARY KEY CLUSTERED  ([AUT$DEF_GROUP_ID]) ON [PRIMARY]
GO
