CREATE TABLE [dbo].[REF$SUB_GRUP]
(
[SUBGRUP_CODE] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SUBGRUP_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$SUB_G__DATE___3C89F72A] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[SAFETYSTOCK] [float] NULL,
[SUBGRUP_GP] [float] NOT NULL CONSTRAINT [DF_REF$SUB_GRUP_SUBGRUP_GP] DEFAULT ((0)),
[SUBGRUP_HO_AUTHORIZE] [int] NOT NULL CONSTRAINT [DF__REF$SUB_G__SUBGR__3D7E1B63] DEFAULT ((0)),
[REF$SUB_GRUP_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$SUB_G__REF$S__7948ECA7] DEFAULT (newid()),
[REF$MERCHANDISE_GRUP_ID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$SUB_GRUP] ADD CONSTRAINT [PK__REF$SUB___10820E2D7B313519] PRIMARY KEY CLUSTERED  ([REF$SUB_GRUP_ID]) ON [PRIMARY]
GO
