CREATE TABLE [dbo].[JURNAL_KOREKSI]
(
[JK_ID] [int] NULL,
[JK_TYPE_TRANSAKSI] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JK_DATE] [datetime] NULL,
[JK_ACC_NO] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JK_NAME_ACC] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JK_DEBET] [decimal] (18, 10) NULL,
[JK_CREDIT] [decimal] (18, 10) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[JK_FLAG] [int] NULL,
[JK_NO_TRANSAKSI] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JURNAL_KOREKSI_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__JURNAL_KO__JURNA__2858E14B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JURNAL_KOREKSI] ADD CONSTRAINT [PK__JURNAL_K__500872402A4129BD] PRIMARY KEY CLUSTERED  ([JURNAL_KOREKSI_ID]) ON [PRIMARY]
GO
