CREATE TABLE [dbo].[SHIPMENT_DOCUMENT_DETIL]
(
[SDD_SD_NOBUKTI] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SDD_SD_UNT_ID] [int] NOT NULL,
[SDD_MSTOK_ID] [int] NOT NULL,
[SDD_MSTOK_UNT_ID] [int] NOT NULL,
[SHIPMENT_DOCUMENT_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SHIPMENT___SHIPM__4AADF94F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SHIPMENT_DOCUMENT_DETIL] ADD CONSTRAINT [PK__SHIPMENT__D69587BE4C9641C1] PRIMARY KEY CLUSTERED  ([SHIPMENT_DOCUMENT_DETIL_ID]) ON [PRIMARY]
GO
