CREATE TABLE [dbo].[SYS$IMPORT_HISTORY]
(
[IMPH_UNT_ID] [int] NOT NULL,
[IMPH_START_TIME] [datetime] NULL,
[IMPH_FINISH_TIME] [datetime] NULL,
[IMPH_LAST_FILE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMPH_LAST_FILE_IS_DONE] [int] NOT NULL,
[IMPH_LAST_EXECUTED_RECORD_NO] [int] NULL,
[IMPH_SESSION_IS_DONE] [int] NOT NULL CONSTRAINT [DF__SYS$IMPOR__IMPH___5AD97420] DEFAULT ((0)),
[SYS$IMPORT_HISTORY_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$IMPOR__SYS$I__2F1AED73] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$IMPORT_HISTORY] ADD CONSTRAINT [PK__SYS$IMPO__0F057324310335E5] PRIMARY KEY CLUSTERED  ([SYS$IMPORT_HISTORY_ID]) ON [PRIMARY]
GO
