CREATE TABLE [dbo].[PROMO]
(
[PROM_UNT_ID] [int] NOT NULL,
[PROM_CUST_ID] [int] NOT NULL,
[PROM_CUST_UNT_ID] [int] NOT NULL,
[PROM_PRORUL_ID] [int] NULL,
[PROM_PRORUL_UNT_ID] [int] NULL,
[PROM_START_DATE] [datetime] NULL CONSTRAINT [DF__PROMO__PROM_STAR__4FD1D5C8] DEFAULT (getdate()),
[PROM_END_DATE] [datetime] NULL CONSTRAINT [DF__PROMO__PROM_END___50C5FA01] DEFAULT (getdate()),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__PROMO__DATE_CREA__51BA1E3A] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[PROM_SUP_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[PROMO_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PROMO__PROMO_ID__73C51D7B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROMO] ADD CONSTRAINT [PK__PROMO__9A7B581675AD65ED] PRIMARY KEY CLUSTERED  ([PROMO_ID]) ON [PRIMARY]
GO
