CREATE TABLE [dbo].[QUOTATION_DETAIL]
(
[QUOTATION_DETAIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__QUOTATION__QUOTA__015422C3] DEFAULT (newid()),
[QUOTATION_ID] [uniqueidentifier] NOT NULL,
[BARANG_ID] [uniqueidentifier] NOT NULL,
[BARANG_PARENT_ID] [uniqueidentifier] NOT NULL,
[REF$SATUAN_ID] [uniqueidentifier] NOT NULL,
[REF$TIPE_HARGA_ID] [uniqueidentifier] NULL,
[QUOTD_BUYPRICE] [numeric] (21, 3) NULL,
[QUOTD_PRICE] [numeric] (21, 3) NULL,
[QUOTD_MU_PERSEN] [numeric] (7, 2) NULL,
[QUOTD_MU_RUPIAH] [numeric] (7, 2) NULL,
[QUOTD_MU_RUPIAH_PLUS_PPN] [numeric] (21, 3) NULL,
[QUOTD_HARGA_AVERAGE] [float] NULL,
[QUOTD_DISC] [float] NULL,
[QUOTD_DISC_PERSEN] [float] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__QUOTATION__DATE___6991A7CB] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QUOTATION_DETAIL] ADD CONSTRAINT [PK__QUOTATIO__B2466883033C6B35] PRIMARY KEY CLUSTERED  ([QUOTATION_DETAIL_ID]) ON [PRIMARY]
GO
