CREATE TABLE [dbo].[CN_RETUR]
(
[CNRET_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CNRET_UNT_ID] [int] NOT NULL,
[CNRET_INV_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__CN_RETUR__CNRET___42E1EEFE] DEFAULT ('RET-'),
[CNRET_DATE] [datetime] NULL CONSTRAINT [DF__CN_RETUR__CNRET___43D61337] DEFAULT (getdate()),
[CNRET_TOTAL] [numeric] (21, 3) NULL,
[CNRET_PPN] [numeric] (21, 3) NULL,
[CNRET_PPNBM] [numeric] (21, 3) NULL,
[CNRET_TOTAL_TAX] [numeric] (21, 3) NULL,
[CNRET_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CN_RETUR__DATE_C__44CA3770] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CN_RETUR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CN_RETUR__CN_RET__6EB64F9B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CN_RETUR] ADD CONSTRAINT [PK__CN_RETUR__97BD0133709E980D] PRIMARY KEY CLUSTERED  ([CN_RETUR_ID]) ON [PRIMARY]
GO
