CREATE TABLE [dbo].[KABUPATEN]
(
[KAB_NAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_CREATE] [datetime] NULL,
[OP_CREATE] [int] NULL,
[OPC_UNIT] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[OPM_UNIT] [int] NULL,
[KABUPATEN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__KABUPATEN__KABUP__70698DE3] DEFAULT (newid()),
[PROPINSI_ID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KABUPATEN] ADD CONSTRAINT [PK__KABUPATE__ECB612AE7251D655] PRIMARY KEY CLUSTERED  ([KABUPATEN_ID]) ON [PRIMARY]
GO
