CREATE TABLE [dbo].[REF$KONVERSI_SATUAN]
(
[REF$KONVERSI_SATUAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$KONVE__REF$K__1F6E958F] DEFAULT (newid()),
[BARANG_ID] [uniqueidentifier] NOT NULL,
[REF$SATUAN_ID] [uniqueidentifier] NOT NULL,
[KONVSAT_SCALE] [numeric] (13, 5) NULL CONSTRAINT [DF__REF$KONVE__KONVS__16644E42] DEFAULT ((0)),
[KONVSAT_BARCODE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$KONVE__DATE___15702A09] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[KONVSAT_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KONVSAT_SAT_CODE_FROM] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KONVSAT_SAT_CODE_TO] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$KONVERSI_SATUAN] ADD CONSTRAINT [PK_REF$KONVERSI_SATUAN] PRIMARY KEY CLUSTERED  ([BARANG_ID], [REF$SATUAN_ID]) ON [PRIMARY]
GO
