CREATE TABLE [dbo].[TSOTRANSFERSQL]
(
[ID] [int] NOT NULL,
[NEWUNIT_ID] [int] NOT NULL,
[NOBUKTI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TGLBUKTI] [date] NOT NULL,
[URUTAN] [int] NOT NULL,
[STAMP] [datetime] NULL,
[TSOTRANSFERSQL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TSOTRANSF__TSOTR__76577163] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TSOTRANSFERSQL] ADD CONSTRAINT [PK__TSOTRANS__9DDFBFD1783FB9D5] PRIMARY KEY CLUSTERED  ([TSOTRANSFERSQL_ID]) ON [PRIMARY]
GO
