CREATE TABLE [dbo].[ACCOUNT_ADJUSTMENT]
(
[ACCADJ_UNT_ID] [int] NOT NULL,
[ACCADJ_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACCADJ_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCADJ_KDJUR_ID] [int] NOT NULL,
[ACCADJ_KDJUR_COMP_ID] [int] NOT NULL,
[ACCADJ_MERCHANGRUP_ID] [int] NULL,
[ACCADJ_IS_DEBET] [int] NULL,
[ACCADJ_REK_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCADJ_REK_COMP_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__ACCOUNT_A__DATE___7E6CC920] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ACCOUNT_ADJUSTMENT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ACCOUNT_A__ACCOU__4BEC364B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNT_ADJUSTMENT] ADD CONSTRAINT [PK__ACCOUNT___2CDA2B764DD47EBD] PRIMARY KEY CLUSTERED  ([ACCOUNT_ADJUSTMENT_ID]) ON [PRIMARY]
GO
