CREATE TABLE [dbo].[AMORTISASI_TRANSAKSI]
(
[AMORTR_COMP_ID] [int] NOT NULL,
[AMORTR_AMOR_ID] [int] NOT NULL,
[AMORTR_AMOR_COMP_ID] [int] NOT NULL,
[AMORTR_DATE] [datetime] NULL CONSTRAINT [DF__AMORTISAS__AMORT__36B12243] DEFAULT (getdate()),
[AMORTR_VALUE] [numeric] (21, 3) NULL,
[AMORTR_AGE] [int] NULL CONSTRAINT [DF__AMORTISAS__AMORT__37A5467C] DEFAULT ((1)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__AMORTISAS__DATE___38996AB5] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[AMORTISASI_TRANSAKSI_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AMORTISAS__AMORT__11757BF3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AMORTISASI_TRANSAKSI] ADD CONSTRAINT [PK__AMORTISA__CE1C1088135DC465] PRIMARY KEY CLUSTERED  ([AMORTISASI_TRANSAKSI_ID]) ON [PRIMARY]
GO
