CREATE TABLE [dbo].[REF$TIPE_PRODUK]
(
[TPPRO_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TPPRO_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TPPRO_OWNER] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__REF$TIPE___TPPRO__5832119F] DEFAULT (' ''MARKETING'''),
[TPPRO_REK_DEBET] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPPRO_REK_DEBET_COMP_ID] [int] NULL,
[TPPRO_REK_CREDIT] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPPRO_REK_CREDIT_COMP_ID] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$TIPE___DATE___592635D8] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$TIPE_PRODUK_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$TIPE___REF$T__56F3D4A3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_PRODUK] ADD CONSTRAINT [PK__REF$TIPE__9D06917958DC1D15] PRIMARY KEY CLUSTERED  ([REF$TIPE_PRODUK_ID]) ON [PRIMARY]
GO
