CREATE TABLE [dbo].[MEMBER_ACTIVASI]
(
[MEMBERACT_ID] [int] NOT NULL,
[MEMBERACT_UNT_ID] [int] NOT NULL,
[MEMBERACT_MEMBER_ID] [int] NOT NULL,
[MEMBERACT_MEMBER_UNT_ID] [int] NOT NULL,
[MEMBERACT_IS_ACTIVASI] [int] NULL,
[MEMBERACT_IS_REACTIVASI] [int] NULL,
[MEMBERACT_VALID_DATE_FROM] [date] NULL CONSTRAINT [DF__MEMBER_AC__MEMBE__7CD98669] DEFAULT (getdate()),
[MEMBERACT_VALID_DATE_TO] [date] NULL,
[MEMBERACT_IS_PRINT_CARD] [int] NULL,
[MEMBERACT_FEE_ACTIVASI] [numeric] (21, 3) NULL,
[MEMBERACT_FEE_REACTIVASI] [numeric] (21, 3) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__MEMBER_AC__DATE___7DCDAAA2] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[MEMBER_ACTIVASI_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__MEMBER_AC__MEMBE__6C8E1007] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEMBER_ACTIVASI] ADD CONSTRAINT [PK__MEMBER_A__5E3F407C6E765879] PRIMARY KEY CLUSTERED  ([MEMBER_ACTIVASI_ID]) ON [PRIMARY]
GO
