CREATE TABLE [dbo].[CLAIM_CONTRABON]
(
[CLMCONT_NO] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CLMCONT_UNT_ID] [int] NOT NULL,
[CLMCONT_DATE] [datetime] NULL,
[CLMCONT_DUE_DATE] [datetime] NULL,
[CLMCONT_RETURN_DATE] [datetime] NULL,
[CLMCONT_TOTAL_AMOUNT] [numeric] (21, 3) NULL,
[CLMCONT_IS_CONTRABON] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CLAIM_CON__DATE___245D67DE] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CLMCONT_SUP_CODE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLMCONT_MG_ID] [int] NULL,
[CLMCONT_IS_PAID] [int] NULL CONSTRAINT [DF__CLAIM_CON__CLMCO__25518C17] DEFAULT ((0)),
[CLAIM_CONTRABON_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CLAIM_CON__CLAIM__1AC9DC03] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLAIM_CONTRABON] ADD CONSTRAINT [PK__CLAIM_CO__17A789F01CB22475] PRIMARY KEY CLUSTERED  ([CLAIM_CONTRABON_ID]) ON [PRIMARY]
GO
