CREATE TABLE [dbo].[WASTAGE_DETIL]
(
[BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HARGA] [float] NOT NULL,
[HEADERUNIT_ID] [int] NOT NULL,
[HEADER_NO] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NEWUNIT_ID] [int] NOT NULL,
[PPNBM_NOMINAL] [float] NULL,
[PPNBM_PERSEN] [float] NULL,
[PPN_NOMINAL] [float] NULL,
[PPN_PERSEN] [float] NULL,
[QTY] [float] NULL,
[SATUAN] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SATUANUNIT_ID] [int] NULL,
[TOTAL] [float] NULL,
[WASTAGE_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__WASTAGE_D__WASTA__3508D0F3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WASTAGE_DETIL] ADD CONSTRAINT [PK__WASTAGE___4591A45236F11965] PRIMARY KEY CLUSTERED  ([WASTAGE_DETIL_ID]) ON [PRIMARY]
GO
