CREATE TABLE [dbo].[CN_DAMAGE]
(
[CNDMG_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CNDMG_UNT_ID] [int] NOT NULL,
[CNDMG_INV_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__CN_DAMAGE__CNDMG__339FAB6E] DEFAULT ('DMG-'),
[CNDMG_DATE] [datetime] NULL CONSTRAINT [DF__CN_DAMAGE__CNDMG__3493CFA7] DEFAULT (getdate()),
[CNDMG_TOTAL] [numeric] (21, 3) NULL,
[CNDMG_PPN] [numeric] (21, 3) NULL,
[CNDMG_PPNBM] [numeric] (21, 3) NULL,
[CNDMG_TOTAL_TAX] [numeric] (21, 3) NULL,
[CNDMG_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CNDMG_IS_JURNAL] [int] NULL,
[CNDMG_IS_POTONG_TAGIHAN] [int] NOT NULL CONSTRAINT [DF__CN_DAMAGE__CNDMG__3587F3E0] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__CN_DAMAGE__DATE___367C1819] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[CN_DAMAGE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CN_DAMAGE__CN_DA__44C015CF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CN_DAMAGE] ADD CONSTRAINT [PK__CN_DAMAG__E6F7090646A85E41] PRIMARY KEY CLUSTERED  ([CN_DAMAGE_ID]) ON [PRIMARY]
GO
