CREATE TABLE [dbo].[TEMP$BALANCE_SHEET_REPORT_GENERATOR]
(
[LINE_NO] [int] NOT NULL,
[DESCRIPTION_AKTIVA] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REK_CODE_AKTIVA] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION_PASSIVA] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REK_CODE_PASSIVA] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEMP$BALANCE_SHEET_REPORT_GENERATOR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TEMP$BALA__TEMP$__12BEA5E7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMP$BALANCE_SHEET_REPORT_GENERATOR] ADD CONSTRAINT [PK__TEMP$BAL__67672FAD14A6EE59] PRIMARY KEY CLUSTERED  ([TEMP$BALANCE_SHEET_REPORT_GENERATOR_ID]) ON [PRIMARY]
GO
