CREATE TABLE [dbo].[PAYMENT_CLAIM_TRANSFER_DETIL]
(
[PAYCTD_COMP_ID] [int] NOT NULL,
[PAYCTD_PAYCT_ID] [int] NULL,
[PAYCTD_PAYCT_COMP_ID] [int] NULL,
[GIRONUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMOUNT] [float] NULL,
[DUEDATE] [datetime] NULL,
[PAYCTD_PAYCF_NO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYCTD_PAYCFD_ID] [int] NULL,
[PAYCTD_PAYCFD_UNT_ID] [int] NULL,
[PAYMENT_CLAIM_TRANSFER_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PAYMENT_C__PAYME__32EB7E57] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYMENT_CLAIM_TRANSFER_DETIL] ADD CONSTRAINT [PK__PAYMENT___EF8BC28234D3C6C9] PRIMARY KEY CLUSTERED  ([PAYMENT_CLAIM_TRANSFER_DETIL_ID]) ON [PRIMARY]
GO
