CREATE TABLE [dbo].[KOMPETITOR_BARANG]
(
[KOMPTBRG_KOMPT_ID] [int] NOT NULL,
[KOMPTBRG_KOMPT_UNT_ID] [int] NOT NULL,
[KOMPTBRG_TANGGAL] [datetime] NULL CONSTRAINT [DF__KOMPETITO__KOMPT__6E8B6712] DEFAULT (getdate()),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__KOMPETITO__DATE___6F7F8B4B] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[KOMPETITOR_BARANG_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__KOMPETITO__KOMPE__11DF9047] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KOMPETITOR_BARANG] ADD CONSTRAINT [PK__KOMPETIT__3EBE72CB13C7D8B9] PRIMARY KEY CLUSTERED  ([KOMPETITOR_BARANG_ID]) ON [PRIMARY]
GO
