CREATE TABLE [dbo].[TLOGEXIMMDB]
(
[LOG_DATE] [datetime] NOT NULL,
[LOG_DATEBYUSER] [datetime] NOT NULL,
[LOG_UNIT] [int] NOT NULL,
[LOG_POSCODE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOG_ISEXPORT] [int] NOT NULL,
[TLOGEXIMMDB_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TLOGEXIMM__TLOGE__6D031153] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TLOGEXIMMDB] ADD CONSTRAINT [PK__TLOGEXIM__59CA71546EEB59C5] PRIMARY KEY CLUSTERED  ([TLOGEXIMMDB_ID]) ON [PRIMARY]
GO
