CREATE TABLE [dbo].[TKETERANGAN]
(
[TABEL] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOLOM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KETERANGAN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TKETERANGAN_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TKETERANG__TKETE__61915EA7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TKETERANGAN] ADD CONSTRAINT [PK__TKETERAN__854B02D56379A719] PRIMARY KEY CLUSTERED  ([TKETERANGAN_ID]) ON [PRIMARY]
GO
