CREATE TABLE [dbo].[REF$GRUP_JURNAL]
(
[GROJUR_CODE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GROJUR_COMP_ID] [int] NOT NULL,
[GROJUR_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROJUR_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$GRUP___DATE___062DE679] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_COMP] [int] NULL,
[OPM_COMP] [int] NULL,
[REF$GRUP_JURNAL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$GRUP___REF$G__379B24DB] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$GRUP_JURNAL] ADD CONSTRAINT [PK__REF$GRUP__18EE200339836D4D] PRIMARY KEY CLUSTERED  ([REF$GRUP_JURNAL_ID]) ON [PRIMARY]
GO
