CREATE TABLE [dbo].[ADJUSTMENT_BARANG_TURUNAN_DETIL]
(
[ABTD_UNT_ID] [int] NOT NULL,
[ABTD_ADJBRGTUR_ID] [int] NULL,
[ABTD_ADJBRGTUR_UNT_ID] [int] NULL,
[ABTD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABTD_BRG_CODE_MASTER] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABTD_BRG_MST_UNT_ID] [int] NULL,
[ABTD_HPP_BRG_TURUNAN_LAMA] [numeric] (21, 3) NULL,
[ABTD_HPP_BRG_MASTER_LAMA] [numeric] (21, 3) NULL,
[ABTD_QTY] [numeric] (18, 3) NULL,
[ABTD_WASTAGE] [int] NULL,
[ABTD_QTY_PER_UOM_BRG_TURUNAN] [numeric] (18, 3) NULL,
[ABTD_IS_TURUNAN] [int] NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL,
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ADJUSTMENT_BARANG_TURUNAN_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ADJUSTMEN__ADJUS__2B4A5C8F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADJUSTMENT_BARANG_TURUNAN_DETIL] ADD CONSTRAINT [PK__ADJUSTME__0E0B21B52D32A501] PRIMARY KEY CLUSTERED  ([ADJUSTMENT_BARANG_TURUNAN_DETIL_ID]) ON [PRIMARY]
GO
