CREATE TABLE [dbo].[REF$SATUAN_NBD]
(
[SATNBD_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SATNBD_UNT_ID] [int] NOT NULL,
[SATNBD_NAME] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SATNBD_GROUP] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__REF$SATUA__SATNB__34E8D562] DEFAULT (' ''SERVICE'''),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$SATUA__DATE___35DCF99B] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$SATUAN_NBD_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$SATUA__REF$S__5031C87B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$SATUAN_NBD] ADD CONSTRAINT [PK__REF$SATU__3D031333521A10ED] PRIMARY KEY CLUSTERED  ([REF$SATUAN_NBD_ID]) ON [PRIMARY]
GO
