CREATE TABLE [dbo].[REF$LOKASI_STOCK_OPNAM]
(
[LOKSO_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOKSO_UNT_ID] [int] NOT NULL,
[LOKSO_RACK] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOKSO_BAY_FROM] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOKSO_BAY_TO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOKSO_SHELVE_FROM] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOKSO_SHELVE_TO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOKSO_POSITION] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOKSO_NAME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOKSO_TYPE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOKSO_IS_ACTIVE] [int] NULL,
[LOKSO_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$LOKAS__DATE___1E05700A] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[LOKSO_TSOP_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOKSO_TSOP_UNT_ID] [int] NOT NULL,
[REF$LOKASI_STOCK_OPNAM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$LOKAS__REF$L__0F582957] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$LOKASI_STOCK_OPNAM] ADD CONSTRAINT [PK__REF$LOKA__CD717489114071C9] PRIMARY KEY CLUSTERED  ([REF$LOKASI_STOCK_OPNAM_ID]) ON [PRIMARY]
GO
