CREATE TABLE [dbo].[PO_ASSGROS]
(
[POAS_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[POAS_UNT_ID] [int] NOT NULL,
[POAS_DATE] [datetime] NULL CONSTRAINT [DF__PO_ASSGRO__POAS___37FA4C37] DEFAULT (getdate()),
[POAS_TRD_ID] [int] NOT NULL,
[POAS_TRD_UNT_ID] [int] NOT NULL,
[POAS_LEAD_TIME] [int] NULL CONSTRAINT [DF__PO_ASSGRO__POAS___38EE7070] DEFAULT ((0)),
[POAS_TOP] [int] NULL CONSTRAINT [DF__PO_ASSGRO__POAS___39E294A9] DEFAULT ((0)),
[POAS_SUBTOTAL] [numeric] (21, 3) NULL,
[POAS_DISC] [numeric] (21, 3) NULL,
[POAS_PPN] [numeric] (21, 3) NULL,
[POAS_PPNBM] [numeric] (21, 3) NULL,
[POAS_DISC_MEMBER] [numeric] (21, 3) NULL,
[POAS_TOTAL] [numeric] (21, 3) NULL,
[POAS_DELIVER_DATE] [datetime] NULL,
[POAS_VALID_DATE] [datetime] NULL,
[POAS_DESCRIPTION] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POAS_STATUS] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__PO_ASSGRO__DATE___3AD6B8E2] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[TPHRG_ID] [int] NULL,
[TPHRG_UNT_ID] [int] NULL,
[PO_ASSGROS_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PO_ASSGRO__PO_AS__57D2EA43] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PO_ASSGROS] ADD CONSTRAINT [PK__PO_ASSGR__5CF02D0859BB32B5] PRIMARY KEY CLUSTERED  ([PO_ASSGROS_ID]) ON [PRIMARY]
GO
