CREATE TABLE [dbo].[PO_BONUS]
(
[POB_UNT_ID] [int] NOT NULL,
[POB_POD_ID] [int] NOT NULL,
[POB_POD_UNT_ID] [int] NOT NULL,
[POB_BNS_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[POB_QTY_CS] [numeric] (18, 3) NULL CONSTRAINT [DF__PO_BONUS__POB_QT__3F9B6DFF] DEFAULT ((0)),
[POB_QTY_SALES] [numeric] (18, 3) NULL CONSTRAINT [DF__PO_BONUS__POB_QT__408F9238] DEFAULT ((0)),
[POB_QTY] [numeric] (18, 3) NULL CONSTRAINT [DF__PO_BONUS__POB_QT__4183B671] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__PO_BONUS__DATE_C__4277DAAA] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[PO_BONUS_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__PO_BONUS__PO_BON__604834B3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PO_BONUS] ADD CONSTRAINT [PK__PO_BONUS__1A33703A62307D25] PRIMARY KEY CLUSTERED  ([PO_BONUS_ID]) ON [PRIMARY]
GO
