CREATE TABLE [dbo].[INVOICE_PAYMENT]
(
[INVPAY_UNT_ID] [int] NOT NULL,
[INVPAY_CUST_ID] [int] NOT NULL,
[INVPAY_CUST_UNT_ID] [int] NOT NULL,
[INVPAY_AGRJDWL_ID] [int] NOT NULL,
[INVPAY_AGRJDWL_UNT_ID] [int] NOT NULL,
[INVPAY_NO_VOUCHER_JURNAL] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVPAY_RECEIPT_DATE] [datetime] NULL,
[INVPAY_RECEIPT_FROM] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVPAY_DESCRIPTION] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVPAY_KDJUR_ID] [int] NOT NULL,
[INVPAY_KDJUR_COMP_ID] [int] NOT NULL,
[INVPAY_PPH23] [numeric] (21, 3) NULL,
[INVPAY_TOTAL_PAYMENT] [numeric] (21, 3) NULL,
[INVPAY_TPBYR_ID] [int] NOT NULL,
[INVPAY_TPBYR_UNT_ID] [int] NOT NULL,
[INVPAY_ACC_NO] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVPAY_NO_DOCUMENT] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVPAY_DUE_DATE] [datetime] NULL,
[INVPAY_AMOUNT] [numeric] (21, 3) NULL,
[INVPAY_STAPRO_ID] [int] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__INVOICE_P__DATE___603D47BB] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[INVOICE_PAYMENT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__INVOICE_P__INVOI__28C2F59F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVOICE_PAYMENT] ADD CONSTRAINT [PK__INVOICE___42D9C6EE2AAB3E11] PRIMARY KEY CLUSTERED  ([INVOICE_PAYMENT_ID]) ON [PRIMARY]
GO
