CREATE TABLE [dbo].[REF$TIPE_MEMBER]
(
[TPMEMBER_NAME] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPMEMBER_BEGIN_VALUE] [numeric] (21, 3) NULL,
[TPMEMBER_END_VALUE] [numeric] (21, 3) NULL,
[TPMEMBER_DISCOUNT] [numeric] (7, 2) NULL,
[TPMEMBER_FEE_ACTIVASI] [numeric] (21, 3) NULL,
[TPMEMBER_FEE_REACTIVASI] [numeric] (21, 3) NULL,
[TPMEMBER_IS_ACTIVE] [int] NULL,
[TPMEMBER_IS_MASTER] [int] NULL,
[TPMEMBER_REF_ID] [int] NULL CONSTRAINT [DF__REF$TIPE___TPMEM__4BCC3ABA] DEFAULT ((0)),
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$TIPE___DATE___4CC05EF3] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[REF$TIPE_MEMBER_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$TIPE___REF$T__6265874F] DEFAULT (newid()),
[IS_POIN] [smallint] NOT NULL CONSTRAINT [DF__REF$TIPE___IS_PO__74F938D6] DEFAULT ((0)),
[IS_UNDIAN] [smallint] NOT NULL CONSTRAINT [DF__REF$TIPE___IS_UN__75ED5D0F] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_MEMBER] ADD CONSTRAINT [PK__REF$TIPE__E469D917644DCFC1] PRIMARY KEY CLUSTERED  ([REF$TIPE_MEMBER_ID]) ON [PRIMARY]
GO
