CREATE TABLE [dbo].[KOMPETITOR_BARANG_DETIL]
(
[KBD_UNT_ID] [int] NOT NULL,
[KBD_KOMPTBRG_ID] [int] NOT NULL,
[KBD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KBD_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KBD_SELL_PRICE] [numeric] (21, 3) NULL,
[KBD_DISC_PERSEN] [numeric] (7, 2) NULL,
[KBD_DISC_NOMINAL] [numeric] (21, 3) NULL,
[KBD_SELL_PRICE_DISC] [numeric] (21, 3) NULL,
[KBD_CONVERS] [numeric] (7, 2) NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__KOMPETITO__DATE___7167D3BD] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[KOMPETITOR_BARANG_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__KOMPETITO__KOMPE__0E0EFF63] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KOMPETITOR_BARANG_DETIL] ADD CONSTRAINT [PK__KOMPETIT__F09CDF810FF747D5] PRIMARY KEY CLUSTERED  ([KOMPETITOR_BARANG_DETIL_ID]) ON [PRIMARY]
GO
