CREATE TABLE [dbo].[SYS$EXPORT_IMPORT_EVENT]
(
[EXIM_TYPE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EXIM_ACTION] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EXIM_TIME] [datetime] NULL CONSTRAINT [DF__SYS$EXPOR__EXIM___58F12BAE] DEFAULT (getdate()),
[EXIM_USR_ID] [int] NULL,
[EXIM_USR_UNT_ID] [int] NULL,
[EXIM_IP_ADDRESS] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXIM_MESSAGE] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXIM_COMP_INFO] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS$EXPORT_IMPORT_EVENT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__SYS$EXPOR__SYS$E__08F5448B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS$EXPORT_IMPORT_EVENT] ADD CONSTRAINT [PK__SYS$EXPO__E9DD1C770ADD8CFD] PRIMARY KEY CLUSTERED  ([SYS$EXPORT_IMPORT_EVENT_ID]) ON [PRIMARY]
GO
