CREATE TABLE [dbo].[HISTORY_SELLING_PRICE]
(
[SPH_UNT_ID] [int] NOT NULL,
[SPH_DATE] [datetime] NULL CONSTRAINT [DF__HISTORY_S__SPH_D__4D2A7347] DEFAULT (getdate()),
[SPH_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPH_SAT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPH_TPHRG_ID] [int] NOT NULL,
[SPH_TPHRG_UNT_ID] [int] NOT NULL,
[SPH_SELL_PRICE_OLD] [numeric] (21, 3) NULL,
[SPH_DISC_PERSEN_OLD] [numeric] (7, 2) NULL,
[SPH_DISC_NOMINAL_OLD] [numeric] (21, 3) NULL,
[SPH_SELL_PRICE_DISC_OLD] [numeric] (21, 3) NULL,
[SPH_MARK_UP_OLD] [numeric] (7, 2) NULL,
[SPH_SELL_PRICE_NEW] [numeric] (21, 3) NULL,
[SPH_DISC_PERSEN_NEW] [numeric] (7, 2) NULL,
[SPH_DISC_NOMINAL_NEW] [numeric] (21, 3) NULL,
[SPH_SELL_PRICE_DISC_NEW] [numeric] (21, 3) NULL,
[SPH_MARK_UP_NEW] [numeric] (7, 2) NULL,
[SPH_REMARK_NEW] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__HISTORY_S__DATE___4E1E9780] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[HISTORY_SELLING_PRICE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__HISTORY_S__HISTO__2EB0D91F] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HISTORY_SELLING_PRICE] ADD CONSTRAINT [PK__HISTORY___E57756B830992191] PRIMARY KEY CLUSTERED  ([HISTORY_SELLING_PRICE_ID]) ON [PRIMARY]
GO
