CREATE TABLE [dbo].[VENDOR]
(
[VDR_NO] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VDR_NAME] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VDR_ADDRESS1] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_ADDRESS2] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_PHONE1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_FAX] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_CITY] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_ZIP] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_COUNTRY] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_CONTACT_NAME1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_CONTACT_TITLE1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_CONTACT_PHONE1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_CONTACT_NAME2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_CONTACT_TITLE2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VDR_CONTACT_PHONE2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_CREATE] [datetime] NULL,
[DATE_MODIFY] [datetime] NULL,
[VDR_GRP_NO] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VDR_PHONE2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENDOR_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__VENDOR__VENDOR_I__2F8FEEBF] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENDOR] ADD CONSTRAINT [PK__VENDOR__418E3C8A31783731] PRIMARY KEY CLUSTERED  ([VENDOR_ID]) ON [PRIMARY]
GO
