CREATE TABLE [dbo].[ELECTRIC_PAYMENT]
(
[ELPAY_UNT_ID] [int] NOT NULL,
[ELPAY_ELINV_ID] [int] NOT NULL,
[ELPAY_ELINV_UNT_ID] [int] NOT NULL,
[ELPAY_DATE] [date] NULL,
[ELPAY_DOCUMENT_NO] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ELPAY_KDJUR_ID] [int] NOT NULL,
[ELPAY_KDJUR_COMP_ID] [int] NOT NULL,
[ELPAY_AMOUNT_PAYMENT] [numeric] (21, 3) NULL,
[ELPAY_DESCRIPTION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ELPAY_REK_CODE_BANK] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELPAY_REK_COMP_BANK_ID] [int] NOT NULL,
[ELPAY_REK_CODE_ELECTRIC] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELPAY_REK_COMP_ELECTRIC_ID] [int] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__ELECTRIC___DATE___19AACF41] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ELECTRIC_PAYMENT_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ELECTRIC___ELECT__699C94C3] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELECTRIC_PAYMENT] ADD CONSTRAINT [PK__ELECTRIC__8A18913D6B84DD35] PRIMARY KEY CLUSTERED  ([ELECTRIC_PAYMENT_ID]) ON [PRIMARY]
GO
