CREATE TABLE [dbo].[REF$TIPE_BARANG]
(
[TPBRG_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TPBRG_NAME] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__REF$TIPE___DATE___3F6663D5] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ISPATRACONTRABON] [int] NULL,
[REF$TIPE_BARANG_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__REF$TIPE_BAR__ID__438BFA74] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_BARANG] ADD CONSTRAINT [PK__REF$TIPE__3214EC27457442E6] PRIMARY KEY CLUSTERED  ([REF$TIPE_BARANG_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REF$TIPE_BARANG] ADD CONSTRAINT [UNIQUE_TPBRG_CODE] UNIQUE NONCLUSTERED  ([TPBRG_CODE]) ON [PRIMARY]
GO
