CREATE TABLE [dbo].[ELECTRIC_INVOICE]
(
[ELINV_UNT_ID] [int] NOT NULL,
[ELINV_NUMBER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELINV_PERIOD] [date] NULL,
[ELINV_DUE_DATE] [date] NULL,
[ELINV_ELECTR_ID] [int] NOT NULL,
[ELINV_ELECTR_UNT_ID] [int] NOT NULL,
[ELINV_GROUP] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ELINV_POWER] [numeric] (17, 2) NULL,
[ELINV_FACTOR] [real] NULL,
[ELINV_COST_SAT_ABODEMEN] [numeric] (21, 3) NULL,
[ELINV_COST_SAT_USE] [numeric] (21, 3) NULL,
[ELINV_ELECTRIC_USE] [numeric] (17, 2) NULL,
[ELINV_COST_ABODEMEN] [numeric] (21, 3) NULL,
[ELINV_COST_USE] [numeric] (21, 3) NULL,
[ELINV_TTBL] [numeric] (21, 3) NULL,
[ELINV_PJU] [numeric] (21, 3) NULL,
[ELINV_IS_PRINT] [int] NULL,
[ELINV_IS_PAYMENT] [int] NULL,
[ELINV_ELCUST_ID] [int] NOT NULL,
[ELINV_ELCUST_UNT_ID] [int] NOT NULL,
[OP_CREATE] [int] NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__ELECTRIC___DATE___17C286CF] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[ELECTRIC_INVOICE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ELECTRIC___ELECT__6D6D25A7] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELECTRIC_INVOICE] ADD CONSTRAINT [PK__ELECTRIC__0F05F9EF6F556E19] PRIMARY KEY CLUSTERED  ([ELECTRIC_INVOICE_ID]) ON [PRIMARY]
GO
