CREATE TABLE [dbo].[AUT$MENU_STRUCTURE]
(
[MENUS_UNT_ID] [int] NOT NULL,
[MENUS_NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MENUS_CAPTION] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MENUS_MOD_ID] [int] NULL,
[MENUS_MOD_UNT_ID] [int] NULL,
[MENUS_PARENT_MENU_ID] [int] NULL,
[MENUS_PARENT_UNT_ID] [int] NULL,
[MENUS_NO] [int] NULL CONSTRAINT [DF__AUT$MENU___MENUS__440B1D61] DEFAULT ((0)),
[AUT$MENU_STRUCTURE_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__AUT$MENU___AUT$M__02333863] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUT$MENU_STRUCTURE] ADD CONSTRAINT [PK__AUT$MENU__24697993041B80D5] PRIMARY KEY CLUSTERED  ([AUT$MENU_STRUCTURE_ID]) ON [PRIMARY]
GO
