CREATE TABLE [dbo].[CCUOM]
(
[CCUOM_SAT_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CCUOM_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__CCUOM__CCUOM_ID__1328BA3B] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCUOM] ADD CONSTRAINT [PK__CCUOM__6328C966151102AD] PRIMARY KEY CLUSTERED  ([CCUOM_ID]) ON [PRIMARY]
GO
