CREATE TABLE [dbo].[RETUR_DETIL]
(
[RETD_ID] [int] NOT NULL,
[RETD_UNT_ID] [int] NOT NULL,
[RETD_BRG_CODE] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RETD_SAT_CODE] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_CREATE] [datetime] NULL CONSTRAINT [DF__RETUR_DET__DATE___70FDBF69] DEFAULT (getdate()),
[OP_MODIFY] [int] NULL,
[DATE_MODIFY] [datetime] NULL,
[OPC_UNIT] [int] NULL,
[OPM_UNIT] [int] NULL,
[RETD_POD_ID] [int] NULL,
[RETD_POD_UNT_ID] [int] NULL,
[RETD_RET_ID] [int] NOT NULL,
[RETD_RET_UNT_ID] [int] NULL,
[RETD_POD_QTY_ORDER] [float] NULL,
[RETD_POD_PRICE] [float] NULL,
[RETD_POD_PPN_PERSEN] [float] NULL,
[RETD_POD_PPNBM_PERSEN] [float] NULL,
[RETD_POD_PO_NO] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETUR_DETIL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__RETUR_DET__RETUR__7FABD173] DEFAULT (newid())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RETUR_DETIL] ADD CONSTRAINT [PK__RETUR_DE__ACE5FD2C019419E5] PRIMARY KEY CLUSTERED  ([RETUR_DETIL_ID]) ON [PRIMARY]
GO
