program POSOne;

uses
  Forms,
  ufrmMain in 'ufrmMain.pas' {frmMain},
  uConstanta in 'source\module\main\unit\uConstanta.pas',
  uGTEncDec in 'source\lib\uGTEncDec.pas',
  uGTINIFile in 'source\lib\uGTINIFile.pas',
  uGTSUICommonDlg in 'source\lib\uGTSUICommonDlg.pas',
  uDM in 'source\module\main\ui\UDM.PAS' {DM},
  ufrmTransaksi in 'source\module\main\ui\ufrmTransaksi.pas' {frmTransaksi},
  uNewBarang in '..\classes\uNewBarang.PAS',
  udmReport in 'source\module\main\ui\udmReport.pas' {dmReport: TDataModule},
  uNewBarangHargaJual in '..\classes\uNewBarangHargaJual.PAS',
  ufrmPayment in 'source\module\main\ui\ufrmPayment.pas' {frmPayment},
  ufraLookupBarang in 'source\module\main\ui\ufraLookupBarang.pas' {fraLookupBarang: TFrame},
  ufrmTransaksiPending in 'source\module\main\ui\ufrmTransaksiPending.pas' {frmTransaksiPending},
  ufraMember in 'source\module\main\ui\ufraMember.pas' {fraMember: TFrame},
  ufraLookUpCC in 'source\module\main\ui\ufraLookUpCC.pas' {fraLookUpCC: TFrame},
  uPosTransaction in '..\classes\uPosTransaction.pas',
  uBarangTransaksi in '..\classes\uBarangTransaksi.pas',
  uVoucherLain in '..\classes\uVoucherLain.pas',
  uPOSTransactionCard in '..\classes\uPOSTransactionCard.pas',
  ufrmTransaksiKring in 'source\module\main\ui\ufrmTransaksiKring.pas' {frmTransaksiKring},
  uDOAssgros in '..\classes\uDOAssgros.pas',
  ufrmPaymentKring in 'source\module\main\ui\ufrmPaymentKring.pas' {frmPaymentKring},
  ufraDOKring in 'source\module\main\ui\ufraDOKring.pas' {fraDOKring: TFrame},
  ufrmLogin in 'source\module\main\ui\ufrmLogin.pas' {frmLogin},
  ufrmLookupBarang in 'source\module\main\ui\ufrmLookupBarang.pas' {frmLookupBarang},
  uDiscountMember in '..\Classes\uDiscountMember.pas',
  uRMSSubClass in '..\Classes\uRMSSubClass.pas',
  uRMSUnit in '..\system\uRMSUnit.pas',
  ufrmMaster in '..\system\ufrmMaster.pas' {frmMaster},
  uExportOfflinePOS in '..\store\module\eximofflinepos\uExportOfflinePOS.pas',
  ufraFooterDialog2Button in '..\system\ufraFooterDialog2Button.pas' {fraFooterDialog2Button: TFrame},
  ufrmMasterDialog in '..\system\ufrmMasterDialog.pas' {frmMasterDialog},
  ufrmPosDownlink in 'source\module\main\ui\ufrmPosDownlink.pas' {frmPosDownlink},
  uConn in 'source\module\lib\uConn.pas',
  ufrmImportFromStore in 'source\module\main\ui\ufrmImportFromStore.pas' {frmImportFromStore},
  ufrmExportOfflinePOS in 'source\module\main\ui\ufrmExportOfflinePOS.pas' {frmExportOfflinePOS},
  udmMain in 'source\module\main\ui\udmMain.pas' {dmMain: TDataModule},
  uConnectionGuardian in 'source\module\lib\uConnectionGuardian.pas',
  uSpell in 'source\module\lib\uSpell.pas',
  uConnection in '..\system\uConnection.pas',
  ufrmProductForSelling in '..\store\module\cashier_supv\ui\ufrmProductForSelling.pas' {frmProductForSelling},
  uProductForSelling in '..\store\module\cashier_supv\unit\cls\uProductForSelling.pas',
  uFormProperty in '..\Classes\uFormProperty.pas',
  ufrmMaintenancePassword in '..\store\module\cashier_supv\ui\ufrmMaintenancePassword.pas' {frmMaintenancePassword},
  uMaintenancePasswd in '..\store\module\cashier_supv\unit\cls\uMaintenancePasswd.pas',
  ufrmDialogMaintenancePassword in '..\store\module\cashier_supv\ui\ufrmDialogMaintenancePassword.pas' {frmDialogMaintenancePassword},
  uSQLProductForSelling in '..\store\module\cashier_supv\unit\sql\uSQLProductForSelling.pas',
  uSQLMAINTENANCEPASSWD in '..\store\module\cashier_supv\unit\sql\uSQLMaintenancePasswd.pas',
  ufrmActivatePOS in '..\store\module\cashier_supv\ui\ufrmActivatePOS.pas' {frmActivatePOS},
  ufrmDialogActivatePOS in '..\store\module\cashier_supv\ui\ufrmDialogActivatePOS.pas' {frmDialogActivePOS},
  uActivatePOS in '..\store\module\cashier_supv\unit\cls\uActivatePOS.pas',
  uSQLACTIVATEPOS in '..\store\module\cashier_supv\unit\sql\uSQLActivatePOS.pas',
  ufrmBeginningBalancePOS in '..\store\module\cashier_supv\ui\ufrmBeginningBalancePOS.pas' {frmBeginningBalancePOS},
  ufrmDialogBeginningBalancePOS in '..\store\module\cashier_supv\ui\ufrmDialogBeginningBalancePOS.pas' {frmDialogBeginBalancePOS},
  uBeginningBalancePOS in '..\store\module\cashier_supv\unit\cls\uBeginningBalancePOS.pas',
  uSQLBEGINNINGBALANCEPOS in '..\store\module\cashier_supv\unit\sql\uSQLBeginningBalancePOS.pas',
  ufrmAdjustmentCashback in '..\store\module\cashier_supv\ui\ufrmAdjustmentCashback.pas' {frmAdjustmentCashback},
  ufrmDialogAdjustmentCashback in '..\store\module\cashier_supv\ui\ufrmDialogAdjustmentCashback.pas' {frmDialogAdjustmentCashback},
  uTransact in '..\store\module\cashier_supv\unit\cls\uTransact.pas',
  uSQLTransact in '..\store\module\cashier_supv\unit\sql\uSQLTransact.pas',
  uAdjustCashback in '..\store\module\cashier_supv\unit\cls\uAdjustCashback.pas',
  uSQLAdjustCashback in '..\store\module\cashier_supv\unit\sql\uSQLAdjustCashback.pas',
  ufrmCashDropping in '..\store\module\cashier_supv\ui\ufrmCashDropping.pas' {frmCashDropping},
  ufrmCreditCard in '..\store\module\cashier_supv\ui\ufrmCreditCard.pas' {frmCreditCard},
  ufrmDisplayCCAndCashback in '..\store\module\cashier_supv\ui\ufrmDisplayCCAndCashback.pas' {frmDisplayCCAndCashback},
  ufrmDisplayLastTransactionNo in '..\store\module\cashier_supv\ui\ufrmDisplayLastTransactionNo.pas' {frmDisplayLastTransactionNo},
  ufrmDisplayPOSMonitor in '..\store\module\cashier_supv\ui\ufrmDisplayPOSMonitor.pas' {frmDisplayPOSMonitor},
  ufrmFinalPayment in '..\store\module\cashier_supv\ui\ufrmFinalPayment.pas' {frmFinalPayment},
  ufrmDataCostumer in '..\store\module\customer_support\ui\ufrmDataCostumer.pas' {frmDataCostumer},
  ufrmMemberShip in '..\store\module\customer_support\ui\ufrmMemberShip.pas' {frmMemberShip},
  ufrmResetCashier in '..\store\module\cashier_supv\ui\ufrmResetCashier.pas' {frmResetCashier},
  ufrmReturNota in '..\store\module\cashier_supv\ui\ufrmReturNota.pas' {frmReturNota},
  ufrmSalesReportContrabon in '..\ho\module\inventory\ui\ufrmSalesReportContrabon.pas' {frmSalesReportContrabon},
  ufrmDialogCashDropping in '..\store\module\cashier_supv\ui\ufrmDialogCashDropping.pas' {frmDialogCashDropping},
  ufrmPopupHistCD in '..\store\module\cashier_supv\ui\ufrmPopupHistCD.pas' {frmPopupHistCD},
  uCashDropping in '..\store\module\cashier_supv\unit\cls\uCashDropping.pas',
  uSQLCashDropping in '..\store\module\cashier_supv\unit\sql\uSQLCashDropping.pas',
  ufrmDialogCreditCard in '..\store\module\cashier_supv\ui\ufrmDialogCreditCard.pas' {frmDialogCreditCard},
  ufrmPopupDetailCashback in '..\store\module\cashier_supv\ui\ufrmPopupDetailCashback.pas' {frmPopupDetailCashback},
  ufrmDialogFinalPayment in '..\store\module\cashier_supv\ui\ufrmDialogFinalPayment.pas' {frmDialogFinalPayment},
  uFinalPayment in '..\store\module\cashier_supv\unit\cls\uFinalPayment.pas',
  uSQLFinalPayment in '..\store\module\cashier_supv\unit\sql\uSQLFinalPayment.pas',
  ufrmPopupHistCDFP in '..\store\module\cashier_supv\ui\ufrmPopupHistCDFP.pas' {frmPopupHistCDFP},
  ufrmDialogDataCostumer in '..\store\module\customer_support\ui\ufrmDialogDataCostumer.pas' {frmDialogDataCostumer},
  uDataCustomer in '..\store\module\customer_support\unit\cls\uDataCustomer.pas',
  uSQLDataCustomer in '..\store\module\customer_support\unit\sql\uSQLDataCustomer.pas',
  ufrmSearchCompanyMember in '..\store\module\customer_support\ui\ufrmSearchCompanyMember.pas' {frmDialogSearchCompanyMember},
  uMemberShip in '..\store\module\customer_support\unit\cls\uMemberShip.pas',
  uSQLMemberShip in '..\store\module\customer_support\unit\sql\uSQLMemberShip.pas',
  ufrmDialogMemberShip in '..\store\module\customer_support\ui\ufrmDialogMemberShip.pas' {frmDialogMemberShip},
  ufrmDialogFamilyMember in '..\store\module\customer_support\ui\ufrmDialogFamilyMember.pas' {frmDialogFamilyMember},
  ufrmSearchStatusKlrg in '..\store\module\customer_support\ui\ufrmSearchStatusKlrg.pas' {frmDialogSearchStatusKlrg},
  uSearchStatusKlrg in '..\store\module\customer_support\unit\cls\uSearchStatusKlrg.pas',
  uSQLSearchStatusKlrg in '..\store\module\customer_support\unit\sql\uSQLSearchStatusKlrg.pas',
  ufrmDialogPersonalMember in '..\store\module\customer_support\ui\ufrmDialogPersonalMember.pas' {frmDialogPersonalMember},
  ufrmSearchTypeMember in '..\store\module\customer_support\ui\ufrmSearchTypeMember.pas' {frmDialogSearchTypeMember},
  uSearchTypeMember in '..\store\module\customer_support\unit\cls\uSearchTypeMember.pas',
  uSQLSearchTypeMember in '..\store\module\customer_support\unit\sql\uSQLSearchTypeMember.pas',
  ufrmPopupFamilyMember in '..\store\module\customer_support\ui\ufrmPopupFamilyMember.pas' {frmPopupFamilyMember},
  ufrmPopupPersonalMember in '..\store\module\customer_support\ui\ufrmPopupPersonalMember.pas' {frmPopupPersonalMember},
  uSQLResetCashier in '..\store\module\cashier_supv\unit\sql\uSQLResetCashier.pas',
  uResetCashier in '..\store\module\cashier_supv\unit\cls\uResetCashier.pas',
  ufrmDialogReturNota in '..\store\module\cashier_supv\ui\ufrmDialogReturNota.pas' {frmDialogReturNota},
  ufrmSearchProduct in '..\store\module\inventory\ui\ufrmSearchProduct.pas' {frmDialogSearchProduct},
  uGroups in '..\store\module\references\unit\cls\uGroups.pas',
  uSQLGroupSubGroupCategory in '..\store\module\references\unit\sql\uSQLGroupSubGroupCategory.pas',
  uSearchProduct in '..\store\module\inventory\unit\uSearchProduct.pas',
  uSQLSearchProduct in '..\store\module\inventory\unit\sql\uSQLSearchProduct.pas',
  ufraPaymentReturNota in '..\store\module\cashier_supv\ui\ufraPaymentReturNota.pas' {fraPaymentNotaRetur: TFrame},
  uReturNota in '..\store\module\cashier_supv\unit\cls\uReturNota.pas',
  uSQLReturNota in '..\store\module\cashier_supv\unit\sql\uSQLReturNota.pas',
  uReportSalesContrabon in '..\store\module\cashier_supv\unit\cls\uReportSalesContrabon.pas',
  uSQLReportSalesContrabon in '..\store\module\cashier_supv\unit\sql\uSQLReportSalesContrabon.pas',
  ufrmMemberActivation in '..\store\module\customer_support\ui\ufrmMemberActivation.pas' {frmMemberActivation},
  uMemberActivation in '..\store\module\customer_support\unit\cls\uMemberActivation.pas',
  uSQLMemberActivation in '..\store\module\customer_support\unit\sql\uSQLMemberActivation.pas',
  ufrmSearchCardNo in '..\store\module\customer_support\ui\ufrmSearchCardNo.pas' {frmDialogSearchCardNo},
  uSearchCardNo in '..\store\module\customer_support\unit\cls\uSearchCardNo.pas',
  uSQLSearchCardNo in '..\store\module\customer_support\unit\sql\uSQLSearchCardNo.pas',
  uFormLookUp in '..\uFormLookUp.pas' {FormLookUp},
  ufrmLoginAdminStore in 'source\module\main\ui\ufrmLoginAdminStore.pas' {frmLoginAdminStore},
  uLogin in '..\store\module\login\unit\uLogin.pas',
  ufrmDisplayPOSTransaction in '..\store\module\cashier_supv\ui\ufrmDisplayPOSTransaction.pas' {frmDisplayPOSTransaction},
  ufrmPopupDetailTransaction in '..\store\module\cashier_supv\ui\ufrmPopupDetailTransaction.pas' {frmPopupDetailTransaction},
  ufrmReprintNota in '..\store\module\cashier_supv\ui\ufrmReprintNota.pas' {frmReprintNota},
  uReprintNota in '..\store\module\cashier_supv\unit\cls\uReprintNota.pas',
  uSQLReprintNota in '..\store\module\cashier_supv\unit\sql\uSQLReprintNota.pas',
  uMasterItemBarang in 'source\module\main\unit\uMasterItemBarang.pas',
  uDivisi in 'source\module\main\unit\uDivisi.pas',
  uCategory in 'source\module\main\unit\uCategory.pas',
  uSubCategory in 'source\module\main\unit\uSubCategory.pas',
  uHargaJual in 'source\module\main\unit\uHargaJual.pas',
  uExportToMDB in 'source\module\main\unit\uExportToMDB.pas',
  ufrmImportFromMDB in 'source\module\main\ui\ufrmImportFromMDB.pas' {frmImportFromMDB},
  ufrmExportToMDB in 'source\module\main\ui\ufrmExportToMDB.pas' {frmExportToMDB},
  uCabang in 'source\module\main\unit\uCabang.pas',
  uRegional in 'source\module\main\unit\uRegional.pas',
  ufraFooter5Button in 'source\module\main\ui\ufraFooter5Button.pas' {fraFooter5Button: TFrame},
  udmReportNew in '..\system\udmReportNew.pas' {dmReportNew},
  uSQLCreateTableExport in '..\store\module\cashier_supv\unit\sql\uSQLCreateTableExport.pas',
  ufrmMaintenanceBarcode in '..\store\module\inventory\ui\ufrmMaintenanceBarcode.pas' {frmMaintenanceBarcode},
  ufrmDialogUpdateBarcode in '..\store\module\inventory\ui\ufrmDialogUpdateBarcode.pas' {frmDialogUpdateBarcode},
  uSQLProduct in '..\system\sql\uSQLProduct.pas',
  ufrmSearchPOBarcode in '..\store\module\inventory\ui\ufrmSearchPOBarcode.pas' {frmSearchPOBarcode},
  uSearchBarcode in '..\store\module\inventory\ui\uSearchBarcode.pas',
  uSQLBarcode in '..\store\module\inventory\ui\uSQLBarcode.pas',
  uSQLBarcodeRequest in '..\store\module\merchandise\unit\sql\uSQLBarcodeRequest.pas',
  ufrmSalesReport in '..\ho\module\inventory\ui\ufrmSalesReport.pas' {frmSalesReport};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TfrmMain, frmMain);
  Application.CreateForm(TdmReportNew, dmReportNew);
  Application.Run;
end.
