SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FN_GENERATESO](
	@MERCHANDISE_ID UNIQUEIDENTIFIER,
	@TANGGAL DATE
)
RETURNS @MYTABLE TABLE(
	BARANG_ID UNIQUEIDENTIFIER,
	SATUAN_ID UNIQUEIDENTIFIER,		
	MERCHAN_ID UNIQUEIDENTIFIER, 	
	MERCHANGROUP_ID UNIQUEIDENTIFIER,
	SUPLIER_MERCHAN_ID UNIQUEIDENTIFIER, 	
	SUPLIER_ID UNIQUEIDENTIFIER,
	SUPPLIERCODE VARCHAR(200),	
	SUPPLIERNAME VARCHAR(200),
	MERCHANGROUP VARCHAR(200),
	KODEBARANG VARCHAR(30),
	NAMABARANG VARCHAR(200),
	SATUAN VARCHAR(30),
	KONVERSI FLOAT,
	LEADTIME INT,
	STOCK FLOAT,
	ADS FLOAT,	
	MINQTY FLOAT,
	MAXQTY FLOAT,
	ROP FLOAT,
	QTYSO FLOAT,
	BUYPRICE FLOAT,
	DISC1 FLOAT,
	DISC2 FLOAT,
	DISC3 FLOAT,
	NETPRICE FLOAT,
	IS_BKP INT,
	IS_REGULAR INT	
)	
AS 
BEGIN
	DECLARE @DAYINDEX INTEGER = DATEPART(dw,GETDATE()) ;
	INSERT INTO @MYTABLE
		SELECT A.BARANG_ID, F.REF$SATUAN_ID, E.REF$MERCHANDISE_ID, E.REF$MERCHANDISE_GRUP_ID,
		D.SUPLIER_MERCHAN_GRUP_ID, C.SUPLIER_ID, C.SUP_CODE, C.SUP_NAME, E.MERCHANGRUP_NAME,
		A.BRG_CODE, A.BRG_NAME, G.SAT_CODE, F.KONVSAT_SCALE, D.SUPMG_LEAD_TIME, 
		(A.TEMP_STOCK/F.KONVSAT_SCALE) AS STOCK, (A.TEMP_AVGSALES/F.KONVSAT_SCALE) AS ADS, -- TEMPORARY 
		B.BRGSUP_MIN_ORDER, B.BRGSUP_MAX_ORDER,
		(D.SUPMG_LEAD_TIME * A.TEMP_AVGSALES/F.KONVSAT_SCALE * 3) AS ROP,
		(D.SUPMG_LEAD_TIME * A.TEMP_AVGSALES/F.KONVSAT_SCALE * 3) AS QTYSO,
		-- pricing
		B.BRGSUP_BUY_PRICE, B.BRGSUP_DISC1, B.BRGSUP_DISC2, B.BRGSUP_DISC3, 
		-- disc bertingkat
		((B.BRGSUP_BUY_PRICE * (100-B.BRGSUP_DISC1)/100) * (100-B.BRGSUP_DISC2)/100) - B.BRGSUP_DISC3 AS NETPRICE,
		B.BRGSUP_IS_BKP, 1 -- IDK REGULER MEANS		
		FROM BARANG A
		INNER JOIN BARANG_SUPLIER B ON A.BARANG_ID=B.BARANG_ID
		INNER JOIN SUPLIER C ON C.SUPLIER_ID=B.SUPLIER_ID
		INNER JOIN SUPLIER_MERCHAN_GRUP D ON D.SUPLIER_ID=C.SUPLIER_ID 
			AND A.REF$MERCHANDISE_GRUP_ID = D.REF$MERCHANDISE_GRUP_ID
		INNER JOIN REF$MERCHANDISE_GRUP E ON A.REF$MERCHANDISE_GRUP_ID=E.REF$MERCHANDISE_GRUP_ID
		INNER JOIN REF$KONVERSI_SATUAN F ON A.BARANG_ID=F.BARANG_ID 
			AND F.REF$SATUAN_ID=B.REF$SATUAN_PURCHASE
		INNER JOIN REF$SATUAN G ON G.REF$SATUAN_ID=F.REF$SATUAN_ID
		WHERE A.BRG_IS_ACTIVE = 1 AND A.BRG_IS_STOCK = 1 
		AND B.BRGSUP_IS_PRIMARY = 1 AND A.BRG_IS_CS = 0
		AND A.BRG_IS_GALON = 0 AND A.BRG_IS_DEPOSIT = 0
		--b.	Barang tidak masuk di table SO_BARANG_BLACKLIST
		--c.	Supplier tidak masuk di SO_SUPLIER_BLACKLIST
		--i.	BARANG.TIPE_BARANG = BARANG SENDIRI
		
		-- PERIOD FILTER
		AND (
			(D.SUPMG_IS_SUN = 1 AND @DAYINDEX = 1)
			OR (D.SUPMG_IS_MON = 1 AND @DAYINDEX = 2)
			OR (D.SUPMG_IS_TUE = 1 AND @DAYINDEX = 3)
			OR (D.SUPMG_IS_WED = 1 AND @DAYINDEX = 4)
			OR (D.SUPMG_IS_THU = 1 AND @DAYINDEX = 5)
			OR (D.SUPMG_IS_FRI = 1 AND @DAYINDEX = 6)
			OR (D.SUPMG_IS_SAT = 1 AND @DAYINDEX = 7)			
		)
		--
		
		AND E.REF$MERCHANDISE_ID = @MERCHANDISE_ID;

	UPDATE @MYTABLE SET QTYSO = MINQTY WHERE ROP < MINQTY;
	UPDATE @MYTABLE SET QTYSO = MAXQTY WHERE ROP > MAXQTY AND MAXQTY <> 0;
	UPDATE @MYTABLE SET QTYSO = CEILING(QTYSO);
	 
	RETURN
END
GO
